<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_X_1</name>
   <tag></tag>
   <elementGuidId>d386eb19-6727-4a38-899a-749177c1a999</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_graphs-table_close_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='lf_graphs-table_close_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;close the popup&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f46f1473-a103-4e8c-9a43-6fb36d89bca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f44c68a5-e78b-4dab-9546-bea62ffc867f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_graphs-table_close_btn</value>
      <webElementGuid>feb2e1d6-a99a-4f01-ac3f-b0f07e028db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-modal-close-btn</value>
      <webElementGuid>1f029597-2e67-4f9b-a64e-fa3955406629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a448bb33-eae3-4a42-ad16-4196e37dae9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>526ab420-4eb2-489b-98f1-e8b1bdea13e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>dece4f8a-22a2-4129-a34b-d77bdcaf8b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>close the popup</value>
      <webElementGuid>90b2907e-48ea-4467-b3f7-2ceaeeed14b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            X
        </value>
      <webElementGuid>cc81b401-78e6-43df-b127-29ab396712b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_graphs-table_close_btn&quot;)</value>
      <webElementGuid>9a4ce096-d047-4901-a18f-ca7ffa9d9d8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='lf_graphs-table_close_btn']</value>
      <webElementGuid>dd921a95-56dc-432b-819f-550698263856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_graphs-table']/div/button</value>
      <webElementGuid>d599eff8-df55-4565-a9b3-d5ca66bd6274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your payments over time'])[5]/following::button[1]</value>
      <webElementGuid>0ad40d6c-df2d-4339-9a76-3cba48726350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End of help content'])[1]/following::button[1]</value>
      <webElementGuid>a0648a23-041c-41c6-b1f5-57e96e31e2b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your payments over time'])[6]/preceding::button[1]</value>
      <webElementGuid>2d4f2d95-1a20-4ae4-94e5-8b070baea182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Month'])[1]/preceding::button[1]</value>
      <webElementGuid>ad4b41e6-d877-4c94-bde4-8015ccb33600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/button</value>
      <webElementGuid>01bc6c49-0be7-46aa-9c69-2748a86146c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'lf_graphs-table_close_btn' and @title = 'Close' and (text() = '
            X
        ' or . = '
            X
        ')]</value>
      <webElementGuid>19f075d7-7ff2-48b9-bf75-5743e1e2616f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
