<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Balance</name>
   <tag></tag>
   <elementGuidId>9713044b-6c62-41ee-98cf-ae8ce16cd110</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#col-3 > span.lf-table-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='col-3']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Balance&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d390a87a-92fe-4256-87e4-2a30738436b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-table-header</value>
      <webElementGuid>2c3e3624-f3f9-499b-bc47-b9c14e30ac76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Balance</value>
      <webElementGuid>b470deb5-4837-46a5-b472-2f0cfbf6f8c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;col-3&quot;)/span[@class=&quot;lf-table-header&quot;]</value>
      <webElementGuid>85f517b5-d3d8-46d9-a1d5-534d7abd21af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='col-3']/span</value>
      <webElementGuid>ff49f342-d2b2-4293-92bc-96363c8baadf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly payment'])[3]/following::span[1]</value>
      <webElementGuid>a61a1be6-41ba-4838-a29b-334043fce5dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Month'])[1]/following::span[2]</value>
      <webElementGuid>3324ab64-a06b-4d17-842c-111e91de16e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Principal paid'])[1]/preceding::span[1]</value>
      <webElementGuid>19c8fe47-16f9-44a7-b598-15524dc47c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interest paid'])[1]/preceding::span[2]</value>
      <webElementGuid>07c28f3f-d910-48c8-85a4-afd354d73767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Balance']/parent::*</value>
      <webElementGuid>ebc695dd-c74a-46c4-9aca-605c72244e24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/span</value>
      <webElementGuid>14b03da5-84f7-4a0c-a35d-415996394c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Balance' or . = 'Balance')]</value>
      <webElementGuid>f7226833-9cb8-4956-b1c8-f52ffa4a9450</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
