<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Must be between 0.00 and 90.00_Global_609372</name>
   <tag></tag>
   <elementGuidId>2638839c-9770-42e0-8edd-05d2387b8df9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_Global_FederalAndStateTaxRate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lf_Global_FederalAndStateTaxRate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Your state &amp; federal tax rate, as a percent&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b41bbaf-da7e-417b-8172-376dd07d1d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Global_FederalAndStateTaxRate</value>
      <webElementGuid>e683eae8-e0cb-45c7-a1fa-4466f03f16b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Global_FederalAndStateTaxRate</value>
      <webElementGuid>09a0fc8f-aca1-4c33-80bb-3d36661e6694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-input-comma</value>
      <webElementGuid>f66dce9f-fd5d-4bd0-ab6d-27e87cbd3a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cddc7437-27e5-4f18-8bc7-9d3214107c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>33.80</value>
      <webElementGuid>19ac0608-300a-43da-9d32-2b457634cfcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>6fa08f35-6277-484c-bfca-db7f0c76d518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Your state &amp; federal tax rate, as a percent</value>
      <webElementGuid>9b7f41f2-1d6a-483d-8b81-0f87d6dff1a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b4b368c4-8bae-4503-9ddd-509ad2c77a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Global_FederalAndStateTaxRate&quot;)</value>
      <webElementGuid>420f50dd-5eba-4e00-9019-bc44cf45c71d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lf_Global_FederalAndStateTaxRate']</value>
      <webElementGuid>7619c662-46e8-4a88-ac19-8af291170f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Global_FederalAndStateTaxRate_container']/div[3]/input</value>
      <webElementGuid>bec3bcec-2e60-43b3-8f53-83a7d1752b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/div/div[2]/div[3]/input</value>
      <webElementGuid>42033c99-fb2c-492d-92f1-dc98de587a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lf_Global_FederalAndStateTaxRate' and @name = 'Global_FederalAndStateTaxRate' and @type = 'text']</value>
      <webElementGuid>9b55a153-2773-4d27-bad3-9d1df7d900c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
