<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_i_1_2</name>
   <tag></tag>
   <elementGuidId>3c1979a4-bff7-4694-82f7-1ca9e649f677</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_Auto_UsedVehicleDownPayment_tooltip > div.lf-tooltip-i</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lf_Auto_UsedVehicleDownPayment_tooltip']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>13f9e0dd-8547-4492-8f15-1a5601084c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8753d3a6-eec2-4fa2-ac85-c2e996870b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-tooltip-i</value>
      <webElementGuid>d8a608cf-b4bb-4827-8154-e587d763d0f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ec56a1f6-5456-4f4e-b9cc-d4adbc4eba82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Auto_UsedVehicleDownPayment_tooltip&quot;)/div[@class=&quot;lf-tooltip-i&quot;]</value>
      <webElementGuid>854ee97f-529b-431c-adde-24a9987ec30d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='lf_Auto_UsedVehicleDownPayment_tooltip']/div</value>
      <webElementGuid>a68b8904-b574-49b9-9a4a-98997073924d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Down payment'])[3]/following::div[1]</value>
      <webElementGuid>a76e1af7-fe22-443f-897d-fb74d93d12bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase price'])[4]/following::div[3]</value>
      <webElementGuid>d585e95c-1ea3-4d1c-9928-40042a88c39c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between $0 and $249,999'])[2]/preceding::div[1]</value>
      <webElementGuid>afdd3ed0-88aa-4b8f-93a0-e8f20e6f3f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Down payment'])[4]/preceding::div[2]</value>
      <webElementGuid>14e64f76-4f4b-48e2-81bf-89332daf5114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div[3]/div[2]/div/a/div</value>
      <webElementGuid>23436647-527a-48f7-973d-f10e9a053de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'i' or . = 'i')]</value>
      <webElementGuid>5e99631f-9fef-483a-9af3-e1a100b503fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
