<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Next Steps</name>
   <tag></tag>
   <elementGuidId>9cb28933-584f-4613-8f2e-a4b86ac3b8a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_next_steps_zoneA_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='lf_next_steps_zoneA_title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>dee568a9-d4d6-4c19-baf9-be228daaa6ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_next_steps_zoneA_title</value>
      <webElementGuid>40695e97-61c7-465c-893f-3a1dd7393b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-modal-title</value>
      <webElementGuid>df561c5e-314c-4c22-885e-46faa931cb72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next Steps</value>
      <webElementGuid>b4f868ea-714f-4a7d-b54d-dd548d239ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_next_steps_zoneA_title&quot;)</value>
      <webElementGuid>21de3871-1b22-488c-bd06-47d5df252434</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='lf_next_steps_zoneA_title']</value>
      <webElementGuid>48387f07-5f06-4980-93e9-c32fea22b0d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_next_steps_zoneA']/div/h2</value>
      <webElementGuid>80d40c93-ab5e-4fbe-8aba-f4f6830f0e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next Steps'])[2]/following::h2[2]</value>
      <webElementGuid>4d44da0e-23ac-487c-b7f7-2d580667501e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2025 Leadfusion'])[1]/following::h2[3]</value>
      <webElementGuid>59338fa0-2d33-47ed-810c-891d188e7357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click Here'])[3]/preceding::h2[1]</value>
      <webElementGuid>8ca76e2d-8831-44dc-b925-63ccfd138353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cs@leadfusion.com'])[3]/preceding::h2[1]</value>
      <webElementGuid>76a823f4-3524-42bc-89cf-6ae9330af3a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h2</value>
      <webElementGuid>fa1e3b14-148a-4bfb-9b12-0651c5c02975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'lf_next_steps_zoneA_title' and (text() = 'Next Steps' or . = 'Next Steps')]</value>
      <webElementGuid>7ce6ef8c-5124-4175-8f16-0ce2fbb144fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
