<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Must be between 1 and 30_Auto_YearsOwned (1)</name>
   <tag></tag>
   <elementGuidId>7b34dbd1-b3e5-4263-9238-33d9fe752b41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lf_Auto_YearsOwned']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lf_Auto_YearsOwned</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61f8a6b9-ba16-4299-8bb6-a517816762ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Auto_YearsOwned</value>
      <webElementGuid>9ddf2fe3-1d65-445c-becb-eb624b62d982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Auto_YearsOwned</value>
      <webElementGuid>dfe718ad-e8eb-4890-9d79-213aa2535abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-input-comma</value>
      <webElementGuid>8cc7df8b-0f68-4a24-aa11-ff8e5e865a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c271afe2-060d-4b9f-993f-c90733fa939e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>98fd45ca-95f8-4137-a3e0-ab585057ce9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5800dfc2-bc4c-4df6-9c8e-f142a119a8fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Years you will own vehicle</value>
      <webElementGuid>447d17ca-bfd6-46a3-bf92-f936f3f003ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Auto_YearsOwned&quot;)</value>
      <webElementGuid>ee2c748c-7253-4901-a7c2-655c5451d63f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lf_Auto_YearsOwned']</value>
      <webElementGuid>dd4db203-94c6-41ae-86ef-07fd37cc3bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Auto_YearsOwned-table']/div[3]/input</value>
      <webElementGuid>f6034e73-9233-46fe-9320-f35fe6b01203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div[3]/div/div[3]/input</value>
      <webElementGuid>217d97be-cb38-4824-bd81-91494f58bfe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lf_Auto_YearsOwned' and @name = 'Auto_YearsOwned' and @type = 'text']</value>
      <webElementGuid>f4dcd9c6-7feb-4a15-ad5e-54d20dd19953</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
