<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Must be between 0 and 249,999_Auto_Us_3b2be1</name>
   <tag></tag>
   <elementGuidId>fbaa00eb-d60e-42fc-8243-95aea8044e68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lf_Auto_UsedVehicleDownPayment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lf_Auto_UsedVehicleDownPayment</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>340a71c6-be84-4f16-8cab-c8912ffa7e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Auto_UsedVehicleDownPayment</value>
      <webElementGuid>3c1b5e68-22e8-45e2-8ad6-631b73790716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Auto_UsedVehicleDownPayment</value>
      <webElementGuid>26c00d2e-f853-46ba-8e19-5c8f9c3aea2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-input-comma</value>
      <webElementGuid>ed576ba1-afe6-4134-a0a8-641ff07084bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8c7b2f0e-4ce9-4713-ae7c-39e2c11b100c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>d6dc9bfe-abf6-496d-98be-580cacad8837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>4af2e641-d7df-4fad-ab8c-0ef3fd23f76f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Down payment, in dollars</value>
      <webElementGuid>acf52346-33cf-4c04-a930-2186176e4127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Auto_UsedVehicleDownPayment&quot;)</value>
      <webElementGuid>a273dc7a-ce8e-48c7-99f1-9f2406e35d1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lf_Auto_UsedVehicleDownPayment']</value>
      <webElementGuid>2daced5d-a583-4b14-97a7-19fabb3f6c4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Auto_UsedVehicleDownPayment-table']/div[3]/input</value>
      <webElementGuid>6bbe5233-8e89-41fd-9e4a-559d517e48a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div[3]/div[2]/div[3]/input</value>
      <webElementGuid>187935c5-90d3-44f8-8e04-b90f70e36542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lf_Auto_UsedVehicleDownPayment' and @name = 'Auto_UsedVehicleDownPayment' and @type = 'text']</value>
      <webElementGuid>a100b7a9-aded-4dcf-8dc3-29be9edf9a6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
