<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Must be between 0 and 10,000_Auto_MonthlyInsurance</name>
   <tag></tag>
   <elementGuidId>0d9a23c8-1268-4f08-ac6e-6a567b9356e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lf_Auto_MonthlyInsurance']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'lf_Auto_MonthlyInsurance' and @name = 'Auto_MonthlyInsurance' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lf_Auto_MonthlyInsurance</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9ac08c7-0f87-47bf-9f97-b0fa760f69c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Auto_MonthlyInsurance</value>
      <webElementGuid>7e7481f0-a0ff-4dac-851c-647c349d31b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Auto_MonthlyInsurance</value>
      <webElementGuid>33de8827-9f40-4365-9bf8-a87f6c7aafec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-input-comma</value>
      <webElementGuid>f161fa30-f629-4daa-812e-876acc91101a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>22513b98-0408-438e-9ac3-560dd2d450b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>1ac804c7-7792-4d1e-84b3-018e3bda0ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>11a1adde-8bba-4140-bb39-091c6fc3647b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Monthly insurance costs, in dollars</value>
      <webElementGuid>c74f574b-a84e-4c66-9a75-1e713ef20594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Auto_MonthlyInsurance&quot;)</value>
      <webElementGuid>3833a3cc-9cd4-4c92-b0a9-a7969d729009</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lf_Auto_MonthlyInsurance']</value>
      <webElementGuid>0269687a-a098-4615-932b-06f811c8799f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Auto_MonthlyInsurance-table']/div[3]/input</value>
      <webElementGuid>37bb9760-b155-4ead-b024-0f02b1361b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div[3]/div[3]/div[3]/input</value>
      <webElementGuid>f2bc8204-3f84-4ec1-accc-733c93f61aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lf_Auto_MonthlyInsurance' and @name = 'Auto_MonthlyInsurance' and @type = 'text']</value>
      <webElementGuid>31abdeaa-f51a-4a67-9a07-0599560fd285</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
