<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Interest rate_1</name>
   <tag></tag>
   <elementGuidId>d7282972-da1c-4256-8d55-ee0fd1440dc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_Auto_UsedVehicleInterestRate-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='lf_Auto_UsedVehicleInterestRate-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>716c018e-86e8-424d-ab8e-dab0f8f2c8ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>lf_Auto_UsedVehicleInterestRate</value>
      <webElementGuid>778741f6-28cc-4501-96c9-e75c7c8c77b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Auto_UsedVehicleInterestRate-label</value>
      <webElementGuid>635c9457-e4a2-415a-aad5-7ad6da6a2bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-field-label-no-tooltip</value>
      <webElementGuid>05cccadc-bf7f-4db8-9d90-5c4dffeb3c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Interest rate
                                
                        </value>
      <webElementGuid>0024c0dc-3c80-442f-ae35-7414758420c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Auto_UsedVehicleInterestRate-label&quot;)</value>
      <webElementGuid>9e4ba2c8-adbd-4aa1-bbe9-8aead58f7bf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='lf_Auto_UsedVehicleInterestRate-label']</value>
      <webElementGuid>5edb84c2-5e22-4694-aca3-70b5266629e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Auto_UsedVehicleInterestRate-table']/div/label</value>
      <webElementGuid>efd56aa6-a5e3-47e0-b41f-2f4a539986d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Down payment'])[4]/following::label[1]</value>
      <webElementGuid>ad876784-4867-4089-9e74-db20fcaff948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between $0 and $249,999'])[2]/following::label[2]</value>
      <webElementGuid>e2652ad7-9d97-482e-a9eb-84bdb9258027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between 0.00% and 50.00%'])[2]/preceding::label[1]</value>
      <webElementGuid>d19ff08c-aa97-475b-bdbe-db0ecc553ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interest rate'])[4]/preceding::label[1]</value>
      <webElementGuid>404f309f-acfb-46fe-a0d4-96311bc6fb4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div[3]/div[3]/div/label</value>
      <webElementGuid>5ee3ce67-4af9-4ce2-a719-a1aad261207c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'lf_Auto_UsedVehicleInterestRate-label' and (text() = 'Interest rate
                                
                        ' or . = 'Interest rate
                                
                        ')]</value>
      <webElementGuid>d8f0a525-d7a8-4ca0-8a1c-901bd9f6ab8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
