<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Loan term  (months)</name>
   <tag></tag>
   <elementGuidId>0175677b-00bd-4321-99ca-37e0e0fb58d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'lf_Auto_UsedVehicleLoanTerm-label' and (text() = 'Loan term  (months)' or . = 'Loan term  (months)')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lf_Auto_UsedVehicleLoanTerm-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='lf_Auto_UsedVehicleLoanTerm-label']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>fd780768-268b-465f-af1f-ba54a87cfe89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>lf_Auto_UsedVehicleLoanTerm</value>
      <webElementGuid>5f182bf9-272d-4395-8ec4-a39efb2159b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Auto_UsedVehicleLoanTerm-label</value>
      <webElementGuid>83a6cf19-2dd7-41e5-8097-74b6fe58ced4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Loan term  (months)</value>
      <webElementGuid>e7ee06f9-83f1-40f4-86d1-88939ab778ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Auto_UsedVehicleLoanTerm-label&quot;)</value>
      <webElementGuid>8ede887f-ddd6-4ffc-90ce-e80f79f087af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='lf_Auto_UsedVehicleLoanTerm-label']</value>
      <webElementGuid>bfe06049-8c61-4217-a2eb-bf1004b62c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Auto_UsedVehicleLoanTerm-table']/div/label</value>
      <webElementGuid>b30c7242-02e9-4e72-ae84-f8a4e13d0c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interest rate'])[4]/following::label[1]</value>
      <webElementGuid>4780117c-25f3-4488-ab9c-8f883107f8da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between 0.00% and 50.00%'])[2]/following::label[2]</value>
      <webElementGuid>9c0e9adf-1ba0-4679-a8fa-036b4c1fbda3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between 1 and 360'])[2]/preceding::label[1]</value>
      <webElementGuid>be3cfe35-9302-4417-b8df-9d36e5e81e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div[3]/div[4]/div/label</value>
      <webElementGuid>511ede38-0aee-46fe-ae85-8bcf290245f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'lf_Auto_UsedVehicleLoanTerm-label' and (text() = 'Loan term  (months)' or . = 'Loan term  (months)')]</value>
      <webElementGuid>00413bae-790f-4c05-a9fd-9b85e424ebe6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
