<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Years of ownership. The longer you own th_aa892f</name>
   <tag></tag>
   <elementGuidId>c33f9f9f-2fb8-4a7c-b82c-4ebaf1dbb6e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_help_4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='lf_help_4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>60e7de0b-81ad-477b-aae1-2b84b0dab19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_help_4</value>
      <webElementGuid>efd48388-dac4-4f76-a3e3-bab27db9f2fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Years of ownership. The longer you own the vehicle, the lower the average annual cost, as acquisition costs are spread out over more years.</value>
      <webElementGuid>ad2fe8f2-968e-4926-ace6-ada6f479320a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_help_4&quot;)</value>
      <webElementGuid>8eeb5d87-0941-4729-841e-13bc4b818a74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='lf_help_4']</value>
      <webElementGuid>b4e88c54-0da9-45aa-8233-663f8226c5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='lf-help-content']/p[5]</value>
      <webElementGuid>b96b5d61-f8f3-4e7d-bbca-b13be85e710b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operating costs.'])[1]/following::p[1]</value>
      <webElementGuid>eda95d4c-1574-4f72-a6d7-dc9553da5b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Depreciation.'])[1]/following::p[2]</value>
      <webElementGuid>c62d1444-7487-4770-8a76-9f588d4b6253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Financing cost.'])[1]/preceding::p[1]</value>
      <webElementGuid>f21ec5c5-b21c-4b1b-bd28-57447782bade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The longer you own the vehicle, the lower the average annual cost, as acquisition costs are spread out over more years.']/parent::*</value>
      <webElementGuid>fd94acf8-aad2-4f5d-beb8-185345526a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[5]</value>
      <webElementGuid>d3b03c7a-7353-4fcb-8831-a79c3f0c6649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'lf_help_4' and (text() = 'Years of ownership. The longer you own the vehicle, the lower the average annual cost, as acquisition costs are spread out over more years.' or . = 'Years of ownership. The longer you own the vehicle, the lower the average annual cost, as acquisition costs are spread out over more years.')]</value>
      <webElementGuid>637bb0ca-c2f0-48b2-8620-5f79cc16883c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
