<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_(years)</name>
   <tag></tag>
   <elementGuidId>2b49ddac-1882-4e05-b4ef-f4a0c2dce23b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_Auto_UsedVehicleAgeInYears-small-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='lf_Auto_UsedVehicleAgeInYears-small-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d08436a6-6819-4d98-9baa-bfac66979a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Auto_UsedVehicleAgeInYears-small-label</value>
      <webElementGuid>2f1993a6-a2af-4487-a55f-349a2ad040d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-small-label</value>
      <webElementGuid>2eacb875-b5b1-4577-8b53-5d64f7c2f42f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (years)</value>
      <webElementGuid>40aa01d0-71de-4230-9dab-a21a7799f054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Auto_UsedVehicleAgeInYears-small-label&quot;)</value>
      <webElementGuid>c9d571c6-12ec-4d67-9d51-9ac22e1d790c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='lf_Auto_UsedVehicleAgeInYears-small-label']</value>
      <webElementGuid>293779f4-e7a7-4e27-b29e-aa0b7dec69aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='lf_Auto_UsedVehicleAgeInYears-label']/span</value>
      <webElementGuid>be2fcbe8-e1ed-45d4-b983-1a44e00dcb02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Used Vehicle Cost'])[1]/following::span[1]</value>
      <webElementGuid>0cb45449-a7b9-462e-bc2e-d7872da5cf8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between 0 and 30'])[1]/preceding::span[1]</value>
      <webElementGuid>9b124f48-d071-4c95-8d98-d050338c0767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle age'])[1]/preceding::span[4]</value>
      <webElementGuid>7a81ec4d-7871-4a87-a0e6-25701cd2e66e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='(years)']/parent::*</value>
      <webElementGuid>bdf6297b-54c7-452f-8cda-08f1abdfe75e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/div[3]/div/div/label/span</value>
      <webElementGuid>02722066-cf34-4cbc-95ff-0ad4e8ae05c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'lf_Auto_UsedVehicleAgeInYears-small-label' and (text() = ' (years)' or . = ' (years)')]</value>
      <webElementGuid>5eeee29d-c29c-48e7-9262-a28c20dabe40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
