<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_5,136</name>
   <tag></tag>
   <elementGuidId>2b62b409-2bde-4882-998d-5f0598af1a43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='lf_AveCostPerYr2Auto01_result_value']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lf_AveCostPerYr2Auto01_result_value > span.lf-nbsp-number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>51b0a113-be32-47ee-9e50-da9f0e7b1b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-nbsp-number</value>
      <webElementGuid>54764b91-ff3c-40a7-94bd-9630a0235b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$5,136</value>
      <webElementGuid>36bac86d-abdc-4617-a9ae-2bd184c9d30f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_AveCostPerYr2Auto01_result_value&quot;)/span[@class=&quot;lf-nbsp-number&quot;]</value>
      <webElementGuid>d11860cb-3e98-4bbb-a5db-3e091954a7ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='lf_AveCostPerYr2Auto01_result_value']/span</value>
      <webElementGuid>e7986ffd-9a57-4a10-8f8c-12bdf1b72e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$13,368'])[1]/following::span[1]</value>
      <webElementGuid>e1729101-e604-4a51-b52b-e3018c2706b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Average cost per year'])[1]/following::span[2]</value>
      <webElementGuid>b9a324b0-bb60-4d39-a567-c887bb866623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly payment'])[1]/preceding::span[1]</value>
      <webElementGuid>ed9f4805-42e4-4237-8838-1b0e6bf2bd0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1,879'])[1]/preceding::span[1]</value>
      <webElementGuid>d3de6006-8f0f-4f4b-bee0-3d7b10314be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$5,136']/parent::*</value>
      <webElementGuid>ededd0d4-65d9-4a3a-8915-3d30ab6aa0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span</value>
      <webElementGuid>e27e41b4-b6ea-46b4-a1eb-c83b1805da60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '$5,136' or . = '$5,136')]</value>
      <webElementGuid>b7f8eb24-275e-4864-81e0-af546155d0a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
