<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Down payment</name>
   <tag></tag>
   <elementGuidId>4aab97ca-d65c-4e94-8db4-c943ddd0e440</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf-tooltip-term</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='lf-tooltip-term']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>def02f25-caac-4721-adce-fc0359873d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf-tooltip-term</value>
      <webElementGuid>6405186b-135a-46f7-8836-d2f96634c056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Down payment</value>
      <webElementGuid>f6a4c7d2-3d87-4ec8-ab40-da8e10e6733c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Down payment</value>
      <webElementGuid>1be60a46-1363-4bcd-ac87-f50bd16cc6e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf-tooltip-term&quot;)</value>
      <webElementGuid>558fac6e-52fa-48a7-854b-f57936cfa72a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='lf-tooltip-term']</value>
      <webElementGuid>80eab865-fa6b-4738-af18-0990309fc4aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf-tooltip']/dfn/h2/span</value>
      <webElementGuid>82915211-e52d-4633-a46a-6ff65005cfa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next Steps'])[2]/following::span[2]</value>
      <webElementGuid>2a750371-f2c5-4249-9dcf-d09c1464d8bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2025 Leadfusion'])[1]/following::span[2]</value>
      <webElementGuid>c03f7d08-5f49-4e0b-974e-1e422fde1e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next Steps'])[3]/preceding::span[2]</value>
      <webElementGuid>c6703b27-be8a-4cb3-ad4f-6eb91edbe4cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click Here'])[3]/preceding::span[3]</value>
      <webElementGuid>7a3e1f4d-3f98-4409-bbcb-5362658db29d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dfn/h2/span</value>
      <webElementGuid>64b8ab10-993c-4366-bd42-c363046743da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'lf-tooltip-term' and (text() = 'Down payment' or . = 'Down payment')]</value>
      <webElementGuid>c8520d2a-3b62-4948-8222-d07267f9a923</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
