<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_7,735</name>
   <tag></tag>
   <elementGuidId>bd7af5dd-9f3f-489c-a78c-5fcee99c458b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_AveCostPerYrAuto01_result_value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='lf_AveCostPerYrAuto01_result_value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>8a9be5fa-59ae-4981-9573-67ac15bac336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_AveCostPerYrAuto01_result_value</value>
      <webElementGuid>1e7c4cda-b7e8-448e-b212-401f5b4c278c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableCellADA </value>
      <webElementGuid>0db192f2-db87-4fa0-be41-44623ae7027c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$7,735
                                        </value>
      <webElementGuid>0ad1bbac-bfe7-46b3-a52b-09a541a45a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_AveCostPerYrAuto01_result_value&quot;)</value>
      <webElementGuid>0eead186-0c79-4e11-975c-f7909759fe10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='lf_AveCostPerYrAuto01_result_value']</value>
      <webElementGuid>b2e0ab1c-dd3f-4759-81bc-ad09ae93a328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='lf_AveCostPerYrAuto01_results']/td</value>
      <webElementGuid>4f7933bb-1fb4-4b05-9b12-7e81d6e7577b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Average cost per year'])[1]/following::td[1]</value>
      <webElementGuid>34ea2ff0-559d-4a69-8b48-060f6e2d633b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Used'])[1]/following::td[1]</value>
      <webElementGuid>db6eeb3b-1273-436e-9071-9ec91dad4b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$3,193'])[1]/preceding::td[1]</value>
      <webElementGuid>963c5009-fdad-4a9b-b25f-0f1ebaffef0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/td</value>
      <webElementGuid>9d5722f6-9b36-46bd-8a7f-f698f8edc226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'lf_AveCostPerYrAuto01_result_value' and (text() = '$7,735
                                        ' or . = '$7,735
                                        ')]</value>
      <webElementGuid>7782aa24-2b9e-41e9-a5e3-70e91b1a2a7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
