<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Category</name>
   <tag></tag>
   <elementGuidId>ef24c868-47ed-4dfe-9cb0-a2188c51c958</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.highcharts-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='highcharts-data-table-0']/thead/tr/th</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>fc7e56fa-3515-49d2-aebb-6a1210117ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>highcharts-text</value>
      <webElementGuid>45a944f6-52c1-4028-9418-cd7dfebfa14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>4a81c50e-4f9e-4338-a1d3-b9cf137167f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Category</value>
      <webElementGuid>0b5d07c5-e5c1-49e8-b3f1-ed45490eca48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-data-table-0&quot;)/thead[1]/tr[1]/th[@class=&quot;highcharts-text&quot;]</value>
      <webElementGuid>102408a5-1360-4baf-86e5-2036efa4b0d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='highcharts-data-table-0']/thead/tr/th</value>
      <webElementGuid>631eef6d-9591-42b8-86c7-7c3198faf1e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Average cost per year of the new vehicle and the used vehicle'])[3]/following::th[1]</value>
      <webElementGuid>99eeb773-84a3-4b5f-bf78-03a947c1a732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End of interactive chart.'])[1]/following::th[1]</value>
      <webElementGuid>a0befeb2-7aef-442a-867e-32dd97b09d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[3]/preceding::th[1]</value>
      <webElementGuid>ebd5e95a-d872-4359-a8da-86053211530b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Used'])[3]/preceding::th[2]</value>
      <webElementGuid>3d92e7c5-d0f7-43de-8c78-5860a5033dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Category']/parent::*</value>
      <webElementGuid>c3e95d35-7163-49ba-967b-77c60d60d17f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/thead/tr/th</value>
      <webElementGuid>d140b068-d6dc-4f5a-903d-933fd500d494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Category' or . = 'Category')]</value>
      <webElementGuid>8ccdfa61-5250-4bcc-a26f-b45a8cb8b21b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
