<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_FutureDepreciation</name>
   <tag></tag>
   <elementGuidId>b80a24f8-266f-4433-8eea-0af923f2f297</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='lf_Auto_FutureDepreciation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lf_Auto_FutureDepreciation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Future depreciation&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5de5c48b-22f0-4f70-8c78-2a7b931dffe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-select-toggle</value>
      <webElementGuid>cd6a28f9-a14c-441a-9b79-8a1e1c80d7b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Auto_FutureDepreciation</value>
      <webElementGuid>49826466-c817-4775-bdca-f8ad2de4d0ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Auto_FutureDepreciation</value>
      <webElementGuid>26b9b529-5c9c-4a41-8f7e-2edcdeb9e5e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>62b270d0-1961-4016-ba93-1e55aa1d430b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Future depreciation</value>
      <webElementGuid>90c830ce-3e1c-4692-b32b-88e12a4b3ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Low
                            Average
                            High
                        </value>
      <webElementGuid>273fa154-48f6-458e-949c-2381636bee86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Auto_FutureDepreciation&quot;)</value>
      <webElementGuid>96c47c59-e197-48d7-bd59-3d92e5206e3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='lf_Auto_FutureDepreciation']</value>
      <webElementGuid>cb0cfaad-ce5c-4ac2-a6be-ce6d77bfa847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Auto_FutureDepreciation_container']/div[3]/select</value>
      <webElementGuid>e240ed74-535a-46b0-929b-d9052b674708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error message for dropdown list here'])[1]/following::select[1]</value>
      <webElementGuid>3c31fe30-af77-4944-9467-23a41fc4634f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Future depreciation'])[1]/following::select[1]</value>
      <webElementGuid>b1c0b623-291f-42a7-92b0-311cf78427b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click Here'])[2]/preceding::select[1]</value>
      <webElementGuid>f8deed1d-3f37-4522-89a6-0a7f7eb9db55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cs@leadfusion.com'])[2]/preceding::select[1]</value>
      <webElementGuid>fdd4dfa3-1782-4d5d-8dd7-0af32a35f6b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>88605daf-b603-48f0-968b-20774f50cee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'Auto_FutureDepreciation' and @id = 'lf_Auto_FutureDepreciation' and (text() = '
                            Low
                            Average
                            High
                        ' or . = '
                            Low
                            Average
                            High
                        ')]</value>
      <webElementGuid>3dbd9047-69c6-4673-bcfd-903dfab9fd4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
