<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_i_1_2</name>
   <tag></tag>
   <elementGuidId>971a7a20-65e9-4f4c-aed4-1a146be98859</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_Global_FederalAndStateTaxRate_tooltip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lf_Global_FederalAndStateTaxRate_tooltip']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Show tooltip for Your state &amp; federal tax rate&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d700e4be-ba62-4586-acf7-a08a4f8adbe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1ac32358-5cdd-46ba-be8e-0129315343a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#taxrates</value>
      <webElementGuid>da2d5f44-a777-458b-97af-6e1b67f1b7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Global_FederalAndStateTaxRate_tooltip</value>
      <webElementGuid>472f91e2-ad8f-4817-8487-af614ebec87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-show-tooltip</value>
      <webElementGuid>bef566e6-eba3-4d62-a979-1d8aa6f68af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Show tooltip for Your state &amp; federal tax rate</value>
      <webElementGuid>d47ee248-042d-4280-a46b-d5133667b2a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>929b7dee-6ce2-42e1-be72-e334c6557e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>5860e3ea-e698-4f60-a6f6-9d120d41c499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Global_FederalAndStateTaxRate_tooltip&quot;)</value>
      <webElementGuid>96c6a1ef-0736-4a63-bee1-f74f0fb5fa96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lf_Global_FederalAndStateTaxRate_tooltip']</value>
      <webElementGuid>e8fc49e5-fd0a-443b-9e98-981b930cbd97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Global_FederalAndStateTaxRate-table']/div/a</value>
      <webElementGuid>5ede6bef-d077-41d8-9f97-44b7eeeeb0a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your state &amp; federal tax rate'])[1]/following::a[1]</value>
      <webElementGuid>e5d2d3e4-fa69-4f88-a8a4-172aa90dd790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tax &amp; Savings Rates'])[1]/following::a[1]</value>
      <webElementGuid>537f0008-7c25-441a-a574-2a55c4ce600c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between 0.00% and 90.00%'])[1]/preceding::a[1]</value>
      <webElementGuid>f4d54ee2-4825-467f-8c2a-d9fe65b06b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your state &amp; federal tax rate'])[2]/preceding::a[1]</value>
      <webElementGuid>865997ee-0f7a-44f8-a940-071aa37651ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#taxrates')]</value>
      <webElementGuid>999a7caa-53a9-4cf7-bef0-379dc1196d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/div[3]/div/div/a</value>
      <webElementGuid>8a8c7e5c-5404-4053-aabf-3e8b8d924225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#taxrates' and @id = 'lf_Global_FederalAndStateTaxRate_tooltip' and (text() = 'i' or . = 'i')]</value>
      <webElementGuid>02143b9d-f31a-4f9f-ae25-4ef5d3313737</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
