<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_The rebate is the better deal.  In tod_5cc545</name>
   <tag></tag>
   <elementGuidId>d17d9966-a699-45eb-b2b3-614a2e4ce4d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_answer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='lf_answer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#lf_answer</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f7ec767d-aa7e-41ac-8885-610ae64d9e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_answer</value>
      <webElementGuid>85a86d60-f370-408d-a322-68cbc54ca974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The rebate is the better deal.  In today's dollars, you'll save $2,119.</value>
      <webElementGuid>754caaac-551b-4ceb-af10-e3606b1e48e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_answer&quot;)</value>
      <webElementGuid>f19c381e-186e-4da1-b88e-f80103075cba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='lf_answer']</value>
      <webElementGuid>b5cd85ad-2e5e-4a56-a451-126413135359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_main']/div/div[3]/div[3]/div/div[3]/h2/span</value>
      <webElementGuid>1e1ace52-e0e9-4722-8a65-710683b3b608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$2,119'])[1]/following::span[1]</value>
      <webElementGuid>76016cc4-342f-4659-8a10-ec0252bfca07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rebate'])[1]/following::span[2]</value>
      <webElementGuid>3a6e6003-423b-4c2f-b056-b0e172a4b57e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/span</value>
      <webElementGuid>36434f13-1b43-421d-bb2f-65c7be1fa0ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'lf_answer' and (text() = concat(&quot;The rebate is the better deal.  In today&quot; , &quot;'&quot; , &quot;s dollars, you&quot; , &quot;'&quot; , &quot;ll save $2,119.&quot;) or . = concat(&quot;The rebate is the better deal.  In today&quot; , &quot;'&quot; , &quot;s dollars, you&quot; , &quot;'&quot; , &quot;ll save $2,119.&quot;))]</value>
      <webElementGuid>6a009108-6b73-42a7-aaa6-b90f57f6a51c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
