<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Shared Loan Info</name>
   <tag></tag>
   <elementGuidId>ed95764b-dcab-49f7-909b-fcdb91b2a161</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#OtherInfo-accordion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='OtherInfo-accordion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Current selection, Shared Loan Info category, Click to hide details,&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5ad323fa-cd20-4d81-b88e-03e10f9625c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>833c42b3-0a78-4b99-b713-17ce8ac2b062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7c3c7342-1121-400a-b7d6-77581d5205db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OtherInfo-accordion</value>
      <webElementGuid>6311cf93-2d80-4f69-831b-6938cb4b3634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>lf-panel-OtherInfo</value>
      <webElementGuid>72295888-1139-4494-a14f-6e882f5d39aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-accordion-label</value>
      <webElementGuid>6a3bd731-52ba-4370-99a5-bcb548df9b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>1ac30cc5-042d-4af0-b7ca-c6c8b0841213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Current selection, Shared Loan Info category, Click to hide details,</value>
      <webElementGuid>650f0465-a414-43aa-9f00-b5a3a15b143b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d94ec5ab-9f4e-4c62-84f8-bcd62cfc8181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shared Loan Info</value>
      <webElementGuid>675270a4-ac12-472e-b9c2-019d6a5ee0c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OtherInfo-accordion&quot;)</value>
      <webElementGuid>77dbc361-92db-41e2-8762-33a0d70cb34a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='OtherInfo-accordion']</value>
      <webElementGuid>8f9c2386-6c07-4f7a-82ab-e48f88a65a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='lf-tab-OtherInfo']/div/h3/a</value>
      <webElementGuid>108ffcf7-ae5a-4973-b7d2-a63522006917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Shared Loan Info')]</value>
      <webElementGuid>5f813c53-6bb5-4481-ad7d-bc8bf4574cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inputs'])[1]/following::a[1]</value>
      <webElementGuid>7f41da5f-8ffb-411d-8f38-602b6f21e15e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cs@leadfusion.com'])[1]/following::a[1]</value>
      <webElementGuid>81844777-4066-4d54-ab35-a2eaa0db39b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase price'])[1]/preceding::a[1]</value>
      <webElementGuid>ee887cd4-44da-42c5-bbf1-b77e33ff681f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between $0 and $1,000,000'])[1]/preceding::a[1]</value>
      <webElementGuid>84057d6d-58b4-47ec-b989-5d897ad56568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Shared Loan Info']/parent::*</value>
      <webElementGuid>f809b131-219f-4a66-986a-f027d8fe96ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>5d413799-c71b-46f6-b7d6-a4b861cf115f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>4fa2531d-125e-426b-a660-571cdef15ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'OtherInfo-accordion' and @href = 'javascript:void(0)' and (text() = 'Shared Loan Info' or . = 'Shared Loan Info')]</value>
      <webElementGuid>f4d4cb54-2fde-4acb-8d60-86c7ad03e6fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
