<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Must be between 1 and 360_Global_Auto_8b1711</name>
   <tag></tag>
   <elementGuidId>9fb22b1b-52e9-4ef2-a8be-ad698bc66e71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_Global_AutoLoanTerm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lf_Global_AutoLoanTerm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Loan term, months&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74b51706-cf7e-40c8-adc0-0b4c96efe689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Global_AutoLoanTerm</value>
      <webElementGuid>28200cf9-8767-4e8f-94cf-ee6e4cf0bc70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Global_AutoLoanTerm</value>
      <webElementGuid>b4542295-c33e-4774-8b3a-93a081749caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-input-comma</value>
      <webElementGuid>05111da0-cf7b-43b7-9a0b-4ca7425435f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>645c2757-fff5-494a-845e-7cc8883d3054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>6f42a3e9-db3c-461e-8a32-dab9ce3cfaf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>251d47af-5261-464e-989b-abf96ac8854d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Loan term, months</value>
      <webElementGuid>48792e29-3ec8-4ec1-9486-17f5c1b9a070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4319869e-ea79-4027-9a06-9d1673851716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Global_AutoLoanTerm&quot;)</value>
      <webElementGuid>b4879831-6df0-41a3-815d-ebaebb5e11b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lf_Global_AutoLoanTerm']</value>
      <webElementGuid>6935e3df-eac0-422c-8eb6-386fd1367235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Global_AutoLoanTerm-table']/div[3]/input</value>
      <webElementGuid>fbaa8bb4-bd2e-4bc9-942a-14c8b4886d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div[3]/div/div[3]/input</value>
      <webElementGuid>b32a6051-ceab-4d4f-8777-e324e457e9eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lf_Global_AutoLoanTerm' and @name = 'Global_AutoLoanTerm' and @type = 'text']</value>
      <webElementGuid>fdee0225-d57a-4d8f-80b0-425d3e475abd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
