<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_875</name>
   <tag></tag>
   <elementGuidId>a1b1526b-7e1a-4c60-bb33-6ef2e4c73414</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_MonPmtAuto07_result_value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='lf_MonPmtAuto07_result_value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;$875&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c14385a6-5d49-41f7-8652-61adb61af4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_MonPmtAuto07_result_value</value>
      <webElementGuid>14a2ff66-8e13-4240-a9a7-0e9140cc6f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableCellADA </value>
      <webElementGuid>5c466bdd-dcd6-4ea7-812c-4b11f73aa0ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$875
                                        </value>
      <webElementGuid>f4bcc742-9465-4697-8912-c59059639c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_MonPmtAuto07_result_value&quot;)</value>
      <webElementGuid>4d57f4f9-5df2-4766-be88-6e46945c1e93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='lf_MonPmtAuto07_result_value']</value>
      <webElementGuid>909a5ab1-6f6c-4c41-91ac-d5491c7b03ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='lf_MonPmtAuto07_results']/td</value>
      <webElementGuid>7afb973f-896f-49d0-a91e-a10444a7b008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly payment'])[1]/following::td[1]</value>
      <webElementGuid>77a9503c-2390-430d-a8ac-173ef728ec1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loan 2'])[1]/following::td[1]</value>
      <webElementGuid>608da690-14aa-4672-b335-ad6da63474ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1,667'])[1]/preceding::td[1]</value>
      <webElementGuid>277c0935-6d18-4847-8674-ad9bb740edfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/td</value>
      <webElementGuid>9302307e-8435-48a6-99ba-67c7f8e9cd48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'lf_MonPmtAuto07_result_value' and (text() = '$875
                                        ' or . = '$875
                                        ')]</value>
      <webElementGuid>241f4a41-28ed-4517-9559-bf890947c834</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
