<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Down payment</name>
   <tag></tag>
   <elementGuidId>c4a1df26-ba50-4717-af68-8ba12642c361</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='lf_Global_AutoDownPayment-label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lf_Global_AutoDownPayment-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#lf_Global_AutoDownPayment-label</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b4fb866d-25b4-4bf9-807c-9b98a66a2d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>lf_Global_AutoDownPayment</value>
      <webElementGuid>4c38c074-ce23-4604-b3e0-81d046e35a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Global_AutoDownPayment-label</value>
      <webElementGuid>aca6eacb-5ff1-4b72-bd84-4161efc45bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Down payment </value>
      <webElementGuid>549f17a5-72f5-4c29-8d9a-88716ed49d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Global_AutoDownPayment-label&quot;)</value>
      <webElementGuid>110f3e2c-3bb2-4ba0-a9d2-c3fd2d938aac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='lf_Global_AutoDownPayment-label']</value>
      <webElementGuid>d9ff94d3-ab82-4c27-8c11-c652f2140333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Global_AutoDownPayment-table']/div/label</value>
      <webElementGuid>6793e166-144d-4bd6-802d-7766012e5e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase price'])[2]/following::label[1]</value>
      <webElementGuid>f408b44a-a57f-4703-bb98-98f2f0e469dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between $0 and $1,000,000'])[1]/following::label[2]</value>
      <webElementGuid>aed84efb-6c93-4a60-bd2e-274ad0247ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between $0 and $249,999'])[1]/preceding::label[1]</value>
      <webElementGuid>9a705030-e361-4392-a05b-c1976ce37b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Down payment'])[2]/preceding::label[1]</value>
      <webElementGuid>7901ccc6-148a-4088-bcc8-ee6f570c3f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Down payment']/parent::*</value>
      <webElementGuid>7c7d2000-9a76-41df-9eae-0588da31e602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label</value>
      <webElementGuid>63cbe1d7-b76a-4863-a5a7-41870f2589cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'lf_Global_AutoDownPayment-label' and (text() = 'Down payment ' or . = 'Down payment ')]</value>
      <webElementGuid>269175ed-7db5-43e6-803a-abcde24eabb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
