<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_5,588</name>
   <tag></tag>
   <elementGuidId>e46f8f0e-13fa-4843-b927-9a09b500854d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='lf_TotDep2Auto01_result_value']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lf_TotDep2Auto01_result_value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;$5,588&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>ce78daf3-2253-492f-ab13-023278efc952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_TotDep2Auto01_result_value</value>
      <webElementGuid>d33fd405-43ce-42f6-a74d-3290324f881b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableCellADA </value>
      <webElementGuid>c852d547-8a35-487b-a963-81d73d7ffde5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$5,588
                                        </value>
      <webElementGuid>11fa0bf0-2b7e-436c-ae21-c3110a055a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_TotDep2Auto01_result_value&quot;)</value>
      <webElementGuid>bac3c066-6e31-466a-99cb-fbfed6fa1b82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='lf_TotDep2Auto01_result_value']</value>
      <webElementGuid>2b8f0efa-610c-46a3-ab85-c93191734c00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='lf_TotDepAuto01_results']/td[2]</value>
      <webElementGuid>473d94ac-06b5-44fe-8a97-b384a7908444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$20,020'])[1]/following::td[1]</value>
      <webElementGuid>2222b163-3881-4f22-aaa6-a0bfaac5f97b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total depreciation'])[1]/following::td[2]</value>
      <webElementGuid>8df26290-7e4d-449e-81c5-3a87135cb7c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next Steps'])[1]/preceding::td[1]</value>
      <webElementGuid>b03cddb7-cd95-43bb-9685-f8ec47dea9d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]</value>
      <webElementGuid>807b1281-747b-486e-ac1b-4d7ea9c7ea05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'lf_TotDep2Auto01_result_value' and (text() = '$5,588
                                        ' or . = '$5,588
                                        ')]</value>
      <webElementGuid>11de04ac-2743-46f6-b9ff-a21e78e313ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
