<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Must be between 0 and 10,000_Global_H_712942</name>
   <tag></tag>
   <elementGuidId>b475ae17-6679-42c0-a2fd-5c197310848d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_Global_HomeEquityUpfrontCosts</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lf_Global_HomeEquityUpfrontCosts']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Upfront costs, in dollars&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>97b237e1-0bfa-4e96-bec7-49803766ef7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Global_HomeEquityUpfrontCosts</value>
      <webElementGuid>f8a27295-c7ea-49a9-bc6b-7f4c4659d980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Global_HomeEquityUpfrontCosts</value>
      <webElementGuid>8e61b473-0a4d-442a-aa08-974b28a303f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-input-comma</value>
      <webElementGuid>ea171e75-4d63-4213-880c-1e44f858e002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3a511b88-758c-4a29-947f-563ae75488a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>375</value>
      <webElementGuid>8d852f69-555e-4be6-b58c-5f07358f7aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>95b9d7cb-ddd6-4584-85ec-ccaba9a2d544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Upfront costs, in dollars</value>
      <webElementGuid>1042a899-3d68-48a5-bc2b-59a188c51f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9c1e67b1-b92a-43ae-b8c1-466850da3340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Global_HomeEquityUpfrontCosts&quot;)</value>
      <webElementGuid>95b814e5-3c38-461b-bc4d-f31e462945e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lf_Global_HomeEquityUpfrontCosts']</value>
      <webElementGuid>85c4fa33-d884-4301-8b5d-2922e52d0c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Global_HomeEquityUpfrontCosts-table']/div[3]/input</value>
      <webElementGuid>bca8489d-b438-49c2-b48c-fe191c6ad164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div[3]/div[2]/div[3]/input</value>
      <webElementGuid>4a2ae14e-1748-49b9-859f-f00c69a92be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lf_Global_HomeEquityUpfrontCosts' and @name = 'Global_HomeEquityUpfrontCosts' and @type = 'text']</value>
      <webElementGuid>421a15dd-c8ef-4ae1-be9a-c64dadeba65f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
