<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Interest rate_1</name>
   <tag></tag>
   <elementGuidId>c131d856-34e9-44b9-813a-39d2fdd2aa84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_Global_AutoInterestRate-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='lf_Global_AutoInterestRate-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#lf_Global_AutoInterestRate-label</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>eafad461-ccba-4a60-bd25-a1456e6c1b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>lf_Global_AutoInterestRate</value>
      <webElementGuid>bc328088-f61b-48b7-b2fe-0433d9d54700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Global_AutoInterestRate-label</value>
      <webElementGuid>10933e5b-b180-4e10-ae0d-4de140f5f737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Interest rate </value>
      <webElementGuid>abe388b8-9b32-4002-80a8-103806576074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Global_AutoInterestRate-label&quot;)</value>
      <webElementGuid>3f3be3b3-7103-45ff-9390-66bb95593270</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='lf_Global_AutoInterestRate-label']</value>
      <webElementGuid>be170e44-dd35-4986-81e7-dd797c1e132d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Global_AutoInterestRate-table']/div/label</value>
      <webElementGuid>eb8fe8c2-65aa-4b95-86fa-b8d15a7879c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle Loan'])[2]/following::label[1]</value>
      <webElementGuid>cd85ca0c-b58d-4dc4-9fbe-963feca2270a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upfront costs'])[2]/following::label[1]</value>
      <webElementGuid>4cf273a9-f6d9-4a59-ac3e-531cae9340ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between 0.00% and 50.00%'])[2]/preceding::label[1]</value>
      <webElementGuid>d9b59569-3176-484a-81c4-ab4e7f6748db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interest rate'])[4]/preceding::label[1]</value>
      <webElementGuid>b496ebad-d8ce-4fe6-a077-53e3f419d689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div[3]/div/div/label</value>
      <webElementGuid>04207db6-e9ac-482b-8886-68240c3caf6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'lf_Global_AutoInterestRate-label' and (text() = 'Interest rate ' or . = 'Interest rate ')]</value>
      <webElementGuid>6df645df-7f3e-4e87-b528-cb6c4b92d63a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
