<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cumulative interest</name>
   <tag></tag>
   <elementGuidId>5c4b33c6-28c1-4730-8c97-1b3a88c3b4d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#col-6 > span.lf-table-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='col-6']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Cumulative interest&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8ecaf057-2416-4a39-b4a1-6f5a8e55cbd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-table-header</value>
      <webElementGuid>58853703-f30c-4abc-9696-701ca4415c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cumulative interest</value>
      <webElementGuid>e6de5890-8c04-4971-b116-88bf22718d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;col-6&quot;)/span[@class=&quot;lf-table-header&quot;]</value>
      <webElementGuid>ee687337-25cc-48c3-9d51-f6a0633a1172</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='col-6']/span</value>
      <webElementGuid>e519b3a3-c632-445f-b458-5b02b5db98f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interest paid'])[1]/following::span[1]</value>
      <webElementGuid>c50585e6-a48e-448d-9e5f-0016943777df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Principal paid'])[1]/following::span[2]</value>
      <webElementGuid>49569de3-5f70-4da9-a582-c326a3d5ce26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$875'])[2]/preceding::span[1]</value>
      <webElementGuid>9cebf0f5-98c5-4f3b-8fdd-35561a95c9f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$37,283'])[1]/preceding::span[1]</value>
      <webElementGuid>2b23b11b-48b1-4b4c-a1b7-466ad8678fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cumulative interest']/parent::*</value>
      <webElementGuid>ca86e893-d67f-4fb0-88bf-c6434f27a00d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[6]/span</value>
      <webElementGuid>485aa8f5-0705-4181-9109-0e57e20ae713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Cumulative interest' or . = 'Cumulative interest')]</value>
      <webElementGuid>292bd940-5e7b-467d-abba-c4a4c124a151</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
