<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SEE TABLE</name>
   <tag></tag>
   <elementGuidId>8d361264-a7f9-441b-b7c7-d37a9c0ec9e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.lf-open-table-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='lf_tables_links0']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;See Payment Schedule - Home Equity Loan table&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1e59c458-1847-4e30-899f-8555fd1d72d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8a8e3e6d-8967-4ca3-bfe4-3a3ffb687bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-open-table-label</value>
      <webElementGuid>d2ad38de-bb90-45d3-b835-121e90f9c864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEE TABLE</value>
      <webElementGuid>7038ce4a-40ad-4874-8bc9-1f5258016585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_tables_links0&quot;)/span[@class=&quot;lf-open-table-label&quot;]</value>
      <webElementGuid>5becc376-c214-44ab-b688-ad5b348648d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='lf_tables_links0']/span</value>
      <webElementGuid>c9f2826c-31ea-4fe4-93e7-49c86015796a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Schedule - Home Equity Loan'])[1]/following::span[1]</value>
      <webElementGuid>e6324435-c49d-4f92-91c2-bb96ff956330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End of interactive chart.'])[2]/following::span[2]</value>
      <webElementGuid>5acc5d20-3381-4a98-96cf-d1283d35b7ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Schedule - Vehicle Loan'])[1]/preceding::span[1]</value>
      <webElementGuid>46d84644-56ab-4b25-bd24-474e65a2fe6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change views between Cost Difference graph, Payments graph, and Amortization tables'])[1]/preceding::span[3]</value>
      <webElementGuid>6214bc54-ecb3-4c8c-a0ed-653bbe13a1e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SEE TABLE']/parent::*</value>
      <webElementGuid>f4704870-cde0-4ec9-93b5-26a80b11cf1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/button/span</value>
      <webElementGuid>f76e6b55-a544-4905-9203-803a64b4fec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'SEE TABLE' or . = 'SEE TABLE')]</value>
      <webElementGuid>92416e98-ed76-4093-a407-ac05e6228033</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
