<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_The Lease option will cost you 2,816 l_3e03f2</name>
   <tag></tag>
   <elementGuidId>89796146-207c-44f3-8a1d-628b69350891</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_answer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='lf_answer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#lf_answer</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5ef785db-4048-4165-b8c2-442d28894d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_answer</value>
      <webElementGuid>5d6fc3f7-5807-40e7-8ec2-5fc6c6bc0c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The Lease option will cost you $2,816 less on average each year.</value>
      <webElementGuid>59eca5fc-c228-4308-b6a6-a3fda6692f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_answer&quot;)</value>
      <webElementGuid>0e077111-50fa-4ec2-9b86-b40671ba40e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='lf_answer']</value>
      <webElementGuid>9a6eccae-436c-4427-86e1-877ad230c47b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_main']/div/div[3]/div[3]/div/div[3]/h2/span</value>
      <webElementGuid>1ffb16c2-eb22-4397-b67d-5782b68ebcb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$2,816 less'])[1]/following::span[1]</value>
      <webElementGuid>94a27bdb-d9a4-4149-a423-2e2f1ebf970a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lease'])[1]/following::span[2]</value>
      <webElementGuid>1a080468-2986-494f-b1a5-1c21d399f035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/span</value>
      <webElementGuid>367ae90c-1026-4233-a8d0-b95a9129baeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'lf_answer' and (text() = 'The Lease option will cost you $2,816 less on average each year.' or . = 'The Lease option will cost you $2,816 less on average each year.')]</value>
      <webElementGuid>85ed5883-ba26-4244-8964-7ee47a2b2f04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
