<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Purchase</name>
   <tag></tag>
   <elementGuidId>27e084ce-69ff-4086-9d25-b633f1260360</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'lf-legend-item-1' and (text() = 'Purchase' or . = 'Purchase')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//text[@id = 'lf-legend-item-1' and (text() = 'Purchase' or . = 'Purchase')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lf-legend-item-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Interactive chart&quot;i >> internal:text=&quot;Purchase&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ab4e873d-fbe7-40cf-8e8a-b8ebef7bcace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>0e7fef79-7a83-4abb-87f0-f6eb1ca6d928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>c8e7e1e6-8e68-4a37-977c-b9f063e8504f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text-anchor</name>
      <type>Main</type>
      <value>start</value>
      <webElementGuid>814f0b31-0428-44f9-8721-bf7047bc80e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>ea4341f0-16b2-4000-b143-c5a5a6164017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf-legend-item-1</value>
      <webElementGuid>b0d879bb-088c-475c-94d3-8ef988f05a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Purchase</value>
      <webElementGuid>707d201d-2aeb-41c5-b5c8-a5ee97637eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf-legend-item-1&quot;)</value>
      <webElementGuid>972a2f7d-1830-44d8-8442-0890e35d3db3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//text[@id = 'lf-legend-item-1' and (text() = 'Purchase' or . = 'Purchase')]</value>
      <webElementGuid>be3b3495-07f9-4f02-bf5f-8a58fd430410</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
