<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_8,204</name>
   <tag></tag>
   <elementGuidId>8af3e94a-6aa4-459c-858b-f8893463b683</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_AveCostPerYr2Auto03_result_value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='lf_AveCostPerYr2Auto03_result_value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;$8,204&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>46c141dd-3580-41b3-b33d-7dc0267ff90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_AveCostPerYr2Auto03_result_value</value>
      <webElementGuid>0d1711db-4aae-46a7-9ad5-d4e7248d4db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableCellADA </value>
      <webElementGuid>6ebad556-ede3-4b01-b5a0-8c118961768d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$8,204
                                        </value>
      <webElementGuid>5769c07d-26a6-4204-8f05-d5e86bcddd64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_AveCostPerYr2Auto03_result_value&quot;)</value>
      <webElementGuid>129a05df-016b-4f09-b47e-dd82b378a5a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='lf_AveCostPerYr2Auto03_result_value']</value>
      <webElementGuid>96a24ff6-10e7-44c2-8ed4-7ad102a4cf70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='lf_AveCostPerYrAuto03_results']/td[2]</value>
      <webElementGuid>ef773f8a-b075-4b7a-a916-1c775a023570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$16,347'])[1]/following::td[1]</value>
      <webElementGuid>9a439388-b00d-4317-a36f-ed44489eee8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Average cost per year'])[1]/following::td[2]</value>
      <webElementGuid>12d2f156-f591-487c-a3cc-2c99db76b9ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly payment'])[1]/preceding::td[1]</value>
      <webElementGuid>8f0c3f44-930a-47a4-acc0-09fe469bca43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>58036944-40cf-4c41-8d85-760f41008ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'lf_AveCostPerYr2Auto03_result_value' and (text() = '$8,204
                                        ' or . = '$8,204
                                        ')]</value>
      <webElementGuid>cf0eafb8-9fd9-4eec-8480-8b731e1ae47b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
