<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Taxes  Depreciation</name>
   <tag></tag>
   <elementGuidId>eb1cc201-227a-4ea4-82ea-846a95582609</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TaxesDepreciation-accordion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='TaxesDepreciation-accordion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Taxes &amp; Depreciation category, Click to show details,&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c205a6b2-ae04-4c6c-b5e7-03e47cb906bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>10e1b904-7f3f-400c-824f-4480f5533d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e4fc0908-f70f-4f8c-9797-be14bba933ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TaxesDepreciation-accordion</value>
      <webElementGuid>33c3ec44-178e-4602-b7e6-2889d4533d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>lf-panel-TaxesDepreciation</value>
      <webElementGuid>0bf914c0-1158-4de2-b76c-f6b8ca83c80a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-accordion-label</value>
      <webElementGuid>052662e1-d031-4ae2-a20f-8e06c94a84f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>f4e8efb6-112f-4fa6-abd1-68a19e21a4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Taxes &amp; Depreciation category, Click to show details,</value>
      <webElementGuid>318ccd17-13d4-45da-9bb2-8a654d4ad4bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fdeb025b-957f-4de3-a106-00ea8ddf9c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Taxes &amp; Depreciation</value>
      <webElementGuid>f29e9f36-e7c2-4497-b124-12f9d467f724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TaxesDepreciation-accordion&quot;)</value>
      <webElementGuid>5cb3f994-c3bb-49b3-978f-bc2675e86272</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='TaxesDepreciation-accordion']</value>
      <webElementGuid>e4b7e6e7-098f-429f-9212-fb78f580e317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='lf-tab-TaxesDepreciation']/div/h3/a</value>
      <webElementGuid>a9086a8c-78a8-4c4f-b59d-31955d2315f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Taxes &amp; Depreciation')]</value>
      <webElementGuid>fa7458ae-4823-4c5a-8254-6bb5209450a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yearly registration'])[4]/following::a[1]</value>
      <webElementGuid>86cc86a7-c62b-453a-9192-a513b523d2f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between $0 and $10,000'])[6]/following::a[1]</value>
      <webElementGuid>7312b81c-f1fb-4b39-93fc-505679bf66f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(years)'])[1]/preceding::a[1]</value>
      <webElementGuid>2abffa05-6f27-4aa4-9ed0-48e39ff41f38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Taxes &amp; Depreciation']/parent::*</value>
      <webElementGuid>2ce0e5e8-0b87-4ea9-9970-34765d16e91f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[4]</value>
      <webElementGuid>eff6579d-1d81-48d8-8c04-06a15a3fcf93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/div/h3/a</value>
      <webElementGuid>c4e3a291-49f3-414d-8703-bfd0f36d02f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'TaxesDepreciation-accordion' and @href = 'javascript:void(0)' and (text() = 'Taxes &amp; Depreciation' or . = 'Taxes &amp; Depreciation')]</value>
      <webElementGuid>4f9cc643-079b-41c7-baa8-3401b1450e5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
