<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Must be between 0.00 and 100.00_Globa_c7d20a</name>
   <tag></tag>
   <elementGuidId>890e281c-5d90-4594-832a-a21199da3ba9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_Global_SavingsInterestRate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lf_Global_SavingsInterestRate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Your savings interest rate, as a percent&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d58d9a4-63b5-4a3f-8a07-42381d5f240d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Global_SavingsInterestRate</value>
      <webElementGuid>47fcca40-33b3-4ef4-9e2a-a2568376f8ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Global_SavingsInterestRate</value>
      <webElementGuid>49b4a313-d239-44a3-a743-659922c037c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-input-comma</value>
      <webElementGuid>50a85a82-900b-4c45-8263-31adc82d9384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bd4d4e08-162d-46e7-9fc3-4db9057a5209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1.00</value>
      <webElementGuid>e12a83c1-ef7a-4676-a6af-864c5391bba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>786e5d07-8ce5-4afe-a060-9d0dc923aa8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Your savings interest rate, as a percent</value>
      <webElementGuid>218e99e2-016f-4b99-9b78-4958c87a9da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fcfa822d-e8bf-4932-9b32-ee7e0f035963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Global_SavingsInterestRate&quot;)</value>
      <webElementGuid>218caad5-bc41-4663-ae06-1ad2856cfd6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lf_Global_SavingsInterestRate']</value>
      <webElementGuid>ce1c0c0d-72d7-4aaa-a9ef-b483cca9b79b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Global_SavingsInterestRate-table']/div[3]/input</value>
      <webElementGuid>710166bf-2b33-4330-908b-36017389747e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/input</value>
      <webElementGuid>3a799af4-4d65-451d-8740-ff028c31d3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lf_Global_SavingsInterestRate' and @name = 'Global_SavingsInterestRate' and @type = 'text']</value>
      <webElementGuid>d903281b-b415-4c8c-aa32-70d79adf85a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
