<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Keeping a vehicle longer will save you_6d9a6c</name>
   <tag></tag>
   <elementGuidId>aec1c387-df3a-4f87-b8f3-2d9d6e2fc53c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_answer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='lf_answer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#lf_answer</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a2653bb5-4c9c-4114-add3-4183ee9c5479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_answer</value>
      <webElementGuid>241249f1-8cdc-4658-957a-730837c2cc06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keeping a vehicle longer will save you $16,697 in today's dollars</value>
      <webElementGuid>067e38f3-01d4-4d72-b962-a81dec7fc466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_answer&quot;)</value>
      <webElementGuid>33905863-c0d3-46e4-b4e1-700ad2b6de99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='lf_answer']</value>
      <webElementGuid>af8a9213-7037-4ea7-a5a0-bffea9cd9a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_main']/div/div[3]/div[3]/div/div[3]/h2/span</value>
      <webElementGuid>ace38a8e-0b52-484c-b94c-332adcd21c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$16,697'])[1]/following::span[1]</value>
      <webElementGuid>d1871856-97f4-4fb0-9210-9448532872f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='save'])[1]/following::span[2]</value>
      <webElementGuid>ced7aa9c-ef3a-467a-97f8-6bb4b72a4562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/span</value>
      <webElementGuid>af7354a8-29bd-4487-b452-49f010c51962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'lf_answer' and (text() = concat(&quot;Keeping a vehicle longer will save you $16,697 in today&quot; , &quot;'&quot; , &quot;s dollars&quot;) or . = concat(&quot;Keeping a vehicle longer will save you $16,697 in today&quot; , &quot;'&quot; , &quot;s dollars&quot;))]</value>
      <webElementGuid>5de63776-bbd8-499b-9543-db812d3af18c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
