<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_i_1_2_3</name>
   <tag></tag>
   <elementGuidId>ea895c26-7c61-4b22-b52d-5322f2fc3b1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_Auto_LeaseTerm_tooltip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lf_Auto_LeaseTerm_tooltip']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Show tooltip for Lease term&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bebb1349-fe44-474d-bf26-594a07ac7069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>59f556c7-ae7b-4b1d-aa16-4bfe961f9c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#term</value>
      <webElementGuid>0dfc1c69-e249-4416-88fd-a5827f9b5a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Auto_LeaseTerm_tooltip</value>
      <webElementGuid>6bcab7c7-ac28-4ae9-82fa-c17d30ad6de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-show-tooltip</value>
      <webElementGuid>9de3dc7b-899b-49ff-bd0b-589a547bc1dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Show tooltip for Lease term</value>
      <webElementGuid>b38d0a71-c050-4682-a365-d14f7115760b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5bb43e81-1024-42f8-a018-f0b5825b3dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3cdb7fc9-dc47-4182-8f81-2587d4c2648c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Auto_LeaseTerm_tooltip&quot;)</value>
      <webElementGuid>9e5d8935-51bc-490d-b321-51bdbb4636ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lf_Auto_LeaseTerm_tooltip']</value>
      <webElementGuid>42178c12-6e63-495a-8caa-ccf4189fb168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Auto_LeaseTerm-table']/div/a</value>
      <webElementGuid>850c5ff8-b78d-4b9f-a8d3-dec336dce94f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(months)'])[2]/following::a[1]</value>
      <webElementGuid>4be9c162-f5b3-49f6-b6c6-3afe5a1eeff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between 1 and 360 months'])[2]/preceding::a[1]</value>
      <webElementGuid>a44d95d1-2ca4-4f49-a219-6d0ac54cb986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lease term'])[1]/preceding::a[1]</value>
      <webElementGuid>c7d47cb6-6833-4ae1-87ff-88fe528bdb4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#term')])[2]</value>
      <webElementGuid>e04e2fcf-b348-4d35-a900-902d87387929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div[3]/div[3]/div/a</value>
      <webElementGuid>b7a690fa-98f7-4fe4-9d30-6e00b8487d11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#term' and @id = 'lf_Auto_LeaseTerm_tooltip' and (text() = 'i' or . = 'i')]</value>
      <webElementGuid>982aa9c3-9051-4c85-82b6-abe95c05be3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
