<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_i_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>da04cdc9-4d06-4b05-a5e5-203977bc4469</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_Auto_LeaseCashRebate_tooltip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lf_Auto_LeaseCashRebate_tooltip']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Show tooltip for Cash rebate&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>da958956-3458-4e69-a51b-705ad6b767cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6bd3fae2-878b-449e-800b-4667000cb43a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#cashrebate</value>
      <webElementGuid>afe23e96-eb20-44fb-8702-03d5ec560a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Auto_LeaseCashRebate_tooltip</value>
      <webElementGuid>206bc8dc-9ceb-46f5-bd92-ea0ad7580479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-show-tooltip</value>
      <webElementGuid>211cba43-6cb5-4b57-b2d4-94bd309823ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Show tooltip for Cash rebate</value>
      <webElementGuid>524dd484-f1e9-40ec-92fb-c6833efc03b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2b76eb68-e0d6-4df2-ab32-dcf5611fbe69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>664620b6-eb16-49d5-9ec8-9df398a05409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Auto_LeaseCashRebate_tooltip&quot;)</value>
      <webElementGuid>c5673c9f-48d3-4064-9167-8d07b0f599a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lf_Auto_LeaseCashRebate_tooltip']</value>
      <webElementGuid>b13c3fce-8b87-4dd7-82f9-0b0602528979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Auto_LeaseCashRebate-table']/div/a</value>
      <webElementGuid>b3136a14-ea51-4736-b3ad-8a56a3cdb7a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash rebate'])[3]/following::a[1]</value>
      <webElementGuid>023ce3c0-d682-404d-bb6c-68b53d612e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Security deposit'])[2]/following::a[1]</value>
      <webElementGuid>7cb2b079-6d76-4467-ad7e-b0bf7aea09d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between $0 and $100,000'])[4]/preceding::a[1]</value>
      <webElementGuid>4221cc6c-b424-45cf-969e-0789632540ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash rebate'])[4]/preceding::a[1]</value>
      <webElementGuid>d2b22e27-b137-43ad-8bd4-61925f6d081f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#cashrebate')])[2]</value>
      <webElementGuid>f7d9c251-941d-42c3-922b-1d889c62bd0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/a</value>
      <webElementGuid>6d75e298-783a-4cf3-a481-c3eb6698570c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#cashrebate' and @id = 'lf_Auto_LeaseCashRebate_tooltip' and (text() = 'i' or . = 'i')]</value>
      <webElementGuid>eeeb68c0-5b7d-4734-ae0a-07596961b419</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
