<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Your average yearly cost of owning a vehi_3a3bce</name>
   <tag></tag>
   <elementGuidId>de5df0f9-905f-4239-893a-96c778b9596e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_help_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='lf_help_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Your average yearly cost of owning a vehicle declines sharply after the first fe&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>0f27c6c4-2b38-451c-a797-37bc5545009d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_help_2</value>
      <webElementGuid>5194537c-00e6-43d7-bbc9-c42239c017f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your average yearly cost of owning a vehicle declines sharply after the first few years. This is due to smaller depreciation and financing expenses.</value>
      <webElementGuid>9bfca4a9-83d4-4512-b4df-21c6ebb35edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_help_2&quot;)</value>
      <webElementGuid>2d09ab22-f0ca-4285-9638-34274cb585b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='lf_help_2']</value>
      <webElementGuid>6e0de26c-508e-4871-bf88-d9f519715298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='lf-help-content']/p[3]</value>
      <webElementGuid>c14c7cc7-599d-4931-a244-2c3fb9f0ccb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[4]/following::p[4]</value>
      <webElementGuid>78fff8b7-6cff-4ae9-adde-1c02aeca4d07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[3]/following::p[4]</value>
      <webElementGuid>d16693b0-127c-4c4f-b0bb-b2192eaac21b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End of help content'])[1]/preceding::p[2]</value>
      <webElementGuid>e3b6da51-c386-4a69-b6bc-11b096a32e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[5]/preceding::p[2]</value>
      <webElementGuid>ec365796-4204-484f-9322-f6c5af8da8c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your average yearly cost of owning a vehicle declines sharply after the first few years. This is due to smaller depreciation and financing expenses.']/parent::*</value>
      <webElementGuid>c5021f95-5d92-4ede-a92d-a09fe919d75f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]</value>
      <webElementGuid>1999578c-c53c-4dd2-9094-b9f11da87c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'lf_help_2' and (text() = 'Your average yearly cost of owning a vehicle declines sharply after the first few years. This is due to smaller depreciation and financing expenses.' or . = 'Your average yearly cost of owning a vehicle declines sharply after the first few years. This is due to smaller depreciation and financing expenses.')]</value>
      <webElementGuid>243717ef-ac91-406f-a271-0fee93e94720</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
