<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_1,163</name>
   <tag></tag>
   <elementGuidId>9f553317-4b2f-4411-8731-069d66c22415</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='lf_TotIntPaid2Auto01_result_value']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lf_TotIntPaid2Auto01_result_value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;$1,163&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>4c0edd25-c914-4933-af8b-8b2fab572f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_TotIntPaid2Auto01_result_value</value>
      <webElementGuid>e6ab6a08-333e-433e-9b83-26df6ae38545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableCellADA </value>
      <webElementGuid>861e2dc7-877f-4833-9a5a-c58d4608d9f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$1,163
                                        </value>
      <webElementGuid>a94e78ab-38dc-4ffa-9fbe-efcf98ab2b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_TotIntPaid2Auto01_result_value&quot;)</value>
      <webElementGuid>3e195f6d-e0ef-4ba1-8fab-1ac1404160f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='lf_TotIntPaid2Auto01_result_value']</value>
      <webElementGuid>42e9ef52-265d-4ef3-9816-0da8be5b357d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='lf_TotIntPaidAuto01_results']/td[2]</value>
      <webElementGuid>76b31311-8829-4a82-8607-575130e172f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$4,005'])[1]/following::td[1]</value>
      <webElementGuid>0a4ca90a-633c-4f6b-b64c-6e8b088720f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total interest paid'])[1]/following::td[2]</value>
      <webElementGuid>de33c35b-0140-4b1f-8306-1dba0ba2947e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total depreciation'])[1]/preceding::td[1]</value>
      <webElementGuid>5b826e44-eed2-4ec6-8d8f-f4177017bed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]</value>
      <webElementGuid>bba3f48d-fc61-4994-98f0-33eb08b11c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'lf_TotIntPaid2Auto01_result_value' and (text() = '$1,163
                                        ' or . = '$1,163
                                        ')]</value>
      <webElementGuid>6f207779-93a1-4119-846f-4b73275f8efb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
