<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Which is better a rebate or special deal_5b50e9</name>
   <tag></tag>
   <elementGuidId>044155c8-b8f6-44a6-81c8-f689f62d631d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_title_label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='lf_title_label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Which is better: a rebate or special dealer financing?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>1601b38d-2340-47f7-80b6-07eac85de223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_title_label</value>
      <webElementGuid>fa26135e-ad38-4e15-a3de-689929edf640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b8aafe28-6746-418c-b8fa-bf8dab510101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Which is better: a rebate or special dealer financing?</value>
      <webElementGuid>0c38f49e-9d4a-43d8-bb10-792b53444054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Which is better: a rebate or special dealer financing?</value>
      <webElementGuid>c15d0ed2-2907-481b-90fa-9ad3dd401b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_title_label&quot;)</value>
      <webElementGuid>30399085-a6d7-4171-9a11-01dec2a579d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='lf_title_label']</value>
      <webElementGuid>a4b295f3-f65d-4ec1-91ac-813a19ef18f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_main']/div/div/h1</value>
      <webElementGuid>6a629512-c5b7-4517-b79e-992ee62a8cd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/preceding::h1[1]</value>
      <webElementGuid>d15d568a-e3fe-4493-a476-999e6e8b730a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In this tool, the results display before the inputs.'])[1]/preceding::h1[1]</value>
      <webElementGuid>e0e2272d-6c36-4e51-8b49-2dce498eec43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Which is better: a rebate or special dealer financing?']/parent::*</value>
      <webElementGuid>bdc9acd1-77fe-4415-a354-ffba7c1eab49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>8c608cf2-ca0e-4b01-920f-91658597e644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'lf_title_label' and (text() = 'Which is better: a rebate or special dealer financing?' or . = 'Which is better: a rebate or special dealer financing?')]</value>
      <webElementGuid>aa40f90d-e912-42d8-bb63-0dfc968e1ca9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
