<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Used Vehicle Cost</name>
   <tag></tag>
   <elementGuidId>5a8982eb-9b04-47bd-aa8a-7faedd9b0255</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UsedVehicleCost-accordion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='UsedVehicleCost-accordion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2cc19052-a776-411b-bf5c-2d344480f831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>259a9cdb-d07f-4738-8ca7-ec43e412b3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>436f74d8-fcb0-4b1d-8441-e1333c2aa322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UsedVehicleCost-accordion</value>
      <webElementGuid>73bb62b8-ee9f-44fb-bd5c-a71646a29974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>lf-panel-UsedVehicleCost</value>
      <webElementGuid>e6785ec4-7a71-4b47-a324-62d7001e42d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-accordion-label</value>
      <webElementGuid>73527fca-6553-4571-a6f0-c76ce573fd8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>0fd4f2a4-1706-4e61-8150-3343a95b5ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Used Vehicle Cost category, Click to show details,</value>
      <webElementGuid>e3f2b3bb-d6a2-4e33-a1f4-3e2076898526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Used Vehicle Cost</value>
      <webElementGuid>c853b301-19ae-4cbc-87f3-bfeaed823c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UsedVehicleCost-accordion&quot;)</value>
      <webElementGuid>770d605d-de4f-4129-b429-8574713ded94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='UsedVehicleCost-accordion']</value>
      <webElementGuid>365f8d2f-e658-47a6-a948-fcf54ef3671a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='lf-tab-UsedVehicleCost']/div/h3/a</value>
      <webElementGuid>88e3cf0b-218a-40b0-8b20-b65866bc2e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Used Vehicle Cost')]</value>
      <webElementGuid>56455a17-e5d5-41d6-a7c5-01ec893df551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loan term'])[2]/following::a[1]</value>
      <webElementGuid>9922a894-a21c-4c42-a7b8-d9fbc82b0184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between 1 and 360'])[2]/following::a[1]</value>
      <webElementGuid>5232a238-c529-42f4-9bfa-1076e4e2c10e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(years)'])[1]/preceding::a[1]</value>
      <webElementGuid>509b9a1e-c333-419c-904b-20e7f6c95471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Used Vehicle Cost']/parent::*</value>
      <webElementGuid>42b44767-09cf-4fcd-ab55-123fc268fce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[4]</value>
      <webElementGuid>49a055d8-8e3f-4d7a-84ca-89fbc37af1a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/div/h3/a</value>
      <webElementGuid>c2d8983f-01f5-428f-99bb-1f86154d1503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'UsedVehicleCost-accordion' and @href = 'javascript:void(0)' and (text() = 'Used Vehicle Cost' or . = 'Used Vehicle Cost')]</value>
      <webElementGuid>7ada794f-ff75-4b88-8372-a8b0da08e31d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
