<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Used Vehicle Loan</name>
   <tag></tag>
   <elementGuidId>e3d4b36a-138c-4777-b84e-e287d6f2dbcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UsedVehicleLoan-accordion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='UsedVehicleLoan-accordion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>28e9f7d4-9468-4541-83e7-371ddd91cca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6d14c71d-489b-45b4-a3ba-2f4af878c49d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>732918bc-c7e9-4e53-b072-9173826b498f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UsedVehicleLoan-accordion</value>
      <webElementGuid>9eabe922-fdc4-4536-a117-feef71fa910f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>lf-panel-UsedVehicleLoan</value>
      <webElementGuid>4b09e604-e849-43a3-b7e4-3785ffcbb673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-accordion-label</value>
      <webElementGuid>de72c02f-0169-406f-a209-45e64f2d9aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>28662373-7c00-4532-99fa-bb64ac62c611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Used Vehicle Loan category, Click to show details,</value>
      <webElementGuid>367e3c12-06d6-4d8a-894a-520ac3545b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Used Vehicle Loan</value>
      <webElementGuid>4988492b-f9af-4b80-8302-04145da5e766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UsedVehicleLoan-accordion&quot;)</value>
      <webElementGuid>3a13271c-70cb-44c8-b103-6d93e0507aa4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='UsedVehicleLoan-accordion']</value>
      <webElementGuid>17e9bcb5-11bd-43f8-a4d1-2a56e3800fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='lf-tab-UsedVehicleLoan']/div/h3/a</value>
      <webElementGuid>d3266849-7f11-4d19-901e-375403e1c3ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Used Vehicle Loan')]</value>
      <webElementGuid>b502058f-0162-4aa9-8a40-3204e3c55832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registration costs'])[2]/following::a[1]</value>
      <webElementGuid>ac3ed42c-9f27-4267-966b-e6cdd353887e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between $0 and $100,000'])[1]/following::a[1]</value>
      <webElementGuid>fffe1128-98ef-482e-b962-309cf79531e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase price'])[3]/preceding::a[1]</value>
      <webElementGuid>c25566e6-5064-4f20-a29f-cc6c31c7ab2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between $0 and $250,000'])[1]/preceding::a[1]</value>
      <webElementGuid>279446c0-1a05-44ae-8986-457e29afd397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Used Vehicle Loan']/parent::*</value>
      <webElementGuid>bb38bc84-fb00-4ba1-968c-dcea4a4c3cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[3]</value>
      <webElementGuid>59d42ebc-4c65-44ac-9a28-8274014e3ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/h3/a</value>
      <webElementGuid>d563964a-d628-4f80-9dab-cbcbc142b61f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'UsedVehicleLoan-accordion' and @href = 'javascript:void(0)' and (text() = 'Used Vehicle Loan' or . = 'Used Vehicle Loan')]</value>
      <webElementGuid>f10d3a2a-13bc-4dd6-9b12-ee79e169daf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
