<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Average Cost</name>
   <tag></tag>
   <elementGuidId>6cd6e109-ce13-4575-a83c-02d49899d06a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.lf-dot-holder.lf-dot-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='lf_graph_tabs_lf_container1']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>60509d02-7496-4192-9028-6b0f4632a9e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-dot-holder lf-dot-label</value>
      <webElementGuid>f6878529-f8e9-410e-8b35-eb273642235e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Average Cost</value>
      <webElementGuid>4ff6ebf3-46b2-4381-9b9a-59d0f702b853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_graph_tabs_lf_container1&quot;)/div[@class=&quot;lf-dot-holder lf-dot-label&quot;]</value>
      <webElementGuid>1494fa8e-7881-45fa-908f-65058fb1a4a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='lf_graph_tabs_lf_container1']/div</value>
      <webElementGuid>4e549101-ed58-4541-ac58-b6e417187ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change views between Average Cost graph, and Payments graph'])[1]/following::div[2]</value>
      <webElementGuid>d0a05ef7-71de-47c2-ac43-8f20bd30f98b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$3,193'])[3]/following::div[5]</value>
      <webElementGuid>3ea039c2-9e31-496b-b368-59d50ad81a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payments'])[1]/preceding::div[1]</value>
      <webElementGuid>c9b0f92c-dff4-4d76-8034-d633afa116a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click Here'])[1]/preceding::div[4]</value>
      <webElementGuid>ced27bf4-a67a-490e-8b70-4731d425bf4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Average Cost']/parent::*</value>
      <webElementGuid>d3ea5d10-245e-4d68-8c04-cb006873e34f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>12852444-c761-414f-96a1-879495dad344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Average Cost' or . = 'Average Cost')]</value>
      <webElementGuid>17a10943-b0eb-4ae3-9a54-790a4edbd2cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
