<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Title</name>
   <tag></tag>
   <elementGuidId>5a786e99-8dea-4514-a87b-99678e151055</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_title_label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='lf_title_label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>65708660-2011-4203-9fb5-703bf2e2f2b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_title_label</value>
      <webElementGuid>457842f0-a353-413d-a30b-f4aa5e6c4f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>95548e94-2c7f-441b-a921-10db159864db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Which is better: a new or used vehicle?</value>
      <webElementGuid>627792a2-7f8a-473d-9e87-0e135224f0b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Which is better: a new or used vehicle?</value>
      <webElementGuid>76dccd18-ec96-4dcb-8593-37df4c9a8281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_title_label&quot;)</value>
      <webElementGuid>63cbdcd9-f967-44f5-864d-1975eae7c565</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='lf_title_label']</value>
      <webElementGuid>b614ed88-2414-483b-aba9-90354bba4ff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_main']/div/div/h1</value>
      <webElementGuid>2a8a696b-163e-4b93-88ae-78e1f6c6371f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/preceding::h1[1]</value>
      <webElementGuid>118e6e59-ad55-4638-b05b-33f6414c7749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In this tool, the results display before the inputs.'])[1]/preceding::h1[1]</value>
      <webElementGuid>d2773b0f-ee06-45f5-b978-2da514b4a477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Which is better: a new or used vehicle?']/parent::*</value>
      <webElementGuid>b5d08e74-5fb6-4de7-98b1-4bb73f63126c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>eccf0ef7-1a99-4c8a-87c3-56968e049874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'lf_title_label' and (text() = 'Which is better: a new or used vehicle?' or . = 'Which is better: a new or used vehicle?')]</value>
      <webElementGuid>74d0ffcf-ec22-4689-8d74-35dbe8cad223</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
