<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Must be between 0 and 30_Auto_UsedVehicleAgeInYears</name>
   <tag></tag>
   <elementGuidId>0ce8cfdb-0ea5-4c12-8095-c992b31d59ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lf_Auto_UsedVehicleAgeInYears']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lf_Auto_UsedVehicleAgeInYears</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fab4de76-32e4-4e5d-827d-de32d202c502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Auto_UsedVehicleAgeInYears</value>
      <webElementGuid>13260d8b-59ee-4f46-8eaf-fbcdafda2851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Auto_UsedVehicleAgeInYears</value>
      <webElementGuid>147850a9-215d-4c75-a759-a8a30e0c6cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-input-comma</value>
      <webElementGuid>41789fe5-becc-434a-bced-bcfe5d210107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c5771e77-f7d3-4edf-a87a-452ee22de82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>76cdc23b-313e-4d98-85fd-e2891905382a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>9a6dc349-61ac-4338-8b19-b1f34daae31b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Vehicle age, years</value>
      <webElementGuid>60e4ab70-66d4-484d-bfca-3bb48e0514b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Auto_UsedVehicleAgeInYears&quot;)</value>
      <webElementGuid>3a70744a-84b1-4627-9cc0-5f1ac734578e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lf_Auto_UsedVehicleAgeInYears']</value>
      <webElementGuid>f95eaabf-cd57-4253-a599-dd54f2e7f2a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Auto_UsedVehicleAgeInYears-table']/div[3]/input</value>
      <webElementGuid>52a7534c-bbd8-4cbd-80d4-db591ad5e70b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/div[3]/div/div[3]/input</value>
      <webElementGuid>5bfd2f5d-ef5a-4284-ad55-7fcca057677c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lf_Auto_UsedVehicleAgeInYears' and @name = 'Auto_UsedVehicleAgeInYears' and @type = 'text']</value>
      <webElementGuid>abe63f94-f7fc-4cab-94c6-bd350c0d6c04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
