<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Must be between 0.00 and 50.00_Auto_UsedVehicleInterestRate</name>
   <tag></tag>
   <elementGuidId>93140ac7-61ac-48b1-95b4-1da870afc21c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lf_Auto_UsedVehicleInterestRate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lf_Auto_UsedVehicleInterestRate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b558f97-f8cd-43d3-b67c-5d531746328a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Auto_UsedVehicleInterestRate</value>
      <webElementGuid>678509d7-3081-47d6-8555-94f750c43bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Auto_UsedVehicleInterestRate</value>
      <webElementGuid>1a55b345-9ccf-4b3e-922c-81a1e9a5c7a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-input-comma</value>
      <webElementGuid>8f5f57ac-0598-46be-a164-d0def6d247bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>309bb141-f3c8-493e-8586-9651df207542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5.500</value>
      <webElementGuid>920fdbe3-8278-447e-9071-1c4ea724c668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>b6d942e8-5533-4618-b73b-09c74bf135ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Interest rate, as a percent</value>
      <webElementGuid>cfa3ee42-01fc-48e2-9bdf-32dacfea4900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Auto_UsedVehicleInterestRate&quot;)</value>
      <webElementGuid>6735b557-a5b1-4c94-956d-e77084f3e7ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lf_Auto_UsedVehicleInterestRate']</value>
      <webElementGuid>a949b40b-88f3-4c28-ae58-c9be87bcd421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Auto_UsedVehicleInterestRate-table']/div[3]/input</value>
      <webElementGuid>83133f76-c950-4e0d-8f28-5da9a1fd8752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div[3]/div[3]/div[3]/input</value>
      <webElementGuid>9754155b-5272-4912-82b8-4b326f793c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lf_Auto_UsedVehicleInterestRate' and @name = 'Auto_UsedVehicleInterestRate' and @type = 'text']</value>
      <webElementGuid>928004c0-dca5-4131-8e81-c22f37e3e939</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
