<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Must be between 1 and 360_Global_Auto_8b1711</name>
   <tag></tag>
   <elementGuidId>c563dcd6-c457-4285-951f-56aabab43c6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lf_Global_AutoLoanTerm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lf_Global_AutoLoanTerm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>468bf506-fcbd-4904-a5ef-6bb19dc1c4ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Global_AutoLoanTerm</value>
      <webElementGuid>b938c1e8-5e87-4f2f-9daa-467f3abaa81d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Global_AutoLoanTerm</value>
      <webElementGuid>22b9d51b-640a-4152-97ca-567604ca5ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-input-comma</value>
      <webElementGuid>adba2f11-5b2a-4a25-ba40-1cb389e54d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a8a2d110-131c-48b8-8f53-3c3c4bb06997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>c958f599-2259-421f-949c-b4619f8c49d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>7c48f982-ed09-4604-a025-2afba88ac8cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Loan term, months</value>
      <webElementGuid>17a62d96-f401-4c6d-a1f5-606f922f58fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Global_AutoLoanTerm&quot;)</value>
      <webElementGuid>cec17354-1c35-491e-a763-ad319717bdd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lf_Global_AutoLoanTerm']</value>
      <webElementGuid>b7b5aacb-256f-40fd-b635-537e66170b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Global_AutoLoanTerm-table']/div[3]/input</value>
      <webElementGuid>2c01af80-f530-4ebf-a9ca-2e8e3fb00674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/input</value>
      <webElementGuid>0421a30e-1e61-43ad-9fd4-6cce2f37440b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lf_Global_AutoLoanTerm' and @name = 'Global_AutoLoanTerm' and @type = 'text']</value>
      <webElementGuid>5fe351e2-bf43-4ac7-a607-a43c074ffa4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
