<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Must be between 1 and 30_Auto_YearsUs_d82219</name>
   <tag></tag>
   <elementGuidId>e6320301-3d1c-4c32-8cd1-9e9682b79d3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lf_Auto_YearsUsedVehicleOwned']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lf_Auto_YearsUsedVehicleOwned</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85b180e6-2d2e-4da8-855b-e555ff37426b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Auto_YearsUsedVehicleOwned</value>
      <webElementGuid>4957f3df-b9ad-4f4c-9e13-427e405d108f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Auto_YearsUsedVehicleOwned</value>
      <webElementGuid>68491238-2bf2-4a2f-85eb-4f150a81529a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-input-comma</value>
      <webElementGuid>8655f389-9c90-470b-9f61-164bf2d2c3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aa9a38e3-a128-48b0-a343-d5e36d5797d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>4d7bd702-459e-420a-8bbb-2f7a5d355d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>91bc0076-1b85-4496-a212-2ced856e17d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Years you will own vehicle</value>
      <webElementGuid>1630e309-5182-4dea-a181-0ccf1bd94d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Auto_YearsUsedVehicleOwned&quot;)</value>
      <webElementGuid>6de14157-5274-4c28-a3bd-cfb61925ceb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lf_Auto_YearsUsedVehicleOwned']</value>
      <webElementGuid>0d354721-0b33-4e10-9b87-2b53b63a9ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Auto_YearsUsedVehicleOwned-table']/div[3]/input</value>
      <webElementGuid>5b1b8739-d711-4c14-a84f-341e2a403d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/div[3]/div[2]/div[3]/input</value>
      <webElementGuid>a0158f86-2ab4-49b6-a5df-1bb8d3b29bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lf_Auto_YearsUsedVehicleOwned' and @name = 'Auto_YearsUsedVehicleOwned' and @type = 'text']</value>
      <webElementGuid>f0e6490b-9365-4a77-8b77-36fc6ed5b070</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
