<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Depreciation. Some vehicles depreciate fa_243f55</name>
   <tag></tag>
   <elementGuidId>5fa4fda5-c272-4e9c-90b6-ee585d5268b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_help_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='lf_help_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b4b5a89a-b7e7-4786-ba53-c7daf8c2109e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_help_2</value>
      <webElementGuid>845b935f-4f73-4391-86a1-c1c8f49d45a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Depreciation. Some vehicles depreciate faster than others do. The slower the depreciation rate of the vehicle, the higher its resale value.</value>
      <webElementGuid>5ee51a07-eb5d-4d4b-aace-7242b8931469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_help_2&quot;)</value>
      <webElementGuid>f3678536-4266-411f-8600-8523aeb1afcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='lf_help_2']</value>
      <webElementGuid>355bda90-5cb9-404b-9bae-dd960da7fa42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='lf-help-content']/p[3]</value>
      <webElementGuid>c59902a3-cf3a-440b-93b9-d03b6309afd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase price.'])[1]/following::p[1]</value>
      <webElementGuid>60f99254-f69e-4071-83a7-8e5341ac0365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[4]/following::p[4]</value>
      <webElementGuid>70708db5-d684-4c55-9d95-8d7d0acead20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operating costs.'])[1]/preceding::p[1]</value>
      <webElementGuid>e2946ef8-fbe9-4ec5-8d2b-6cebdd2d7d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Some vehicles depreciate faster than others do. The slower the depreciation rate of the vehicle, the higher its resale value.']/parent::*</value>
      <webElementGuid>800269c9-2ca7-4df0-9f7d-951b8ad24db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]</value>
      <webElementGuid>e364dff0-1fd7-4a6f-a100-138c46d58abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'lf_help_2' and (text() = 'Depreciation. Some vehicles depreciate faster than others do. The slower the depreciation rate of the vehicle, the higher its resale value.' or . = 'Depreciation. Some vehicles depreciate faster than others do. The slower the depreciation rate of the vehicle, the higher its resale value.')]</value>
      <webElementGuid>3377f4e9-212c-4dbe-aed5-a60886615652</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
