<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Operating costs. A used vehicle is likely_fe087c</name>
   <tag></tag>
   <elementGuidId>2ef52834-3386-4363-a601-d4ab06f300b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_help_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='lf_help_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>34121f44-842e-4d3b-8ff3-2344a35c6632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_help_3</value>
      <webElementGuid>8df4bf44-0735-4700-b127-838ceef0a4c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Operating costs. A used vehicle is likely to require more maintenance and repair than a new one. Also, fuel consumption may be less efficient.</value>
      <webElementGuid>11eb010f-2c18-49c8-abd3-fd24a7363722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_help_3&quot;)</value>
      <webElementGuid>5a5c1c93-4724-4f56-b464-3f295b2448d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='lf_help_3']</value>
      <webElementGuid>29f32b53-3223-4be3-bd5c-e323795d69bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='lf-help-content']/p[4]</value>
      <webElementGuid>0f9773f4-3ad2-434d-9efd-35d0c0cf78bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Depreciation.'])[1]/following::p[1]</value>
      <webElementGuid>84cadcd0-3e95-4f4c-8cfc-a96324ee89d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase price.'])[1]/following::p[2]</value>
      <webElementGuid>ba3555a2-ca8c-482f-ae17-607dcb5036e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Years of ownership.'])[1]/preceding::p[1]</value>
      <webElementGuid>114b1864-8525-4bc5-b39d-fdbaf18e07de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='A used vehicle is likely to require more maintenance and repair than a new one. Also, fuel consumption may be less efficient.']/parent::*</value>
      <webElementGuid>ad49bcc3-2584-4d92-8ad3-6b1785a00e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]</value>
      <webElementGuid>a56521fb-dc48-4c85-95e4-8f40194da1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'lf_help_3' and (text() = 'Operating costs. A used vehicle is likely to require more maintenance and repair than a new one. Also, fuel consumption may be less efficient.' or . = 'Operating costs. A used vehicle is likely to require more maintenance and repair than a new one. Also, fuel consumption may be less efficient.')]</value>
      <webElementGuid>b00f1176-d08d-4434-a01f-d4679d7a6a22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
