<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_976</name>
   <tag></tag>
   <elementGuidId>2cb65f65-69b4-4166-986d-f57bccdf3c12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='lf_MonPmt2Auto01_result_value']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lf_MonPmt2Auto01_result_value > span.lf-nbsp-number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>857425b6-834f-49e8-8b5c-4b25009781b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-nbsp-number</value>
      <webElementGuid>dd3f9eb3-07e1-442e-ae7b-e4e8ccab9844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$976</value>
      <webElementGuid>7e38f53b-9517-4d92-988e-29cb89cfe4a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_MonPmt2Auto01_result_value&quot;)/span[@class=&quot;lf-nbsp-number&quot;]</value>
      <webElementGuid>5c9f9639-51ae-40af-9981-ab3523f38c6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='lf_MonPmt2Auto01_result_value']/span</value>
      <webElementGuid>941ba422-f7e6-44d6-9f53-abc64bd26ed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1,879'])[1]/following::span[1]</value>
      <webElementGuid>8ebd39ef-1c90-409e-bcd4-6c8f6613d606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly payment'])[1]/following::span[2]</value>
      <webElementGuid>c1fdb81f-7fa6-473d-a65e-b42a6323ac30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total interest paid'])[1]/preceding::span[1]</value>
      <webElementGuid>815e236d-8289-4049-8ea5-6a41855e33e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$6,896'])[1]/preceding::span[1]</value>
      <webElementGuid>bc1806c6-8dae-4915-b9b2-4478893e9009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$976']/parent::*</value>
      <webElementGuid>ee6000e0-0f7c-4fab-bc6f-9d14af56ebb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/span</value>
      <webElementGuid>a6086d64-d33f-405b-ad5e-4fc60e854681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '$976' or . = '$976')]</value>
      <webElementGuid>696f38ca-d05c-4c8f-ac7d-efdd13630e0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
