<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_7,735</name>
   <tag></tag>
   <elementGuidId>9523c1d5-e34e-4c0a-b7fd-7a1908e5832c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.lf-nbsp-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='lf_AveCostPerYrAuto01_result_value']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7455097b-cb60-4108-a006-8f7b60c0d26b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-nbsp-number</value>
      <webElementGuid>0a3a94aa-4aa3-4e94-92de-ccec3c38959a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$7,735</value>
      <webElementGuid>ffb17e0c-ebae-4353-bb7a-3599e9245dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_AveCostPerYrAuto01_result_value&quot;)/span[@class=&quot;lf-nbsp-number&quot;]</value>
      <webElementGuid>9bba8137-6875-416f-b320-fb8bed0dc976</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='lf_AveCostPerYrAuto01_result_value']/span</value>
      <webElementGuid>22681c08-9df6-494f-8dc4-0d7e72a6c190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Average cost per year'])[1]/following::span[1]</value>
      <webElementGuid>b9051331-2b42-4030-b424-2cfefb46ab39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Used'])[1]/following::span[1]</value>
      <webElementGuid>ae10b979-984e-47d9-be8c-4165a56f5c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$3,193'])[1]/preceding::span[1]</value>
      <webElementGuid>df320738-abf6-4966-8623-b9c8f564f841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly payment'])[1]/preceding::span[2]</value>
      <webElementGuid>7badea43-8aa6-4bbb-be00-dcb73d5e6981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$7,735']/parent::*</value>
      <webElementGuid>f5ddb8fd-536c-4851-ad92-c9662ae4cb07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span</value>
      <webElementGuid>236ca83e-a63f-4d59-a7e6-f880ffe08fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '$7,735' or . = '$7,735')]</value>
      <webElementGuid>37edc832-fb6c-4235-bdf4-503f66f9d4b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
