<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_The used vehicle will cost you 8,233 l_5a0361</name>
   <tag></tag>
   <elementGuidId>0a69a56a-8ab9-45d2-b7f1-370f2b9a1676</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='lf_answer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lf_answer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b4be5880-8b35-4dcf-8da4-ee58cdf6cb8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_answer</value>
      <webElementGuid>89da650e-7d59-4726-ab99-57dd4c7fa17b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The used vehicle will cost you $8,233 less on average each year</value>
      <webElementGuid>2ef50ef4-243e-4685-9160-1d9ebf6695ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_answer&quot;)</value>
      <webElementGuid>bf29973b-1998-49d9-bd5e-9ae41e3c13b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='lf_answer']</value>
      <webElementGuid>0bbede54-9392-4114-87aa-debd18882658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_main']/div/div[3]/div[3]/div/div[3]/h2/span</value>
      <webElementGuid>d8560310-c2c1-4e8f-8d4e-b2766e16c3ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$8,233 less'])[1]/following::span[1]</value>
      <webElementGuid>6433d833-2b60-4353-89ad-cdfaf1d418fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='used vehicle'])[1]/following::span[2]</value>
      <webElementGuid>f4a2a291-68c2-4941-afd3-dc973a3bc8f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/span</value>
      <webElementGuid>f0683dc9-eef8-474e-b954-376aafc090de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'lf_answer' and (text() = 'The used vehicle will cost you $8,233 less on average each year' or . = 'The used vehicle will cost you $8,233 less on average each year')]</value>
      <webElementGuid>88ad8bfc-dde6-45f9-ad87-ff1e555d7aca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
