<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_3,193_1</name>
   <tag></tag>
   <elementGuidId>c805a1f2-87a8-4fe5-86ea-d54df27bb367</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='highcharts-data-table-0']/tbody/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>1d3dc866-3c8a-4bf8-8320-17ad0da4c1fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>highcharts-number</value>
      <webElementGuid>522717aa-1047-41f1-9520-bfebe2b34b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$3,193</value>
      <webElementGuid>cf48e6e4-399d-4041-a395-bae653f1bc85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-data-table-0&quot;)/tbody[1]/tr[1]/td[@class=&quot;highcharts-number&quot;]</value>
      <webElementGuid>099c828b-c9be-421d-a377-1fad6dbbc241</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='highcharts-data-table-0']/tbody/tr/td[2]</value>
      <webElementGuid>6453e9f0-0779-4984-b92b-8ba08941b3dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$7,735'])[2]/following::td[1]</value>
      <webElementGuid>82980450-5bf5-4bcc-9f20-250c84658b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Average Cost Per Year'])[2]/following::td[2]</value>
      <webElementGuid>34f4a80f-dbc2-4855-b203-23d8fee9725c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change views between Average Cost graph, and Payments graph'])[1]/preceding::td[1]</value>
      <webElementGuid>b5c374a3-3c82-49b5-a7ca-6a0f8c07bb0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Average Cost'])[1]/preceding::td[1]</value>
      <webElementGuid>41488baa-f888-4721-a725-0db15226dc8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[2]</value>
      <webElementGuid>29b0a9dd-f331-4d2e-a8ff-cfd71ad96952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '$3,193' or . = '$3,193')]</value>
      <webElementGuid>b77b1e06-a423-44c6-b689-b677d6c67448</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
