<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Total depreciation</name>
   <tag></tag>
   <elementGuidId>32624d92-e0ed-43ab-a80d-3424067f5580</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_TotDepAuto01_result_label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='lf_TotDepAuto01_result_label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>a17c7ecc-8fef-467d-ad04-baa69aec23f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_TotDepAuto01_result_label</value>
      <webElementGuid>b2d2f3c0-cb91-421b-9f5c-a3cd22af1c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableCellADA</value>
      <webElementGuid>f23a3012-0c2e-464c-bcd3-4e86e3d4a9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>60204705-7bdf-4eca-ab69-2a8524ec2e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Total depreciation
                                        </value>
      <webElementGuid>a3d29ea6-c1b9-49ec-95b5-4f753c6460dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_TotDepAuto01_result_label&quot;)</value>
      <webElementGuid>d4c01f57-5f80-4f19-ba3a-ae53ddbde4b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//th[@id='lf_TotDepAuto01_result_label']</value>
      <webElementGuid>eea3ae22-148f-4055-b3fc-2f0734f54758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='lf_TotDepAuto01_results']/th</value>
      <webElementGuid>8772bdf7-bb14-4645-8f40-da3fd52a1ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1,163'])[1]/following::th[1]</value>
      <webElementGuid>65dbeafd-1f8a-438c-8a4e-99109e390596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$4,005'])[1]/following::th[1]</value>
      <webElementGuid>3cbe3595-c1f7-4bc5-9620-2e8dc71a116d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$20,020'])[1]/preceding::th[1]</value>
      <webElementGuid>a7aeeb76-9330-46f8-b587-363de481c26b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$5,588'])[1]/preceding::th[1]</value>
      <webElementGuid>0854c2a7-6e2f-434b-92dc-ac491be64a7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Total depreciation']/parent::*</value>
      <webElementGuid>0c7ade2e-60cb-4379-aef4-b12bf676d964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/th</value>
      <webElementGuid>353b5936-79a3-4df6-8acc-e06edea57cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[@id = 'lf_TotDepAuto01_result_label' and (text() = '
                                            Total depreciation
                                        ' or . = '
                                            Total depreciation
                                        ')]</value>
      <webElementGuid>5c0c5f4f-c12a-40ed-b2e7-45a9d7a562e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
