<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Which vehicle loan is better</name>
   <tag></tag>
   <elementGuidId>53103618-48a8-4b87-a4db-05ae6807082a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_title_label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='lf_title_label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Which vehicle loan is better?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>2f0aff95-1b5b-4049-b5bb-518540f0e92f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_title_label</value>
      <webElementGuid>7496f321-1a6e-4195-b5ab-9500bdae63a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f4e79b27-c755-41ae-a3c4-aabb37ee2cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Which vehicle loan is better?</value>
      <webElementGuid>b82e7552-1468-43af-8909-e5907f87b5d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Which vehicle loan is better?</value>
      <webElementGuid>55c76b1f-be61-46a7-96c9-84e2318e346c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_title_label&quot;)</value>
      <webElementGuid>db56c2c6-dfe2-4790-9b18-da4e83e257ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='lf_title_label']</value>
      <webElementGuid>93d757eb-4d65-4f63-ae2e-c350db1a45d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_main']/div/div/h1</value>
      <webElementGuid>837eb0e6-4306-4cbd-989f-a36ed42561aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/preceding::h1[1]</value>
      <webElementGuid>406ed810-3f48-4d4d-a35b-45234b305e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In this tool, the results display before the inputs.'])[1]/preceding::h1[1]</value>
      <webElementGuid>9ff493d1-2acf-43cb-9d95-79ebe3016c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Which vehicle loan is better?']/parent::*</value>
      <webElementGuid>799188e8-58a0-4891-9bb2-d0a0938f2ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>4e44d30b-6e81-4399-bfd1-3a500a062ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'lf_title_label' and (text() = 'Which vehicle loan is better?' or . = 'Which vehicle loan is better?')]</value>
      <webElementGuid>62388b48-c78a-4029-a04e-94ee1962a52f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
