<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Must be between 1 and 30_Auto_YearsBe_a86674</name>
   <tag></tag>
   <elementGuidId>35855c1a-0617-47eb-9f7a-1a31ebf52374</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_Auto_YearsBeforeSellingIfSellOften</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lf_Auto_YearsBeforeSellingIfSellOften']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Years before selling&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7057c8af-f49b-4a37-957f-ed678ecef947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Auto_YearsBeforeSellingIfSellOften</value>
      <webElementGuid>528ef527-3842-4c44-9961-c575e9129a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Auto_YearsBeforeSellingIfSellOften</value>
      <webElementGuid>4ce266f3-dae2-4557-919b-b8d9f0999672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-input-comma</value>
      <webElementGuid>7a72acc9-d897-4c74-887a-9e73a139d22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>68d0516e-4643-4210-b800-d02892f3656b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>a3e1a684-b53f-41a0-a737-7f2ef2c779c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7882d7d1-8347-4b5f-ba44-8e6e52903da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Years before selling</value>
      <webElementGuid>47da6646-4ab1-4b11-b9b4-1b2e93dcd4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2d7d2c49-15c5-438a-9065-8b18205fe3cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Auto_YearsBeforeSellingIfSellOften&quot;)</value>
      <webElementGuid>da642881-d595-45f1-98bf-46edc46a2f26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lf_Auto_YearsBeforeSellingIfSellOften']</value>
      <webElementGuid>93047e70-a567-4deb-87e4-cdc4fc8f5186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Auto_YearsBeforeSellingIfSellOften-table']/div[3]/input</value>
      <webElementGuid>d9c1fc62-d993-40f6-9372-6a39b0ce538b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div[3]/div/div[3]/input</value>
      <webElementGuid>f21e6c3b-52fc-42d4-8d98-3ebc0c4b003c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lf_Auto_YearsBeforeSellingIfSellOften' and @name = 'Auto_YearsBeforeSellingIfSellOften' and @type = 'text']</value>
      <webElementGuid>3cd3e15a-5401-4d30-8a17-c71208ecc081</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
