<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Must be between 0.00 and 90.00_Global_609372</name>
   <tag></tag>
   <elementGuidId>f5f808d7-a0b3-413e-89ac-46719f96dabb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_Global_FederalAndStateTaxRate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lf_Global_FederalAndStateTaxRate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Your state &amp; federal tax rate, as a percent&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e7eec15-3886-4dbc-ab94-e0de37c38af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Global_FederalAndStateTaxRate</value>
      <webElementGuid>a1621c9e-daf5-4b2a-b329-4ef781d1c864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Global_FederalAndStateTaxRate</value>
      <webElementGuid>ccb734cf-7adf-4e02-82d4-e1b9bfd6378a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-input-comma</value>
      <webElementGuid>97d75942-3d93-4f0b-83ef-98792d3bb614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bb0125cd-0e58-4f87-8dc1-4cc59f15b513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>33.80</value>
      <webElementGuid>fd8bec16-6d6d-4b55-82d4-2ceeee0f4cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>fe995974-4469-49b2-b2de-078368290372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Your state &amp; federal tax rate, as a percent</value>
      <webElementGuid>47d4257f-45db-47ac-a980-8d57b308c52a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>92c95268-4acc-4d7b-bf8b-2f1db4b20e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Global_FederalAndStateTaxRate&quot;)</value>
      <webElementGuid>dd17406f-a3e4-4d57-9cc2-dd5bdd3859ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lf_Global_FederalAndStateTaxRate']</value>
      <webElementGuid>9c2af660-06df-4777-aeaf-e88f8d6ae98c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Global_FederalAndStateTaxRate-table']/div[3]/input</value>
      <webElementGuid>a2c8cd03-f5c3-42d6-9d54-c7419a6ab5b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/div[3]/div[4]/div[3]/input</value>
      <webElementGuid>aba87ac1-1de0-4e15-a70e-286f278fcec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lf_Global_FederalAndStateTaxRate' and @name = 'Global_FederalAndStateTaxRate' and @type = 'text']</value>
      <webElementGuid>1d4cff9a-99d0-4830-8bce-fc5ec7117755</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
