<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Sales tax rate</name>
   <tag></tag>
   <elementGuidId>29b60781-fc8b-435d-883e-83d25bd65228</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_Global_SalesTaxRate-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='lf_Global_SalesTaxRate-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#lf_Global_SalesTaxRate-label</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>761ca587-8648-4b95-93de-0ebfd91590b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>lf_Global_SalesTaxRate</value>
      <webElementGuid>f13a793c-2a69-4774-a582-ffa32acf5d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Global_SalesTaxRate-label</value>
      <webElementGuid>d68ff8bc-6b19-451b-9155-a44cbe358aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-field-label-no-tooltip</value>
      <webElementGuid>60429b97-07d2-4462-85c7-866be4906384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sales tax rate
                                
                        </value>
      <webElementGuid>f55fe002-86b6-4fe5-b81d-218ecdd566a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Global_SalesTaxRate-label&quot;)</value>
      <webElementGuid>4e86bd98-bddf-4763-bd75-83028960f611</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='lf_Global_SalesTaxRate-label']</value>
      <webElementGuid>4c61df14-10e1-4e84-874f-04b8e45c3d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Global_SalesTaxRate-table']/div/label</value>
      <webElementGuid>1fef143e-1c03-486d-8357-6e5902f0aa04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error message for dropdown list here'])[1]/following::label[1]</value>
      <webElementGuid>a9930b79-e1bb-4be9-95dd-cf545ccf73d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Future depreciation'])[1]/following::label[1]</value>
      <webElementGuid>2e2f6ddf-9429-4991-8768-326e7deba15c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between 0.00% and 99.00%'])[1]/preceding::label[1]</value>
      <webElementGuid>45de15de-7b11-422c-83b4-65c2f8ec53e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales tax rate'])[2]/preceding::label[1]</value>
      <webElementGuid>57b7a94e-0cf3-47a1-83fc-9eb7fbaef115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sales tax rate']/parent::*</value>
      <webElementGuid>52d4975f-d745-420b-b47e-e591990fd662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/div[3]/div[3]/div/label</value>
      <webElementGuid>da67178f-d2aa-41d8-a78b-342bf964c986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'lf_Global_SalesTaxRate-label' and (text() = 'Sales tax rate
                                
                        ' or . = 'Sales tax rate
                                
                        ')]</value>
      <webElementGuid>1a12f100-1964-4581-a27d-1e694eaae13f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
