<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_If new cars are bought, the biggest depre_174e02</name>
   <tag></tag>
   <elementGuidId>6f205add-89fa-403c-a1a4-a3750d33f4b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_help_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='lf_help_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;If new cars are bought, the biggest depreciation occurs in the first year of own&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>16f5e9d4-085e-4b23-9c78-9578be5f255b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_help_3</value>
      <webElementGuid>9f8a3777-95e2-469c-942e-989dcd788f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>If new cars are bought, the biggest depreciation occurs in the first year of ownership.</value>
      <webElementGuid>cc2ce60b-0c35-496f-b69f-3791c22ca6d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_help_3&quot;)</value>
      <webElementGuid>01d689ba-0f55-422a-bab5-d2b0e7a0b994</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='lf_help_3']</value>
      <webElementGuid>d202cdf1-b727-4a31-82ef-7cb5ddf33bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='lf-help-content']/p[4]</value>
      <webElementGuid>7ba03d95-2544-4cb1-b489-1e5e72552102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[4]/following::p[5]</value>
      <webElementGuid>d321e9b7-e15c-421c-b06e-3ffc3e7a8ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[3]/following::p[5]</value>
      <webElementGuid>f7178b4d-1aeb-46a0-bbde-207e312136fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End of help content'])[1]/preceding::p[5]</value>
      <webElementGuid>dcb32f8b-c5e4-4625-9e69-f0f1264f03f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[5]/preceding::p[5]</value>
      <webElementGuid>3faf571b-af68-40e6-b333-2b8c323b5588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='If new cars are bought, the biggest depreciation occurs in the first year of ownership.']/parent::*</value>
      <webElementGuid>3834ddb9-d089-4b1e-aad7-4a1cd8025353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]</value>
      <webElementGuid>26d0f292-c6d5-4b7a-a309-5c600c84880f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'lf_help_3' and (text() = 'If new cars are bought, the biggest depreciation occurs in the first year of ownership.' or . = 'If new cars are bought, the biggest depreciation occurs in the first year of ownership.')]</value>
      <webElementGuid>2bb98bac-43dd-4c46-a679-b3881a4a1121</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
