<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_24,147</name>
   <tag></tag>
   <elementGuidId>05ae7d34-79b3-4614-a334-86e2667acd64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_TotDepAuto10_result_value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='lf_TotDepAuto10_result_value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;$24,147&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f7083006-2384-4895-81cc-eb2835cb1726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_TotDepAuto10_result_value</value>
      <webElementGuid>839d6439-51a6-4c90-8d67-659242f05120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableCellADA </value>
      <webElementGuid>66acd669-2d4c-46ff-849b-11a786e47924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$24,147
                                        </value>
      <webElementGuid>4a91f994-41ca-42a9-a398-0e93fa82e69a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_TotDepAuto10_result_value&quot;)</value>
      <webElementGuid>e28f0dd7-a4e1-4402-818c-e4d70929e6fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='lf_TotDepAuto10_result_value']</value>
      <webElementGuid>3cd71b21-8104-4887-9832-ea101ed6eed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='lf_TotDepAuto10_results']/td</value>
      <webElementGuid>70b32518-0880-4b4e-9917-7a2833a4b322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total depreciation'])[1]/following::td[1]</value>
      <webElementGuid>8289bfbe-6b4c-45fd-a0b3-6ebce62b4c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$10,908'])[1]/following::td[1]</value>
      <webElementGuid>718186fe-e4d8-4f92-b35e-52c8d8005c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$34,592'])[1]/preceding::td[1]</value>
      <webElementGuid>a15950ab-7410-4747-911b-6848c933c94a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td</value>
      <webElementGuid>7acfb228-c6ac-4965-a6e2-4aaf338a92b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'lf_TotDepAuto10_result_value' and (text() = '$24,147
                                        ' or . = '$24,147
                                        ')]</value>
      <webElementGuid>b2525e58-bffb-4aae-aaf2-7e6e8b6b1d02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
