<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_34,592</name>
   <tag></tag>
   <elementGuidId>b60b684b-266c-4cda-9ffd-1cad67066880</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_TotDep2Auto10_result_value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='lf_TotDep2Auto10_result_value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;$34,592&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>9bf3b24a-5ded-4faf-9a96-d867625622bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_TotDep2Auto10_result_value</value>
      <webElementGuid>5537027b-ba80-4b47-bbf3-e914614385e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableCellADA </value>
      <webElementGuid>8bb1583d-2a19-4ac0-9969-951307f3ce70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$34,592
                                        </value>
      <webElementGuid>09989a86-81f9-4d28-b08f-359819e73c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_TotDep2Auto10_result_value&quot;)</value>
      <webElementGuid>bb4e1a8a-7d88-4145-8ea3-435ab5fa7050</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='lf_TotDep2Auto10_result_value']</value>
      <webElementGuid>ab64cc29-a1f7-4c06-a73b-5b99c0456b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='lf_TotDepAuto10_results']/td[2]</value>
      <webElementGuid>138759c3-9d62-4cba-ba21-337f9e8d5ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$24,147'])[1]/following::td[1]</value>
      <webElementGuid>42f46e3c-5545-4c1b-a134-bdec018b6a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total depreciation'])[1]/following::td[2]</value>
      <webElementGuid>29eca061-1a8e-4554-b5a7-27bd57a268c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total repairs'])[1]/preceding::td[1]</value>
      <webElementGuid>b2515bd0-c39f-4706-9280-3e5f81a68cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]</value>
      <webElementGuid>4e7473ac-c549-4c83-990e-3120a2b95cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'lf_TotDep2Auto10_result_value' and (text() = '$34,592
                                        ' or . = '$34,592
                                        ')]</value>
      <webElementGuid>493764a5-91c1-4173-b217-f6b583b95203</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
