<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Basic</name>
   <tag></tag>
   <elementGuidId>e7ee0b7e-f894-4e58-9a38-2b1bb3f9bd9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_tab_basic</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='lf_tab_basic']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Basic&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc85b037-b068-4be2-82fd-6f17a9278265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>15fa5de5-f9a0-43ce-8ccf-c1401d8381f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_tab_basic</value>
      <webElementGuid>efe08324-cc78-4849-b736-c6f8d7c05527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-legend lf-secondary-gradient lf-open lf-tab-basic</value>
      <webElementGuid>da189b2c-00c7-40ed-80ec-fc76c319653d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>73d1176b-8852-49a4-80d2-35ca033369e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>aa58f397-c569-41e4-9139-9d471ffa61a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>basic-panel</value>
      <webElementGuid>345535c6-e6cc-4ce8-9d4e-431e06378a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>870bbd31-30f2-4ccc-b1bd-19bc30a165a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Basic
    </value>
      <webElementGuid>9248925a-79c4-450b-8d48-886a70f218db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_tab_basic&quot;)</value>
      <webElementGuid>e959a6ca-9cc0-4c8d-bb1f-6418c9215ef2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='lf_tab_basic']</value>
      <webElementGuid>ddf3113b-16c2-42e0-b0e5-014ab3eebd6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf-accordion-tab-template-placeholder']/button</value>
      <webElementGuid>cbd3fd7d-b1e2-4248-8313-a0ddc31e4781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inputs'])[1]/following::button[1]</value>
      <webElementGuid>694d80e1-fb80-44e7-b10c-e5b1c679007f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cs@leadfusion.com'])[1]/following::button[1]</value>
      <webElementGuid>8311ff64-8e95-46a7-9cd7-027490d7e9bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced'])[1]/preceding::button[1]</value>
      <webElementGuid>579a67f3-7296-493a-9cc7-96b678fedfc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic'])[2]/preceding::button[2]</value>
      <webElementGuid>3b3ff050-f93f-498e-ae8c-808e0359c70f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Basic']/parent::*</value>
      <webElementGuid>702a21d4-a651-4a34-8387-0b1eb96a843c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/div/button</value>
      <webElementGuid>3eede7c7-ddda-4c28-aaab-e59890b3af6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'lf_tab_basic' and (text() = 'Basic
    ' or . = 'Basic
    ')]</value>
      <webElementGuid>9354056b-1b04-4c77-9a6b-1da541bffc91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
