<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_What vehicle can I afford_lf-busy-overlay</name>
   <tag></tag>
   <elementGuidId>04165286-5e39-44e0-8477-03de75b99287</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf-busy-overlay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='lf-busy-overlay']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#lf-busy-overlay</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4cef260c-70bb-45ce-88a4-049da04ee8b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf-busy-overlay</value>
      <webElementGuid>75115982-c52a-46fb-b4e8-e7108390fae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget-overlay lf-busy-overlay</value>
      <webElementGuid>c73b58ce-0234-453c-8e85-dfcbeb91a1a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>abc3139b-4cfe-4a58-aadd-2a3f4957267a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf-busy-overlay&quot;)</value>
      <webElementGuid>2d3d54f8-6bc5-49d9-84a3-ce4d72f92c43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='lf-busy-overlay']</value>
      <webElementGuid>929fc591-ab24-416f-81bd-739bdecdb29e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]</value>
      <webElementGuid>144009a2-6ec2-469a-9083-6a31af88e47e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'lf-busy-overlay']</value>
      <webElementGuid>3f9b04d4-b3b0-4b64-816b-35f2c1b14a97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
