<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_2,060</name>
   <tag></tag>
   <elementGuidId>f698473b-7438-4f07-89e3-5b908f9a6b67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='lf-table-rows']/tr[48]/td[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;$2,060&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a705942f-1366-4abd-a312-ee716e37f556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableCellADA lf-graphs-table-col-6</value>
      <webElementGuid>07a7490c-f09c-43eb-8c44-e9de5e81b0d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$2,060</value>
      <webElementGuid>19289827-52e3-423e-8d70-1b7efb85121a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf-table-rows&quot;)/tr[@class=&quot;light-color-row&quot;]/td[@class=&quot;tableCellADA lf-graphs-table-col-6&quot;]</value>
      <webElementGuid>2becb25f-4d8e-44cf-8f13-6709141e1493</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='lf-table-rows']/tr[48]/td[6]</value>
      <webElementGuid>c76eb9eb-517b-41e3-8e82-3ba502b6074d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$2'])[1]/following::td[1]</value>
      <webElementGuid>f4b327a3-557c-4a1f-a675-b2492cbb842a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$448'])[2]/following::td[2]</value>
      <webElementGuid>44fbab39-f928-4a65-8ebe-e615a5275c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your payments over time'])[7]/preceding::td[1]</value>
      <webElementGuid>b29ba222-899a-40d7-a61e-cd4464321f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your payments over time'])[8]/preceding::td[1]</value>
      <webElementGuid>5528c11e-d419-45b4-a001-aef80eb5bc67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$2,060']/parent::*</value>
      <webElementGuid>6224b47a-fe20-489f-b936-acf25dbcc87b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[48]/td[6]</value>
      <webElementGuid>5166aa65-f627-4336-bc14-58f5af742786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '$2,060' or . = '$2,060')]</value>
      <webElementGuid>705f31fa-9b98-4f18-8ba4-dcd29aa8e4fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
