<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Down payment</name>
   <tag></tag>
   <elementGuidId>a83d13f9-671e-4ed2-bbe8-d407f28e0b2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf-legend-item-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//text[@id = 'lf-legend-item-2' and (text() = 'Down payment' or . = 'Down payment')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Interactive chart&quot;i >> internal:text=&quot;Down payment&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>19cc4ab8-2a86-4e17-8160-726c08e9b8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>4c469d26-2012-44e5-9d90-ebd833658a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>45bb84fa-05af-4449-a343-59b7c7306f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text-anchor</name>
      <type>Main</type>
      <value>start</value>
      <webElementGuid>f34be4bb-a94b-4715-8686-89d72dfc6b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>f737249e-3af7-4475-9625-cc2ca5985312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf-legend-item-2</value>
      <webElementGuid>49544b64-be40-4dc4-87c7-3917ddbde084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Down payment</value>
      <webElementGuid>6cc6c46e-87c4-4f7c-bc14-f941ef6d2d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf-legend-item-2&quot;)</value>
      <webElementGuid>c77412aa-de39-4d8b-915e-e263011971d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//text[@id = 'lf-legend-item-2' and (text() = 'Down payment' or . = 'Down payment')]</value>
      <webElementGuid>2a750d26-d2b7-443e-b8cb-d02ea96ce352</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
