<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Must be between 0.00 and 100.00_Globa_c7d20a</name>
   <tag></tag>
   <elementGuidId>a6fbcbc9-ae85-4210-b4c2-2981d7da5b38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_Global_SavingsInterestRate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lf_Global_SavingsInterestRate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Your savings interest rate, as a percent&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56f8b347-d5ed-4212-8dc0-282474f72c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Global_SavingsInterestRate</value>
      <webElementGuid>77b22cec-d60f-42b7-90eb-b69945c1ddaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Global_SavingsInterestRate</value>
      <webElementGuid>0d9c0dd1-2b89-48cf-8093-9391f4cc4513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-input-comma</value>
      <webElementGuid>dd300894-3823-48a9-b290-22f1ae15f916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>334940b8-63d5-4f53-8753-fcc51e3d7d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1.00</value>
      <webElementGuid>8d7c9374-b1de-4d30-9d5c-ea70ffcae24f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>6ea3068c-cca1-493f-ab34-8951ee807db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Your savings interest rate, as a percent</value>
      <webElementGuid>e8c72225-01de-40ba-9d21-bd49a4fbc7f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>df923c07-eca5-4509-a345-b9a00849b206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Global_SavingsInterestRate&quot;)</value>
      <webElementGuid>3e74ef55-8973-455e-98d2-049276a0d747</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lf_Global_SavingsInterestRate']</value>
      <webElementGuid>910258be-7f76-4059-a3cb-f96ce81b83a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Global_SavingsInterestRate_container']/div[3]/input</value>
      <webElementGuid>cdfa8216-5aac-4eda-b709-de2554f27f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/div/div[3]/div[3]/input</value>
      <webElementGuid>cd022742-1d15-44c5-9627-f937966ce519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lf_Global_SavingsInterestRate' and @name = 'Global_SavingsInterestRate' and @type = 'text']</value>
      <webElementGuid>39736299-4c43-44ed-b06d-176cd6e13ec0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
