<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_The tool helps you determine whether it i_fcc0c7</name>
   <tag></tag>
   <elementGuidId>25c5e8a8-fc51-4817-9f0c-d029e24e528e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_help_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='lf_help_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;The tool helps you determine whether it is cheaper to borrow money to buy a vehi&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>65744cc2-53df-45f3-9580-97c356931e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_help_0</value>
      <webElementGuid>fd081f1a-63fa-46eb-961c-13a5bf90c793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The tool helps you determine whether it is cheaper to borrow money to buy a vehicle or to pay cash.</value>
      <webElementGuid>a172b774-2c3f-4c1c-8bca-9e9a1c000c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_help_0&quot;)</value>
      <webElementGuid>129e773d-513b-4b19-89a8-a8d7af70ab58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='lf_help_0']</value>
      <webElementGuid>f45074cb-d0fa-4ccb-a3a5-79b1b576e9ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='lf-help-content']/p</value>
      <webElementGuid>f61521ff-d406-484c-bc59-7be65add7bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[4]/following::p[2]</value>
      <webElementGuid>b43ac8c3-a195-4537-bbdc-8cfbed3738a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[3]/following::p[3]</value>
      <webElementGuid>127a5a43-7b78-4d41-b7fa-c8843052c3a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End of help content'])[1]/preceding::p[3]</value>
      <webElementGuid>ce188195-22f2-452c-b660-3211595e1573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[5]/preceding::p[3]</value>
      <webElementGuid>ecf6d194-f838-4f80-8a2e-2358c4d93ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The tool helps you determine whether it is cheaper to borrow money to buy a vehicle or to pay cash.']/parent::*</value>
      <webElementGuid>a9e88c39-b3e4-4716-9af0-05d31d5aa487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/p</value>
      <webElementGuid>687a50b5-ed28-40b2-9738-d153dd6ac9e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'lf_help_0' and (text() = 'The tool helps you determine whether it is cheaper to borrow money to buy a vehicle or to pay cash.' or . = 'The tool helps you determine whether it is cheaper to borrow money to buy a vehicle or to pay cash.')]</value>
      <webElementGuid>49921060-53db-44bd-bcb2-69fcba46c3a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
