<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tax  Savings Rates</name>
   <tag></tag>
   <elementGuidId>1ee1f814-901d-4693-8acb-989da0ee8663</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TaxSavingsRates-accordion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='TaxSavingsRates-accordion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Tax &amp; Savings Rates category, Click to show details,&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>799cc15b-877b-4b7c-9f92-e9ed1702c4fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7583a035-9cfe-48cf-b680-db004281504c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3bf3eaf7-efeb-47e0-97dc-dfbcfb1424e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TaxSavingsRates-accordion</value>
      <webElementGuid>6ad58833-782f-4a45-b2e8-64492c76cb48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>lf-panel-TaxSavingsRates</value>
      <webElementGuid>b42fcf0b-4da5-469b-bf15-d044722a510a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-accordion-label</value>
      <webElementGuid>417abea0-dc1f-4dfa-857c-7ff4c9cfcb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>284dcfbe-e2f0-4923-94d4-1aabaffa1776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Tax &amp; Savings Rates category, Click to show details,</value>
      <webElementGuid>341179dd-99f5-4e7b-bc74-2f0257f352fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4b63e318-4d8b-47ff-81d7-daa52861d280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tax &amp; Savings Rates</value>
      <webElementGuid>25e24134-64d9-4be3-8f87-952a9de01d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TaxSavingsRates-accordion&quot;)</value>
      <webElementGuid>71d18cc9-3a20-4cf3-9e10-eda7412fab2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='TaxSavingsRates-accordion']</value>
      <webElementGuid>ae8d66cd-658b-412f-b5a6-a3f549863daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='lf-tab-TaxSavingsRates']/div/h3/a</value>
      <webElementGuid>1735710a-e783-456e-94aa-6437b01a3c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tax &amp; Savings Rates')]</value>
      <webElementGuid>590816b2-b511-436f-8fa2-67bd52de9f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interest rate'])[4]/following::a[1]</value>
      <webElementGuid>11235a0c-7d53-4408-929f-d4f50c627034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between 0.00% and 50.00%'])[2]/following::a[1]</value>
      <webElementGuid>4b9e638d-7e85-4e16-9540-fb7b4cc7ca53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your state &amp; federal tax rate'])[1]/preceding::a[1]</value>
      <webElementGuid>08da5a42-3380-4cde-830c-4e60313c9413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between 0.00% and 90.00%'])[1]/preceding::a[2]</value>
      <webElementGuid>8939d3f0-a5cd-4f97-855a-f3e2588db7a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tax &amp; Savings Rates']/parent::*</value>
      <webElementGuid>c508f4ce-f22c-41b4-a5cc-e48f24eb1ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[4]</value>
      <webElementGuid>c7680e5b-d413-408b-89c3-c1fe6485979d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/div/h3/a</value>
      <webElementGuid>f19173b1-dd33-4ace-8a5a-7b8090e36c61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'TaxSavingsRates-accordion' and @href = 'javascript:void(0)' and (text() = 'Tax &amp; Savings Rates' or . = 'Tax &amp; Savings Rates')]</value>
      <webElementGuid>3dd73a15-5fab-4661-a578-0ae9bc82669a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
