<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Interest rate</name>
   <tag></tag>
   <elementGuidId>7cf3997c-6e5d-43e9-b7e6-424b853d7325</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_Global_AutoInterestRate-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='lf_Global_AutoInterestRate-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#lf_Global_AutoInterestRate-label</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>4bbed605-4285-422e-8baa-07d49eb73c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>lf_Global_AutoInterestRate</value>
      <webElementGuid>baa6281e-543c-4f29-801d-8c1bb47a9bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Global_AutoInterestRate-label</value>
      <webElementGuid>453533e6-a981-4214-a463-c643ae2cc802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-field-label-no-tooltip</value>
      <webElementGuid>4e36525d-0bd6-4893-8463-013380e69065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Interest rate
                                
                        </value>
      <webElementGuid>eb96ab63-63af-4679-b9aa-a6765755bf91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Global_AutoInterestRate-label&quot;)</value>
      <webElementGuid>09f4d6e6-7bc9-4bf0-b7b9-de6fdb7ada88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='lf_Global_AutoInterestRate-label']</value>
      <webElementGuid>2aaa2ea5-5dfb-4168-a004-ccc188b9a782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Global_AutoInterestRate-table']/div/label</value>
      <webElementGuid>e6491c5b-e4ca-475c-91fe-97e55efa8f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loan term'])[1]/following::label[1]</value>
      <webElementGuid>174647ef-0caf-4feb-ad38-1862fa9a69a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between 1 and 360'])[1]/following::label[2]</value>
      <webElementGuid>f741e856-42d8-49ea-9247-a662ff5e0a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between 0.00% and 50.00%'])[1]/preceding::label[1]</value>
      <webElementGuid>32f5b9f2-fab6-4194-a740-6cffd196ab12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interest rate'])[2]/preceding::label[1]</value>
      <webElementGuid>ebfe12a3-d953-4280-9182-b5764f0b65cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Interest rate']/parent::*</value>
      <webElementGuid>2dd979b6-38cc-410d-9173-0d5bd5e0b569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/label</value>
      <webElementGuid>7100d826-77ef-4722-bbed-ded7f834cd05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'lf_Global_AutoInterestRate-label' and (text() = 'Interest rate
                                
                        ' or . = 'Interest rate
                                
                        ')]</value>
      <webElementGuid>21e0c0c4-92af-4489-8639-0a64a218ff7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
