<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Loan 2</name>
   <tag></tag>
   <elementGuidId>f2e0d7fb-fe81-4ce3-991b-250f9fbf47eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf-legend-item-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//text[@id = 'lf-legend-item-2' and (text() = 'Loan 2' or . = 'Loan 2')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Interactive chart&quot;i >> internal:text=&quot;Loan 2&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f4a4fb85-c264-4c7b-a71c-da12fe70f14a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>f656a37b-3f67-46dd-98fd-a815c5e53007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>2faae562-cf7e-4c40-a5bf-4e4fbcf7d794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text-anchor</name>
      <type>Main</type>
      <value>start</value>
      <webElementGuid>3c45d4c5-46f8-42bd-9b8b-e635e40a0fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>275d0343-51a7-4180-8976-c6f431ce91ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf-legend-item-2</value>
      <webElementGuid>7b7bf6ed-27f2-484d-907c-a14fa3234b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Loan 2</value>
      <webElementGuid>154058a3-4b61-4cde-a442-966da394ab3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf-legend-item-2&quot;)</value>
      <webElementGuid>2264794b-e130-493f-a952-259aa8670935</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//text[@id = 'lf-legend-item-2' and (text() = 'Loan 2' or . = 'Loan 2')]</value>
      <webElementGuid>8e47754c-861d-4169-8125-03da307c05d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
