<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Which is better a new or used vehicle_l_1eb8b8</name>
   <tag></tag>
   <elementGuidId>f65c383f-e2f7-4071-95ec-de32f534b4b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf-busy-overlay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='lf-busy-overlay']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c65937d1-86ea-4353-a459-4a8a0257a079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf-busy-overlay</value>
      <webElementGuid>0382dd9d-9df1-4a90-bb4d-0d446b8e5038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget-overlay lf-busy-overlay</value>
      <webElementGuid>81f61f7f-a3ec-4005-a427-7fe1466d37e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf-busy-overlay&quot;)</value>
      <webElementGuid>7b09f47e-15c8-40ce-8ff0-0c9b0004a7b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='lf-busy-overlay']</value>
      <webElementGuid>fa3e1028-4db8-4404-aa39-b7b1057f8b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]</value>
      <webElementGuid>cdce5cb1-1802-4500-9d69-d01f4412d078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'lf-busy-overlay']</value>
      <webElementGuid>2947a204-9454-4e77-b6aa-d09c67ac208f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
