<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_lf_next_steps_zoneA_title</name>
   <tag></tag>
   <elementGuidId>9b62830e-fee5-4498-aee9-e05f45524af2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'lf_next_steps_zoneA_title' and (text() = 'Next Steps' or . = 'Next Steps')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lf_next_steps_zoneA_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='lf_next_steps_zoneA_title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Next Steps&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>20f8a36d-6e1f-4366-a60d-84c71ec8fbe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_next_steps_zoneA_title</value>
      <webElementGuid>b524105f-4eb8-40da-9fe8-011336c8f68d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-modal-title</value>
      <webElementGuid>5cf8d111-135e-407d-a061-648b419965f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next Steps</value>
      <webElementGuid>b7fb21e0-fe16-49da-96e1-48af0983df88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_next_steps_zoneA_title&quot;)</value>
      <webElementGuid>8e5a4231-5f51-4f17-bf97-6bdcda84b465</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='lf_next_steps_zoneA_title']</value>
      <webElementGuid>128e69ea-3caf-40ab-8ca3-e574e8f24a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_next_steps_zoneA']/div/h2</value>
      <webElementGuid>7af22a69-7468-44d5-bce7-042c4c1602d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next Steps'])[5]/following::h2[1]</value>
      <webElementGuid>a6aa5b91-958c-4ec8-ac4c-ac0e120a393d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End of help content'])[1]/following::h2[2]</value>
      <webElementGuid>b05d7104-2ee9-47a3-873c-7d86b0cda8ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click Here'])[3]/preceding::h2[1]</value>
      <webElementGuid>46c02f8c-a52a-409c-aa89-4ebfe88368cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cs@leadfusion.com'])[3]/preceding::h2[1]</value>
      <webElementGuid>ecae6287-dec0-4f93-8ae1-279ab7860de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/h2</value>
      <webElementGuid>c510e375-d332-4e8b-b425-5e15c55f8616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'lf_next_steps_zoneA_title' and (text() = 'Next Steps' or . = 'Next Steps')]</value>
      <webElementGuid>c5f8418c-15c7-462d-a88e-46de03c510fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
