<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_4,210</name>
   <tag></tag>
   <elementGuidId>e469281b-315e-4167-846b-0c64d8ce8509</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_AveCostPerYr2Auto01_result_value > span.lf-nbsp-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='lf_AveCostPerYr2Auto01_result_value']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0eb23a11-44c8-4baf-92f3-5bc9aed88e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-nbsp-number</value>
      <webElementGuid>043857e5-d460-4f11-9db6-42fa2aad67c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$4,210</value>
      <webElementGuid>ff4c5358-a66b-46b4-8559-00806672aa0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_AveCostPerYr2Auto01_result_value&quot;)/span[@class=&quot;lf-nbsp-number&quot;]</value>
      <webElementGuid>e6fc28a9-7cb7-4dd8-a810-99d3b548c4ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='lf_AveCostPerYr2Auto01_result_value']/span</value>
      <webElementGuid>df86eae2-2d0d-4635-aab2-f14dafda6482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$100,270'])[1]/following::span[1]</value>
      <webElementGuid>8e42f278-af13-4166-b74a-89ed82f64c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Average cost per year'])[1]/following::span[2]</value>
      <webElementGuid>bf5d4e35-b0f5-4d69-a574-7ffea2245fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly payment'])[1]/preceding::span[1]</value>
      <webElementGuid>30ef7e4c-ee43-489e-97e0-3f6714295921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$20,039'])[1]/preceding::span[1]</value>
      <webElementGuid>0471eccf-cf48-4991-9d06-fb4454d3687f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$4,210']/parent::*</value>
      <webElementGuid>f6460dc2-395c-43c0-8b85-dcead1d23f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span</value>
      <webElementGuid>5c71c52a-62dd-44f8-bc18-048379cbb3e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '$4,210' or . = '$4,210')]</value>
      <webElementGuid>f47e322f-d82f-4254-b836-56db04a81df7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
