<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_100,270</name>
   <tag></tag>
   <elementGuidId>c2be4435-2b1b-4ec2-bf5c-c3aa1c1162bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.lf-nbsp-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='lf_AveCostPerYrAuto01_result_value']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4dd02b5a-7405-4c3e-93be-80f5c77655dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-nbsp-number</value>
      <webElementGuid>39ae24fb-53ee-4759-b83f-4c75ba6ff157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$100,270</value>
      <webElementGuid>d8a72815-469f-4955-a2ee-0f49fc10a234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_AveCostPerYrAuto01_result_value&quot;)/span[@class=&quot;lf-nbsp-number&quot;]</value>
      <webElementGuid>9d9b872b-070b-4754-8e32-13443ea30615</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='lf_AveCostPerYrAuto01_result_value']/span</value>
      <webElementGuid>300e333d-fd0d-4e31-b139-09a17f1e659b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Average cost per year'])[1]/following::span[1]</value>
      <webElementGuid>cc25b638-b13b-4c5a-976d-98f026da16c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Used'])[1]/following::span[1]</value>
      <webElementGuid>1bfaddf8-5d7c-4512-b474-251a91738d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$4,210'])[1]/preceding::span[1]</value>
      <webElementGuid>09c6dce8-c85b-4a4f-be4e-863b2c585c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly payment'])[1]/preceding::span[2]</value>
      <webElementGuid>cc19c759-9ae8-4825-ad24-37f8a1d311df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$100,270']/parent::*</value>
      <webElementGuid>13bd3088-52fa-46b2-b1e7-0f7311d0522e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span</value>
      <webElementGuid>6b19a4f0-563c-4927-af0a-d29a834e385b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '$100,270' or . = '$100,270')]</value>
      <webElementGuid>1226684c-80de-47a2-9245-56820a780620</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
