<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Loan 1</name>
   <tag></tag>
   <elementGuidId>8e940372-d481-4b56-bf49-f97d3df7bf52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Loan1-accordion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Loan1-accordion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Current selection, Loan 1 category, Click to hide details,&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a3cd5023-d227-4883-a8ca-3bbd8e968429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f6e47c84-2f81-4e51-aec4-3ba73175cf3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d3dd350a-0e57-4bfd-86db-86dddb64da8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Loan1-accordion</value>
      <webElementGuid>2cce9267-3106-43dd-be31-538a4f8855ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>lf-panel-Loan1</value>
      <webElementGuid>390eb9e2-61b7-4297-8a1d-237c5e503273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-accordion-label</value>
      <webElementGuid>a3a28fec-4bbe-40af-a5f7-93d3bc1100c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>19bbc0d6-96c7-4b61-8948-d5576291a9f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Current selection, Loan 1 category, Click to hide details,</value>
      <webElementGuid>cd304c0b-bdd1-4df2-8791-47fa185f402b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2e27be9c-cd02-4c03-9323-04b6b99ca362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Loan 1</value>
      <webElementGuid>8e740598-025e-473a-b0d6-037c5eabd86f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Loan1-accordion&quot;)</value>
      <webElementGuid>2a1178d3-3d79-48ba-8f1c-d00ce815685b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='Loan1-accordion']</value>
      <webElementGuid>6c242af5-8433-49a0-a86f-3b29caa05b56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='lf-tab-Loan1']/div/h3/a</value>
      <webElementGuid>f4082b61-2f1c-4e97-8398-c830169c0eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Loan 1')]</value>
      <webElementGuid>330cf49e-18b4-4f7e-a1f6-bc16d272ebd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inputs'])[1]/following::a[1]</value>
      <webElementGuid>14653801-fc4e-4083-a4b6-1e50b1783e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cs@leadfusion.com'])[1]/following::a[1]</value>
      <webElementGuid>73d086b1-83e0-4f87-8c20-5246ecf890a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase price'])[1]/preceding::a[1]</value>
      <webElementGuid>53bea706-891e-47f3-9898-00dec3314d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between $0 and $1,000,000'])[1]/preceding::a[1]</value>
      <webElementGuid>dce1d78c-622e-4eb4-aa48-fc7580d51950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>216c57bb-61bc-4b9e-b20a-44f0ecbbef76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>3b130ed2-bf3c-4a75-9614-73b5ab48b265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'Loan1-accordion' and @href = 'javascript:void(0)' and (text() = 'Loan 1' or . = 'Loan 1')]</value>
      <webElementGuid>bc8b9019-3782-43a0-a3e0-6f10a6dffaa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
