<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Loan 2</name>
   <tag></tag>
   <elementGuidId>ea2870c4-497b-48d6-b0d7-01baecb16fb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Loan2-accordion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Loan2-accordion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Loan 2 category, Click to show details,&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>37a25b62-d2ab-4d4b-9001-25fd5a9cd4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cfddf300-4fb6-4ca7-aa1e-0e2f2fd06caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>09a87227-ed15-4ec0-b2b3-7c280986c37c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Loan2-accordion</value>
      <webElementGuid>da28c609-5389-4992-81ce-3fe1fdbee92f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>lf-panel-Loan2</value>
      <webElementGuid>4aa702cb-9cba-447c-9f2b-771c7df9e62b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-accordion-label</value>
      <webElementGuid>b0efdfa9-fb03-4486-9e3c-ce4d2cb4f8d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>03ef1859-ba9f-4661-a01d-23ac53afde20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Loan 2 category, Click to show details,</value>
      <webElementGuid>bc131750-891f-43a2-81f7-0a380c50bdf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>26811842-bf18-47af-b930-0381cc8839e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Loan 2</value>
      <webElementGuid>f2a987a1-bdfc-44c3-9696-528f199ccd16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Loan2-accordion&quot;)</value>
      <webElementGuid>b4d0abc5-996a-4766-af5d-2fcb5576fd6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='Loan2-accordion']</value>
      <webElementGuid>78fe031c-9ab8-4d7b-aa20-82dbebdc7938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='lf-tab-Loan2']/div/h3/a</value>
      <webElementGuid>cf233e77-cb67-481e-8c37-fb2e23fcd6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Loan 2')]</value>
      <webElementGuid>2b935f30-da1f-43f2-b806-3da46aaffa15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interest rate'])[2]/following::a[1]</value>
      <webElementGuid>2283ef93-985a-487f-967c-79177e56aaef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between 0.00% and 50.00%'])[1]/following::a[1]</value>
      <webElementGuid>4801de20-f189-4f96-8466-994d68fbfeb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase price'])[3]/preceding::a[1]</value>
      <webElementGuid>8f961282-3e43-4f25-aea9-0c3a75d304d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between $0 and $250,000'])[1]/preceding::a[1]</value>
      <webElementGuid>6990f9be-3651-430c-b6de-a4bba7e3a8ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[2]</value>
      <webElementGuid>0e1d61c8-2580-4aaa-b85f-a151884583f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/h3/a</value>
      <webElementGuid>7965a4c2-864b-41a5-a076-941633c2706c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'Loan2-accordion' and @href = 'javascript:void(0)' and (text() = 'Loan 2' or . = 'Loan 2')]</value>
      <webElementGuid>236aa4cf-8072-4344-bea8-983326af06bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
