<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Amortization</name>
   <tag></tag>
   <elementGuidId>f86c91cf-7754-4a6c-be58-097cbdb6f7f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_graph_tabs_lf_container3 > div.lf-dot-holder.lf-dot-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='lf_graph_tabs_lf_container3']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Amortization&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bc157326-c77e-4c8b-9df7-979662f463e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-dot-holder lf-dot-label</value>
      <webElementGuid>7b0f1b96-20d0-4024-bd00-e15a1d795349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Amortization</value>
      <webElementGuid>4af5be89-7a2f-44e4-8c98-182ce3e9cd6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_graph_tabs_lf_container3&quot;)/div[@class=&quot;lf-dot-holder lf-dot-label&quot;]</value>
      <webElementGuid>4eb62590-0450-4439-b17e-6b1b9e020aae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='lf_graph_tabs_lf_container3']/div</value>
      <webElementGuid>25224a12-7e24-48d2-92a8-24dfd6f1b808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payments'])[1]/following::div[1]</value>
      <webElementGuid>fb540215-7b88-4697-b1a6-cd84bfa9bf2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Cost'])[2]/following::div[2]</value>
      <webElementGuid>8c5e3eff-d81e-44a1-ac67-f9b9b4166489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click Here'])[1]/preceding::div[3]</value>
      <webElementGuid>bd22c1c3-70e7-44c3-8285-2b7f341eb4fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cs@leadfusion.com'])[1]/preceding::div[3]</value>
      <webElementGuid>caf3ee0b-7f3c-4260-b0a1-facd3799aac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Amortization']/parent::*</value>
      <webElementGuid>59b59c3a-2ed7-46a5-9973-99bfd38956ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]/div</value>
      <webElementGuid>b244e657-a06f-48c2-9cf7-dd60186c803c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Amortization' or . = 'Amortization')]</value>
      <webElementGuid>a3625bc4-0612-42c2-a102-28267c4a3db1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
