<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Must be between 0 and 249,999_Auto_Se_3b0f6d</name>
   <tag></tag>
   <elementGuidId>7f6415bc-57ea-4147-b514-c83063f0cb05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_Auto_SecondLoanDownPayment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lf_Auto_SecondLoanDownPayment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Down payment, in dollars&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82253426-a0f5-4b26-abdf-96547d49d2a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Auto_SecondLoanDownPayment</value>
      <webElementGuid>2a0e4061-fca5-44c1-8191-1fe8bb038264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Auto_SecondLoanDownPayment</value>
      <webElementGuid>d905f30a-f270-470b-b519-51ca3c0a9795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-input-comma</value>
      <webElementGuid>4a7821fd-5f8a-49ca-b80c-40b5788be56c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fb34f9d2-eabb-4f04-99cc-c233bb58e8c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>933e5fed-ff00-4cff-bae9-efff62a8eaae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>de8d509e-cca1-4738-978e-7bb62130aa53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Down payment, in dollars</value>
      <webElementGuid>8e93f0a5-2901-44dd-818b-1c6e49f79bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>390924ba-7373-44c4-90d7-0eece9060114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0c648072-5fc8-41b8-a339-6f0985d85dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Auto_SecondLoanDownPayment&quot;)</value>
      <webElementGuid>03dd3693-1b3e-44ef-b12c-9662d68a022f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lf_Auto_SecondLoanDownPayment']</value>
      <webElementGuid>1a565482-33f5-442c-b410-80909b06ccf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Auto_SecondLoanDownPayment-table']/div[3]/input</value>
      <webElementGuid>9dac8b86-991b-405b-92e9-4b99361583bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div[3]/div[2]/div[3]/input</value>
      <webElementGuid>94283589-cd21-4c9f-9320-711611fffbdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lf_Auto_SecondLoanDownPayment' and @name = 'Auto_SecondLoanDownPayment' and @type = 'text']</value>
      <webElementGuid>83852366-5fda-47a3-a6b7-c07b296a82de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
