<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Loan 2 will cost you, in todays dollar_b2c683</name>
   <tag></tag>
   <elementGuidId>0cfe2d75-51c5-4ea3-a18f-a652a443ae07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_answer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='lf_answer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#lf_answer</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5fbeb8de-3360-4a20-b61d-8854cae780ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_answer</value>
      <webElementGuid>3f570b02-574b-4cfb-8757-aa004fd395af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Loan 2 will cost you, in today's dollars, $18,161 less than Loan 1</value>
      <webElementGuid>9614f52c-ac22-4f45-ba16-b76ff404c614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_answer&quot;)</value>
      <webElementGuid>8c33ec79-03e8-4322-b835-14d5b55ffdd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='lf_answer']</value>
      <webElementGuid>b29954ba-5c88-4eb5-b6f8-b2c213de8688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_main']/div/div[3]/div[3]/div/div[3]/h2/span</value>
      <webElementGuid>68ab3354-9f48-45ea-aa21-a19aa0a96b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$18,161 less'])[1]/following::span[1]</value>
      <webElementGuid>3f07b226-9149-468b-8a99-813884a2f999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show details'])[1]/preceding::span[2]</value>
      <webElementGuid>6599c696-e85f-47eb-a218-b1b7235f5828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/span</value>
      <webElementGuid>8b694d4e-d756-4f27-a968-53e44570e59a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'lf_answer' and (text() = concat(&quot;Loan 2 will cost you, in today&quot; , &quot;'&quot; , &quot;s dollars, $18,161 less than Loan 1&quot;) or . = concat(&quot;Loan 2 will cost you, in today&quot; , &quot;'&quot; , &quot;s dollars, $18,161 less than Loan 1&quot;))]</value>
      <webElementGuid>1b8ab73e-0406-47c9-9f4c-d5f106f3e8b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
