<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_570</name>
   <tag></tag>
   <elementGuidId>fb59d22b-7aba-4a52-9680-7c541634de35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_MonPmt2Auto06_result_value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='lf_MonPmt2Auto06_result_value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;$570&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>fad231b8-94b6-4a6d-923a-bf0f500cbaad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_MonPmt2Auto06_result_value</value>
      <webElementGuid>dac73731-ed7b-4c83-bc8a-43908ed9a3d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableCellADA </value>
      <webElementGuid>6d54f635-ff5f-4704-80e2-b2db518a3298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$570
                                        </value>
      <webElementGuid>a7862ac3-69b2-4039-b5d8-bde7cf7ab3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_MonPmt2Auto06_result_value&quot;)</value>
      <webElementGuid>1d190dd8-fb2a-4340-80e4-587566653005</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='lf_MonPmt2Auto06_result_value']</value>
      <webElementGuid>95fc6204-0d58-48ae-99cf-f8855b8d6822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='lf_MonPmtAuto06_results']/td[2]</value>
      <webElementGuid>641d410b-876f-4fb2-a0c1-ef7e11712bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$875'])[1]/following::td[1]</value>
      <webElementGuid>dc9d4461-4273-4ae9-9e87-87c860c5ce6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly payment'])[1]/following::td[2]</value>
      <webElementGuid>053fa83e-9358-4012-ad7c-228b32a186b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total interest paid'])[1]/preceding::td[1]</value>
      <webElementGuid>d1d91151-8ccf-4dc9-9b24-2ed4ab83d917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>6f3cdabd-ccbd-4699-ac7d-46fca9302da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'lf_MonPmt2Auto06_result_value' and (text() = '$570
                                        ' or . = '$570
                                        ')]</value>
      <webElementGuid>2248da7a-6fab-4327-831d-542a6836960d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
