<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_i</name>
   <tag></tag>
   <elementGuidId>5d61d3b5-af89-4a47-9882-f52894d981d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_Global_AutoDownPayment_tooltip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lf_Global_AutoDownPayment_tooltip']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Show tooltip for Down payment&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b6c01396-681f-4635-ac02-e398c9e3c5f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>71015c28-628b-4e7f-b751-9fb19ab568ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#downpayment</value>
      <webElementGuid>581abf3c-0c81-44d0-9cc8-35130d6fcb5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Global_AutoDownPayment_tooltip</value>
      <webElementGuid>ca09dc3f-256a-4fba-b433-0a0df6876f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-show-tooltip</value>
      <webElementGuid>3b1cfccf-26dd-4138-8d26-c5375449b4a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Show tooltip for Down payment</value>
      <webElementGuid>50237fd8-3b82-40e7-bcc2-65602a844fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dfc1c4ad-bf2d-4d48-8c97-53e93ac8fcfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            i
                        </value>
      <webElementGuid>b25946df-bca4-4962-982a-c2d36df31b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Global_AutoDownPayment_tooltip&quot;)</value>
      <webElementGuid>f6b94ac4-947d-467d-a017-e0e90008aeba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lf_Global_AutoDownPayment_tooltip']</value>
      <webElementGuid>bd896ac9-ff9e-42cc-837f-574d5aa8a11d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Global_AutoDownPayment_container']/div/a</value>
      <webElementGuid>8ec2d269-3bf2-45af-adcb-7c58c48c7430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Down payment'])[1]/following::a[1]</value>
      <webElementGuid>7fc5b7f4-a599-4107-9dcc-8eb9c6defc63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase price'])[2]/following::a[1]</value>
      <webElementGuid>055557e0-f368-4fc5-aefa-b32614224342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between $0 and $249,999'])[1]/preceding::a[1]</value>
      <webElementGuid>1202a807-090f-47e2-b559-431a74e18286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Down payment'])[2]/preceding::a[1]</value>
      <webElementGuid>9150f591-5892-4ba9-b752-e41084996fc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#downpayment')]</value>
      <webElementGuid>49af29dc-c49b-4d44-b0e2-11f766585946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>4089e2d5-d9ed-45e7-b40c-5e614e99f355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#downpayment' and @id = 'lf_Global_AutoDownPayment_tooltip' and (text() = '
                            i
                        ' or . = '
                            i
                        ')]</value>
      <webElementGuid>6b571f0e-f0ac-4a81-aaad-26d515335847</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
