<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_2,010</name>
   <tag></tag>
   <elementGuidId>df3a7d2b-143e-4963-ab00-e816be49849c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_Auto_TotalInterestPaid_result_value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='lf_Auto_TotalInterestPaid_result_value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;$2,010&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e07f742f-3553-408a-98fd-b26a7628c5d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Auto_TotalInterestPaid_result_value</value>
      <webElementGuid>c126ff18-e49f-40d5-b166-14fa3434106d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableCellADA </value>
      <webElementGuid>6a1c297b-347f-4a5f-a8cc-788359795989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$2,010
                                            </value>
      <webElementGuid>56c55c8b-3ff3-4342-9ef6-12b231a0c310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Auto_TotalInterestPaid_result_value&quot;)</value>
      <webElementGuid>d2c65783-1282-4c86-812f-2037b226bb0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='lf_Auto_TotalInterestPaid_result_value']</value>
      <webElementGuid>8276a01d-eaad-46ee-b65b-313168703ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='lf_Auto_TotalInterestPaid_results']/td</value>
      <webElementGuid>64129033-7278-49e1-9c32-0d6ce32b3484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total interest paid'])[1]/following::td[1]</value>
      <webElementGuid>8f3af54e-2a6a-4eef-96ff-1a08f7df3194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$23,164'])[1]/following::td[1]</value>
      <webElementGuid>3dfa18ee-7913-4d87-9a6d-bdc1bdf09ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next Steps'])[1]/preceding::td[1]</value>
      <webElementGuid>50af6553-e171-41fb-b8e8-815dcbe0e61e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td</value>
      <webElementGuid>d57f1e91-b2d0-4bc1-94d0-1acb9b05bfb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'lf_Auto_TotalInterestPaid_result_value' and (text() = '$2,010
                                            ' or . = '$2,010
                                            ')]</value>
      <webElementGuid>b9a24ee8-f963-49c7-8578-d3a54cf96b73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
