<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_233</name>
   <tag></tag>
   <elementGuidId>343aa76b-6888-45f0-8eb7-18c6bf9bb325</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='lf_MonPmt2Auto01_result_value']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lf_MonPmt2Auto01_result_value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;$233&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>aca6d908-fb75-4081-987e-49d7206a6d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_MonPmt2Auto01_result_value</value>
      <webElementGuid>9bfa8294-3db1-4ba6-859b-3d5dde7a1373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableCellADA </value>
      <webElementGuid>d74d7cdf-b0f3-4d38-bfaa-eb02f65ba10c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$233
                                        </value>
      <webElementGuid>6f4661e4-3227-4167-b7a8-f350a22726cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_MonPmt2Auto01_result_value&quot;)</value>
      <webElementGuid>7d0e15bc-88f9-4fb2-8859-8d0415ed6d90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='lf_MonPmt2Auto01_result_value']</value>
      <webElementGuid>3dc0097c-92e3-469f-a3af-53625f876cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='lf_MonPmtAuto01_results']/td[2]</value>
      <webElementGuid>c61f47e0-646c-44be-8d4e-a7164db017d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$875'])[1]/following::td[1]</value>
      <webElementGuid>3a353e8d-4d93-4421-a4d0-c22a7471d304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly payment'])[1]/following::td[2]</value>
      <webElementGuid>b080ffa9-1ce0-4b73-802d-dfedaefabb9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total interest paid'])[1]/preceding::td[1]</value>
      <webElementGuid>3e408853-d131-418a-b8d7-2617bae48fa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]</value>
      <webElementGuid>42d9bfe7-8b02-4b8b-8004-01f949a55d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'lf_MonPmt2Auto01_result_value' and (text() = '$233
                                        ' or . = '$233
                                        ')]</value>
      <webElementGuid>c8c76a0b-dcfc-46f1-824b-ff5eec1911d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
