<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_7,735</name>
   <tag></tag>
   <elementGuidId>1ada4434-be3a-4543-b316-a3daf05b8057</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='lf_AveCostPerYrAuto01_result_value']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lf_AveCostPerYrAuto01_result_value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;$7,735&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>bfda3fe4-0f5b-4193-be7f-b16ac7fb31eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_AveCostPerYrAuto01_result_value</value>
      <webElementGuid>aa69bb4d-7836-4d85-bef7-22e69b4e0b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableCellADA </value>
      <webElementGuid>0f5534c6-6aa4-43d3-84d7-de6a10e5b411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$7,735
                                        </value>
      <webElementGuid>999496e8-33e4-4ffa-a587-208083534ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_AveCostPerYrAuto01_result_value&quot;)</value>
      <webElementGuid>8facb0fe-4d9b-4ece-8dc2-2dd3fe5624e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='lf_AveCostPerYrAuto01_result_value']</value>
      <webElementGuid>bce5770f-457e-498c-9959-9712a2b5b0d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='lf_AveCostPerYrAuto01_results']/td</value>
      <webElementGuid>58b54a1a-594e-421f-82a3-cc1a458eb473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Average cost per year'])[1]/following::td[1]</value>
      <webElementGuid>036cc9b0-985e-40dd-b3bc-c6a15207fe98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Used'])[1]/following::td[1]</value>
      <webElementGuid>2f8b070c-cbf4-4b9d-a284-10e76cd9cb54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$3,193'])[1]/preceding::td[1]</value>
      <webElementGuid>e19e6e09-78bf-4ad6-9314-9fc763e67118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/td</value>
      <webElementGuid>fb8db3a0-c561-4246-9abe-f88206439d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'lf_AveCostPerYrAuto01_result_value' and (text() = '$7,735
                                        ' or . = '$7,735
                                        ')]</value>
      <webElementGuid>059a796a-3f7f-4785-9b78-c708691080e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
