<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_i_1</name>
   <tag></tag>
   <elementGuidId>a207a65b-099d-48ae-98d4-f7ca80d908d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_Global_AutoLoanTerm_tooltip > div.lf-tooltip-i</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lf_Global_AutoLoanTerm_tooltip']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>02c13b3a-73bf-40da-af2d-a174512c1043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c8ba602d-c022-4d5e-a548-f60a08989fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-tooltip-i</value>
      <webElementGuid>1affebd2-aa9d-4e0b-a1f7-a88ae034151d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>6e74f702-dedb-42cd-b838-8f0a9e2a4960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Global_AutoLoanTerm_tooltip&quot;)/div[@class=&quot;lf-tooltip-i&quot;]</value>
      <webElementGuid>67038bbd-49e8-42c6-8816-2704a37545ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='lf_Global_AutoLoanTerm_tooltip']/div</value>
      <webElementGuid>a50d44a4-137d-4d38-b6c9-f61900ccfbea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(months)'])[1]/following::div[1]</value>
      <webElementGuid>ef1a3bb7-90c9-45a1-83e8-b21244836f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between 1 and 360'])[1]/preceding::div[1]</value>
      <webElementGuid>c8e0f3dc-ca70-40da-b830-64958e8bec11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loan term'])[1]/preceding::div[2]</value>
      <webElementGuid>6d34d9b0-5c36-452a-ab75-38aa7de00305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a/div</value>
      <webElementGuid>86a303c6-fa4e-4336-8129-7abf9f89031f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'i' or . = 'i')]</value>
      <webElementGuid>f68e58c0-a17a-4980-a419-d64fdf616635</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
