<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Help</name>
   <tag></tag>
   <elementGuidId>7a260d34-d428-4610-956c-ecfb0d7fb168</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_help_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='lf_help_title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>3bc51f1a-ed24-4499-90ef-8662654c932a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_help_title</value>
      <webElementGuid>f894a61d-decd-4b06-9d52-4211927d4789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-modal-title</value>
      <webElementGuid>6013ca28-facd-4d7a-8d42-84a5cf766cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Help</value>
      <webElementGuid>7177a968-fb02-4186-9757-a424eb0d04ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_help_title&quot;)</value>
      <webElementGuid>8cca1070-6113-4122-85f5-57c64a7157f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='lf_help_title']</value>
      <webElementGuid>77136ffb-4647-4bcb-bb2c-04788fa95ac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_help_Container']/div/h2</value>
      <webElementGuid>f79b3ad4-bd61-4701-8ebe-c10acbdc7c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[3]/following::h2[1]</value>
      <webElementGuid>553bc17a-fbaf-4f20-b66f-bc108758b0d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[2]/following::h2[3]</value>
      <webElementGuid>a8043442-1c75-4b78-9f9a-7642e80a3b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase price.'])[1]/preceding::h2[2]</value>
      <webElementGuid>98985001-917c-45a7-858f-a1692a0d5972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Depreciation.'])[1]/preceding::h2[2]</value>
      <webElementGuid>5f199499-d503-4c95-be74-eeae6c25a5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h2</value>
      <webElementGuid>a5ec0e7a-b39b-4e0d-b0c0-e6491d7e005d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'lf_help_title' and (text() = 'Help' or . = 'Help')]</value>
      <webElementGuid>dfee074a-f6c1-47da-8965-38ae67b83d2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
