<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Must be between 0.00 and 100.00_Global_SavingsInterestRate</name>
   <tag></tag>
   <elementGuidId>9e151c56-efff-47f0-a2f0-ef42d1b10182</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lf_Global_SavingsInterestRate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lf_Global_SavingsInterestRate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac6b0443-1772-4054-9330-4d4da2613c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Global_SavingsInterestRate</value>
      <webElementGuid>ac298b22-bf80-47be-aca9-fed325ee4000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Global_SavingsInterestRate</value>
      <webElementGuid>685d2c3a-c9ed-480e-b16f-b11d7b5d81e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-input-comma</value>
      <webElementGuid>5a73e606-dbc1-4f09-917f-2df253e6990a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c8e6b86b-3b27-4b79-b4c4-b0617e3ca061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1.00</value>
      <webElementGuid>5dc2ef43-9aeb-497f-b939-2134d9a4cc22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>5742ec5a-b7fb-413a-a490-e4f3ab5b1383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Your savings interest rate, as a percent</value>
      <webElementGuid>ef0711d5-8ea0-4b5f-9d4e-78b1759fbc82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Global_SavingsInterestRate&quot;)</value>
      <webElementGuid>bbff10ea-080c-4def-8fb5-d2d30ac0fc56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lf_Global_SavingsInterestRate']</value>
      <webElementGuid>08bf0d1f-99e0-4df7-9238-60d3fc0fd450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Global_SavingsInterestRate-table']/div[3]/input</value>
      <webElementGuid>cfa51b14-235a-4228-b35c-9043e63ada4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[5]/div[3]/div[3]/div[3]/input</value>
      <webElementGuid>c9c1dfe9-220d-4ea2-8b7c-09bad0ef7da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lf_Global_SavingsInterestRate' and @name = 'Global_SavingsInterestRate' and @type = 'text']</value>
      <webElementGuid>acd7ebb6-f8a1-4108-ad1c-0eedfa55a6b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
