<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Monthly insurance costs</name>
   <tag></tag>
   <elementGuidId>947c6549-b33c-48de-8cc0-97dc02ab4080</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_Auto_MonthlyInsurance-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='lf_Auto_MonthlyInsurance-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>cc04f04c-30ca-4f61-95ae-254b0557cd80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>lf_Auto_MonthlyInsurance</value>
      <webElementGuid>e513a099-6719-4fb7-bafc-d1473ba55635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Auto_MonthlyInsurance-label</value>
      <webElementGuid>849bd7dc-c034-4bbf-808b-7877aa9552d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-field-label-no-tooltip</value>
      <webElementGuid>32945530-1552-467c-ad63-d2dfc36e21ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Monthly insurance costs
                                
                        </value>
      <webElementGuid>f65e2bbf-de2f-4d89-ba1d-9dc1b3601ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Auto_MonthlyInsurance-label&quot;)</value>
      <webElementGuid>a2df12c0-fff5-4bac-8dde-44ba7cae361f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='lf_Auto_MonthlyInsurance-label']</value>
      <webElementGuid>5dffbd62-64c3-430b-bbf2-de7e2a668ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Auto_MonthlyInsurance-table']/div/label</value>
      <webElementGuid>70cd16d6-c117-4a0c-83c5-73e27ca60006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly maintenance costs'])[2]/following::label[1]</value>
      <webElementGuid>c1d2cf12-7825-4693-9ce7-6e45d3abb9d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between $0 and $10,000'])[1]/following::label[2]</value>
      <webElementGuid>043b6e4f-9527-40fd-b37f-def8551d7d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between $0 and $10,000'])[2]/preceding::label[1]</value>
      <webElementGuid>f2b4ad08-64ea-4bb8-811b-aadd35d89f51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly insurance costs'])[2]/preceding::label[1]</value>
      <webElementGuid>55ccf985-c9c9-4646-84d8-2a081d020625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Monthly insurance costs']/parent::*</value>
      <webElementGuid>2a79ced2-4050-4b28-9565-94404ad0fcc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div[3]/div[3]/div/label</value>
      <webElementGuid>22e67312-9c32-4d61-9f1e-d442f35adff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'lf_Auto_MonthlyInsurance-label' and (text() = 'Monthly insurance costs
                                
                        ' or . = 'Monthly insurance costs
                                
                        ')]</value>
      <webElementGuid>8c47d37a-1a49-45ba-964e-880461c056c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
