<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Purchase price. A new vehicle will clearl_f88dae</name>
   <tag></tag>
   <elementGuidId>f8bb5d06-6b57-46ba-b80f-13ec7cad3406</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_help_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='lf_help_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>df391eb7-eed0-4952-92d4-69b94f9d07a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_help_1</value>
      <webElementGuid>b92f074f-4faa-49b5-83b8-79cbab5dddbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Purchase price. A new vehicle will clearly cost you more than a used vehicle of the same make and model. The extent to which the new or used car will drop in value is based on the depreciation rate chosen - average, high or low.</value>
      <webElementGuid>d42a382c-4962-48ed-8945-42ca6baed1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_help_1&quot;)</value>
      <webElementGuid>abb769b9-daf2-467b-9433-5760d0763ed6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='lf_help_1']</value>
      <webElementGuid>77596bd4-7e50-4419-9e25-2dfc88fd924c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='lf-help-content']/p[2]</value>
      <webElementGuid>ee12ed84-2cb3-4dd8-8dbe-63deb3784ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[4]/following::p[3]</value>
      <webElementGuid>6c2c3a6c-fd3d-4e5c-99a4-009ddd88f997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[3]/following::p[3]</value>
      <webElementGuid>c9362cbb-a7f5-4e8e-ae18-ccca606d8285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Depreciation.'])[1]/preceding::p[1]</value>
      <webElementGuid>892a1b7a-8d13-4d15-b5c0-6926cf7f3457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='A new vehicle will clearly cost you more than a used vehicle of the same make and model. The extent to which the new or used car will drop in value is based on the depreciation rate chosen - average, high or low.']/parent::*</value>
      <webElementGuid>2a37022c-4ded-4634-97cf-b17b4bb9d510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>96541de5-ef90-41df-9f91-ff983a81f1ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'lf_help_1' and (text() = 'Purchase price. A new vehicle will clearly cost you more than a used vehicle of the same make and model. The extent to which the new or used car will drop in value is based on the depreciation rate chosen - average, high or low.' or . = 'Purchase price. A new vehicle will clearly cost you more than a used vehicle of the same make and model. The extent to which the new or used car will drop in value is based on the depreciation rate chosen - average, high or low.')]</value>
      <webElementGuid>388a7479-6fbe-4cff-b27c-9f6862fd4d8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
