<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_28,062</name>
   <tag></tag>
   <elementGuidId>8ab00ae9-0f36-4fb0-b95d-d6d88470ac53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='lf_TotDep2Auto01_result_value']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lf_TotDep2Auto01_result_value > span.lf-nbsp-number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>654d478c-f8df-40a4-a0b7-c104399e8865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-nbsp-number</value>
      <webElementGuid>95f4c4d9-9029-467e-813f-2eb0954d598f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$28,062</value>
      <webElementGuid>b0300410-2fd5-47e5-aeab-f30ef5fe9fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_TotDep2Auto01_result_value&quot;)/span[@class=&quot;lf-nbsp-number&quot;]</value>
      <webElementGuid>287a7916-8b2e-4865-9f2e-ad05b59b747e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='lf_TotDep2Auto01_result_value']/span</value>
      <webElementGuid>6a1d40d3-98a8-42b6-9494-44e8a2886502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$46,074'])[1]/following::span[1]</value>
      <webElementGuid>eae66efe-391d-476e-bcda-779bc189de12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total depreciation'])[1]/following::span[2]</value>
      <webElementGuid>d9631db4-ebd2-4494-93a9-2c6886ef02bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next Steps'])[1]/preceding::span[1]</value>
      <webElementGuid>277747ac-e209-4546-8ac9-d5acc9e65a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable color patterns'])[1]/preceding::span[1]</value>
      <webElementGuid>f0ffe1b9-2690-4be7-9b96-1fe405910efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$28,062']/parent::*</value>
      <webElementGuid>44e97dc8-c47d-4fe5-89b0-31a80c0cc7e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/span</value>
      <webElementGuid>1f356cd3-a38e-48b2-9b3f-2031951df44d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '$28,062' or . = '$28,062')]</value>
      <webElementGuid>0dcf67c8-761e-4295-90d1-ce2b17bea840</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
