<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>0f5477f6-2fe0-4fa4-9255-ffe56e8fd626</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='lf_Global_SavingsInterestRate_suffix']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lf_Global_SavingsInterestRate_suffix</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e4436b69-3f2c-414c-b8e5-6588223694aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Global_SavingsInterestRate_suffix</value>
      <webElementGuid>0291616a-d8f7-4b82-9320-54e490691cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-after-input</value>
      <webElementGuid>a9c36b8c-9adb-4b1d-a057-93e6956eb830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>89d7e875-7a83-493e-ba13-a30f8bdd40e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>%</value>
      <webElementGuid>d22c2e26-3bc0-4abd-a5ef-3980a01b9819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Global_SavingsInterestRate_suffix&quot;)</value>
      <webElementGuid>6756c50e-2735-4886-a822-e845c355e1fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='lf_Global_SavingsInterestRate_suffix']</value>
      <webElementGuid>8c993204-6780-4b83-a541-7f9b2cd897c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Global_SavingsInterestRate-table']/div[3]/span[2]</value>
      <webElementGuid>2479b5fd-9f28-494e-9f1f-2d5d115dc8ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between 0.00% and 100.00%'])[1]/following::span[2]</value>
      <webElementGuid>5e3a3445-5b70-46a0-8da0-825b05802a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your savings interest rate'])[1]/following::span[2]</value>
      <webElementGuid>cee92e71-38ba-45e6-9b96-025b5bbe9d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your savings interest rate'])[2]/preceding::span[2]</value>
      <webElementGuid>9caa775e-f212-4113-90c3-05ba6358c057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click Here'])[2]/preceding::span[2]</value>
      <webElementGuid>ce85f41d-f434-4f43-adfc-4192c4b2272c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[5]/div[3]/div[3]/div[3]/span[2]</value>
      <webElementGuid>81144b22-1f4a-4e62-9a54-7393cccf502d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'lf_Global_SavingsInterestRate_suffix' and (text() = '%' or . = '%')]</value>
      <webElementGuid>55d276cd-1835-4ab3-8aa2-d5684bc4b065</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
