<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_7,735_1</name>
   <tag></tag>
   <elementGuidId>24ccea79-00ca-4426-a257-a1492a5d555a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.highcharts-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='highcharts-data-table-0']/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>ff380d7f-d584-4d69-9020-0e44efc185ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>highcharts-number</value>
      <webElementGuid>edcd4674-f5c9-48e8-8b30-1b984e5bf6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$7,735</value>
      <webElementGuid>3abfd611-0629-4b62-8b6a-ac8559ed24cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-data-table-0&quot;)/tbody[1]/tr[1]/td[@class=&quot;highcharts-number&quot;]</value>
      <webElementGuid>84e63d64-7f97-4c72-a501-38c1c60d31ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='highcharts-data-table-0']/tbody/tr/td</value>
      <webElementGuid>2926c5cf-3543-46c4-be91-18714fac6187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Average Cost Per Year'])[2]/following::td[1]</value>
      <webElementGuid>e4f24682-bc8c-472c-9b0b-e85cd5bea3a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Used'])[3]/following::td[1]</value>
      <webElementGuid>4a4206fe-cad0-48e2-ad15-fa9aef189f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$3,193'])[3]/preceding::td[1]</value>
      <webElementGuid>feb8a953-04fd-4945-bb00-5f572270ecdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change views between Average Cost graph, and Payments graph'])[1]/preceding::td[2]</value>
      <webElementGuid>7ea8a4f3-700c-441a-9c97-ea7e671066d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td</value>
      <webElementGuid>dd5e2fdc-31a6-456d-9707-c1e8c32c42e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '$7,735' or . = '$7,735')]</value>
      <webElementGuid>c09dedba-8bc5-4e25-ace0-05912e7a3d07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
