<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Amortization</name>
   <tag></tag>
   <elementGuidId>04b9cccf-cf6f-4d1c-aed2-efc565efde3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_graph_tabs_lf_container2 > div.lf-dot-holder.lf-dot-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='lf_graph_tabs_lf_container2']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Amortization&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b5a664a8-7760-4f66-bf01-463c5b001baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-dot-holder lf-dot-label</value>
      <webElementGuid>9af8274b-97df-4274-a5a1-3bd32082fc50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Amortization</value>
      <webElementGuid>be6a74ab-1cb7-41e3-a6db-2477669099d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_graph_tabs_lf_container2&quot;)/div[@class=&quot;lf-dot-holder lf-dot-label&quot;]</value>
      <webElementGuid>4dfd223e-17a1-40d2-ad23-ecb54537a7d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='lf_graph_tabs_lf_container2']/div</value>
      <webElementGuid>887b8b84-34c3-47ad-b267-6dda65d1d452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Cost'])[1]/following::div[1]</value>
      <webElementGuid>74b930bc-5d89-4364-87d0-7ad696612499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change views between Total Cost graph, and Amortization table'])[1]/following::div[3]</value>
      <webElementGuid>0fa889f0-9133-48e6-b48e-44b318bceb08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click Here'])[1]/preceding::div[3]</value>
      <webElementGuid>280be9bf-46bd-4b1d-b169-06132d6e6df7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cs@leadfusion.com'])[1]/preceding::div[3]</value>
      <webElementGuid>55ab0b7d-557d-44b7-b32c-c06569f9da35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Amortization']/parent::*</value>
      <webElementGuid>81d9c3b9-ffa1-4515-af28-940052fa849a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/div</value>
      <webElementGuid>bd80ac86-a8de-48e6-a309-c2793f329454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Amortization' or . = 'Amortization')]</value>
      <webElementGuid>bbf224cd-af62-4a66-92d8-a351c18d7f6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
