<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Should I finance or pay cash for a vehicle</name>
   <tag></tag>
   <elementGuidId>c638db16-ea2e-40ef-b39f-73ac73c2af28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_title_label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='lf_title_label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Should I finance or pay cash for a vehicle?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>69c7bc80-9799-4bcb-a522-e15e0bc2e749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_title_label</value>
      <webElementGuid>bbd6f4a1-ba24-42e8-b0be-3570f759fbb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7ade1b55-9692-4d80-a6eb-5eb0e725925d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Should I finance or pay cash for a vehicle?</value>
      <webElementGuid>417dafb1-4708-44f9-afaf-04d78cdc6721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Should I finance or pay cash for a vehicle?</value>
      <webElementGuid>a19e6b14-727b-4517-b3f7-1a8223466537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_title_label&quot;)</value>
      <webElementGuid>213ce936-384e-4081-9699-a6b2bf06dcd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='lf_title_label']</value>
      <webElementGuid>dd4b2920-c7d4-4beb-aa89-b00dab865e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_main']/div/div/h1</value>
      <webElementGuid>e9b7132f-7567-4f49-a017-ce826af4c78d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/preceding::h1[1]</value>
      <webElementGuid>39e9c500-ff6d-4801-9404-d9d66bc8c07b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In this tool, the results display before the inputs.'])[1]/preceding::h1[1]</value>
      <webElementGuid>283a8efc-307f-42ee-b4bc-015009fa6550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Should I finance or pay cash for a vehicle?']/parent::*</value>
      <webElementGuid>a414c2a5-08dc-48db-b97b-c94bcbf3d979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>db920059-74df-49f3-a9ec-534c6d35ebee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'lf_title_label' and (text() = 'Should I finance or pay cash for a vehicle?' or . = 'Should I finance or pay cash for a vehicle?')]</value>
      <webElementGuid>bbc13a87-2ed6-4bef-93ea-cdd6191ff688</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
