<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sell Often</name>
   <tag></tag>
   <elementGuidId>47fabf0d-e27d-4bb4-a050-bd49b09fb3e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SellOften-accordion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='SellOften-accordion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Sell Often category, Click to show details,&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>37538dba-4887-4ddf-a20a-d2dcc49a1932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>da9d6ad8-f929-4b5e-8aa5-4e701342f10c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>301e773f-9b84-482a-9467-f7ba8d072afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SellOften-accordion</value>
      <webElementGuid>fe777dbd-6b55-4367-8168-32ba0ac39d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>lf-panel-SellOften</value>
      <webElementGuid>4a19c12f-7e4c-476f-835b-9a461248d04c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-accordion-label</value>
      <webElementGuid>f449ef99-c36c-4789-bb36-c94524330388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>21c5327f-26de-44b0-80fa-ee742ef7970a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Sell Often category, Click to show details,</value>
      <webElementGuid>8d06f06a-403d-42f1-93c5-7b07a68e251c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d84fbd33-3dfb-4f4a-b8eb-15009d3e37b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sell Often</value>
      <webElementGuid>f7234742-eadb-4e49-b3ca-1c5c85fde889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SellOften-accordion&quot;)</value>
      <webElementGuid>db0a7be3-c3c9-408b-8632-6be43fb051b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='SellOften-accordion']</value>
      <webElementGuid>bb05626a-d593-477d-958a-532fe2b8e9f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='lf-tab-SellOften']/div/h3/a</value>
      <webElementGuid>377a0f31-1e83-4999-9435-316a6cde9833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sell Often')]</value>
      <webElementGuid>511340e3-6413-468e-93b2-574b43566175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yearly registration'])[2]/following::a[1]</value>
      <webElementGuid>5f28ce82-e04f-4e15-9a7c-44933d59f9a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between $0 and $10,000'])[3]/following::a[1]</value>
      <webElementGuid>559496ba-cfee-4ab7-88dc-728243029301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Years before selling'])[3]/preceding::a[1]</value>
      <webElementGuid>77672c19-5309-43b1-a98e-5e6ceb6bedba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between 1 and 30'])[2]/preceding::a[1]</value>
      <webElementGuid>6881b177-c7ad-4d6b-b20c-3905b467b58e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[3]</value>
      <webElementGuid>07aea41a-4adc-4f75-9e31-d53115bd9092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/h3/a</value>
      <webElementGuid>ab4b4982-8058-4984-aaa3-f247da0e74b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'SellOften-accordion' and @href = 'javascript:void(0)' and (text() = 'Sell Often' or . = 'Sell Often')]</value>
      <webElementGuid>37022801-ad82-4fec-b06c-e7974b35c05e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
