<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Must be between 0 and 30 years_Auto_V_3f7ed3</name>
   <tag></tag>
   <elementGuidId>84628fd8-bd60-44ee-93bd-5d47fd0b69e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_Auto_VehicleAgeInYears</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lf_Auto_VehicleAgeInYears']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Vehicle age, years&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83934e2e-2483-44a6-8a04-726e23957af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Auto_VehicleAgeInYears</value>
      <webElementGuid>a0de0610-6e2f-4c95-bcc9-59fea89f78eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Auto_VehicleAgeInYears</value>
      <webElementGuid>06cd1592-5cfc-4da1-a432-0be2f6f3cd6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-input-comma</value>
      <webElementGuid>c93a2801-45e5-4806-89ac-04684620b817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f5a78ce4-afc4-44ab-834f-b86638933027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f5322e06-94de-44bb-be2a-b9ebfc008679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1ef6ff4e-df9c-4daf-8f5f-10ab5c9670e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Vehicle age, years</value>
      <webElementGuid>c308558b-b2c8-49cb-ad90-e20e7f3d9eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0f52df86-9e25-4292-9dba-804827f6e39f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Auto_VehicleAgeInYears&quot;)</value>
      <webElementGuid>14bf606e-56ac-4407-9abb-4da94227aa7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lf_Auto_VehicleAgeInYears']</value>
      <webElementGuid>57321800-07af-4398-be17-5f494eeecbad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Auto_VehicleAgeInYears-table']/div[3]/input</value>
      <webElementGuid>8aa533bc-05cf-4007-881d-b31de3ef5031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/div[3]/div/div[3]/input</value>
      <webElementGuid>7f5ccd17-25ff-401a-916a-1b42c3d26295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lf_Auto_VehicleAgeInYears' and @name = 'Auto_VehicleAgeInYears' and @type = 'text']</value>
      <webElementGuid>2b82a993-7174-4e95-b702-7448db11ecfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
