<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lease</name>
   <tag></tag>
   <elementGuidId>f0484092-c262-420a-aa97-ccec0536be98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lease-accordion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lease-accordion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Lease category, Click to show details,&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>874292eb-1001-4cbd-be9c-c1897ea94598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>658bcdf2-d6d6-41be-b9b2-246142deacbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fc942ce1-78f3-4fb9-9eb2-969df1d77a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lease-accordion</value>
      <webElementGuid>881b309e-c864-4fef-96d4-d28de23d7b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>lf-panel-lease</value>
      <webElementGuid>a8820855-a36d-4f70-86fc-3d1b8379fe86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-accordion-label</value>
      <webElementGuid>305a9e6e-8a4a-4d43-897b-1962f29bb476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>3c7c081e-42cb-4b72-8dfe-f812caeda4a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Lease category, Click to show details,</value>
      <webElementGuid>ef9a77f8-4bf3-48c7-a2f3-b22be3e9838a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1deeeda1-ae2a-4664-b89b-d3d82cefe29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lease</value>
      <webElementGuid>782f359f-72ef-4502-a84c-308124535471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lease-accordion&quot;)</value>
      <webElementGuid>b348f14e-3bf9-4ed4-9c47-a1308d428540</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lease-accordion']</value>
      <webElementGuid>ca29c459-4cc8-458c-a112-e8cecd138b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='lf-tab-lease']/div/h3/a</value>
      <webElementGuid>7c47aa50-b1e8-448c-84cf-bef1f77f25d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lease')]</value>
      <webElementGuid>06e15224-9294-46a1-b41e-646ce20369dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other upfront costs'])[2]/following::a[1]</value>
      <webElementGuid>80576121-b0f0-4b45-b7e6-c50d35d9a301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between $0 and $100,000'])[1]/following::a[1]</value>
      <webElementGuid>6e94c8fa-007d-4074-98c0-816178e6f027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly payment'])[2]/preceding::a[1]</value>
      <webElementGuid>7d8b4b96-a291-43f7-93b4-62ad3c843c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between $0 and $100,000'])[2]/preceding::a[1]</value>
      <webElementGuid>3c1cb382-e6f0-4395-ae64-9168e5f1ab44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[3]</value>
      <webElementGuid>d11d4606-f51e-4f20-b1a0-2dfadab7abc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/h3/a</value>
      <webElementGuid>70c69673-2ef5-4f68-a3da-ad5cc931bfb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'lease-accordion' and @href = 'javascript:void(0)' and (text() = 'Lease' or . = 'Lease')]</value>
      <webElementGuid>7ab120db-3f6d-4401-a358-1ec48602af54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
