<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_i_1_2_3</name>
   <tag></tag>
   <elementGuidId>bcbd67e8-d51c-4d38-899b-bef4e0fcc94e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_Auto_SecondLoanDownPayment_tooltip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lf_Auto_SecondLoanDownPayment_tooltip']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Show tooltip for Down payment&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cc3da04a-3f69-4a77-8e62-edc9f38c5cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>429d4ece-5c8a-4e42-a886-029e57f02bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#downpayment</value>
      <webElementGuid>6ea8f04c-d93b-4159-9305-d00fed787157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Auto_SecondLoanDownPayment_tooltip</value>
      <webElementGuid>2afe7b46-2e40-45a5-86de-fb291af47a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-show-tooltip</value>
      <webElementGuid>f8484a5c-e7a6-4df7-a9a0-0aa365e3a20c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Show tooltip for Down payment</value>
      <webElementGuid>62793e41-9ac8-4e89-a71a-8bedaa49c9eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d9881966-1b13-4d6f-a9e4-c77132f3d6b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>e6304115-9678-48fa-9599-2bc44bd45b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Auto_SecondLoanDownPayment_tooltip&quot;)</value>
      <webElementGuid>a4cfc248-72a2-4527-8f70-a685ef2ca8a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lf_Auto_SecondLoanDownPayment_tooltip']</value>
      <webElementGuid>1b05eb12-3cf2-458d-82e0-9e47d4f03a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Auto_SecondLoanDownPayment-table']/div/a</value>
      <webElementGuid>737c4d51-52c0-4072-89d7-deb0438063cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Down payment'])[3]/following::a[1]</value>
      <webElementGuid>4f5a81e5-ea3d-4073-b658-1694557d9b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loan term'])[2]/following::a[1]</value>
      <webElementGuid>90c70c57-6822-49cb-9ee4-8b19f766e270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between $0 and $249,999'])[2]/preceding::a[1]</value>
      <webElementGuid>ddd189fa-5e66-4e37-9550-28aae134c479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Down payment'])[4]/preceding::a[1]</value>
      <webElementGuid>a7333db5-f5a1-43c4-9bda-8a2d99a176f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#downpayment')])[2]</value>
      <webElementGuid>d9ae4c85-4078-46ba-9329-33bc25fbd518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div[3]/div[2]/div/a</value>
      <webElementGuid>efb8dc03-d506-4fd3-a4f4-2ccb236ca24d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#downpayment' and @id = 'lf_Auto_SecondLoanDownPayment_tooltip' and (text() = 'i' or . = 'i')]</value>
      <webElementGuid>9471c8f3-9391-4711-b6dc-e71cfc9b0c2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
