<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Loan 2</name>
   <tag></tag>
   <elementGuidId>8e999bed-38d6-4542-9dae-61ca1f312bc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf-legend-item-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//text[@id = 'lf-legend-item-2' and (text() = 'Loan 2' or . = 'Loan 2')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Interactive chart&quot;i >> internal:text=&quot;Loan 2&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>45564a3a-f940-4850-8196-ad1083b0fdfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>5c8b084b-f1d2-4fb3-9092-ddadb50d2a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>6c8095fb-7c85-455e-b17b-a78e6b9802ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text-anchor</name>
      <type>Main</type>
      <value>start</value>
      <webElementGuid>e6375db9-ef83-4809-b77b-d7cb0a297c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>11281aaf-7606-496a-8906-9a78a2d02af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf-legend-item-2</value>
      <webElementGuid>02b3cc4f-cc50-4e00-b522-28161622cdbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Loan 2</value>
      <webElementGuid>71fd80a0-6fa0-4022-a336-6969e23f258d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf-legend-item-2&quot;)</value>
      <webElementGuid>44527b25-830a-4d88-94dd-ee4c26e4e800</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//text[@id = 'lf-legend-item-2' and (text() = 'Loan 2' or . = 'Loan 2')]</value>
      <webElementGuid>b7c9e909-da0f-464c-aa09-51b223461b9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
