<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_i_1</name>
   <tag></tag>
   <elementGuidId>2710325a-4deb-4ff3-80f9-7d6b035e3beb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_Auto_CashRebate_tooltip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lf_Auto_CashRebate_tooltip']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Show tooltip for Cash rebate&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>38874c46-bc8b-4ea7-8b0a-9c1f35c29d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>feaa6994-c3d2-4922-a160-85ab69a88305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#cashrebate</value>
      <webElementGuid>80d6339e-131b-4d1f-8394-c83de5515784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Auto_CashRebate_tooltip</value>
      <webElementGuid>1c5d5bbd-001c-49f4-8225-d889b43de7ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-show-tooltip</value>
      <webElementGuid>f53d49f9-11e7-46d6-b678-098b8f194525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Show tooltip for Cash rebate</value>
      <webElementGuid>42e138a4-fc29-4b5a-9d17-d0b1a372845c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4b1a3765-c495-45a5-bc20-1607068b3c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>85e20039-cc82-4e22-b1ec-8e96233b4284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Auto_CashRebate_tooltip&quot;)</value>
      <webElementGuid>f7d40e19-cf8f-406c-ab3f-f3aa5e6facda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lf_Auto_CashRebate_tooltip']</value>
      <webElementGuid>3b311e05-0ab9-4dd4-baf1-d3f1c41d9f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Auto_CashRebate-table']/div/a</value>
      <webElementGuid>0985f526-8f37-4ca0-9cde-5daa2b98330b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash rebate'])[1]/following::a[1]</value>
      <webElementGuid>eb571600-c36e-4431-9590-810fb5954ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle age'])[1]/following::a[1]</value>
      <webElementGuid>7d900b6c-ff3b-4b92-9207-05e8e41fb2a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between $0 and $1,000,000'])[2]/preceding::a[1]</value>
      <webElementGuid>b3fb2408-06ae-41f7-a8a8-10cfa6268b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash rebate'])[2]/preceding::a[1]</value>
      <webElementGuid>37627fb7-3e1b-4546-8213-e41c5767a45f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#cashrebate')]</value>
      <webElementGuid>51bf0055-0281-482b-87a9-712ffce411dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div[3]/div[3]/div/a</value>
      <webElementGuid>aa208be7-3bdc-4901-bacc-58c63ce06aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#cashrebate' and @id = 'lf_Auto_CashRebate_tooltip' and (text() = 'i' or . = 'i')]</value>
      <webElementGuid>1c5db78c-662c-407a-823f-5f5b423a5cfa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
