<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Total interest paid</name>
   <tag></tag>
   <elementGuidId>a6191169-52c4-4add-9465-a456e3aca645</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_TotIntPaidAuto03_result_label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='lf_TotIntPaidAuto03_result_label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=rowheader[name=&quot;Total interest paid&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>999ed298-9cef-49d9-b978-9f18ee9bfd68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_TotIntPaidAuto03_result_label</value>
      <webElementGuid>e81baf75-a736-4664-9703-748c7e7e8f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableCellADA</value>
      <webElementGuid>44e5ace2-1f53-4fe7-b7ef-81824c48b965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>305188a7-21fa-4cc4-8fe4-e0bd0114ddb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Total interest paid
                                        </value>
      <webElementGuid>322a7b7b-9667-4597-8093-5be4777594fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_TotIntPaidAuto03_result_label&quot;)</value>
      <webElementGuid>b6558a5c-6222-4dd2-8675-56b9d43137b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//th[@id='lf_TotIntPaidAuto03_result_label']</value>
      <webElementGuid>14602f9c-6d58-4496-a46b-da140a386fbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='lf_TotIntPaidAuto03_results']/th</value>
      <webElementGuid>fd9adc9f-ad0d-4f73-b034-7a44ce62bd38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$250'])[1]/following::th[1]</value>
      <webElementGuid>abeaa77d-3108-4fa3-bf94-91aad355b278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$875'])[1]/following::th[1]</value>
      <webElementGuid>ed971e0e-32bd-4d83-98e3-ce853e39ac41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$4,005'])[1]/preceding::th[1]</value>
      <webElementGuid>d68050f4-a7ad-4ad4-b207-4793e6f0c16d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N/A'])[1]/preceding::th[1]</value>
      <webElementGuid>90fa0365-b532-4a79-bd0b-9c7c0659de97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Total interest paid']/parent::*</value>
      <webElementGuid>75f70cdb-d9c4-4145-bdf8-d6970e72f521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/th</value>
      <webElementGuid>8e3b519d-0f86-4926-bbce-1f8360050baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[@id = 'lf_TotIntPaidAuto03_result_label' and (text() = '
                                            Total interest paid
                                        ' or . = '
                                            Total interest paid
                                        ')]</value>
      <webElementGuid>02e10cb2-1714-40cf-8263-03d991147f61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
