<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_New Vehicle Loan</name>
   <tag></tag>
   <elementGuidId>1eb4b215-45a8-4d6a-abcf-b863824236de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NewVehicleLoan-accordion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='NewVehicleLoan-accordion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8731c70b-7419-4fc8-80c5-d00bae935de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>143d80e6-9f89-4c58-a11d-a9cdb51f5cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e3e10ef3-d308-4ee2-886d-48bf4cbcf961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NewVehicleLoan-accordion</value>
      <webElementGuid>95445c21-429e-46f0-b7d5-7a564a2b0f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>lf-panel-NewVehicleLoan</value>
      <webElementGuid>fc6379dd-440e-4b37-be23-f4b09ef21997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-accordion-label</value>
      <webElementGuid>416177bd-c986-456b-9f17-e88e906daef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>ea5be21a-29c8-4649-b535-b21146046d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Current selection, New Vehicle Loan category, Click to hide details,</value>
      <webElementGuid>81a49826-3639-40f7-860f-460fd07563ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New Vehicle Loan</value>
      <webElementGuid>9bb599a6-8eed-45e6-9f45-545da95cb13f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewVehicleLoan-accordion&quot;)</value>
      <webElementGuid>c9ed66a0-b5dc-4548-809f-7d85a79b7f6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='NewVehicleLoan-accordion']</value>
      <webElementGuid>aab6f1fa-3363-4f9e-a5cb-6201948b85df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='lf-tab-NewVehicleLoan']/div/h3/a</value>
      <webElementGuid>26ac535f-bd7f-4019-8d54-73452837d500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'New Vehicle Loan')]</value>
      <webElementGuid>439493da-6813-4fca-af7f-cbb30f09e637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inputs'])[1]/following::a[1]</value>
      <webElementGuid>a316f22c-96a9-42cf-9790-39e83d660276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cs@leadfusion.com'])[1]/following::a[1]</value>
      <webElementGuid>eca226a7-e00b-40d5-b3ff-531868a8e202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase price'])[1]/preceding::a[1]</value>
      <webElementGuid>839d12f3-76f9-40a8-9813-6ca6a2d410b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between $0 and $1,000,000'])[1]/preceding::a[1]</value>
      <webElementGuid>fee9677d-3817-45d5-a536-7a01bac675ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New Vehicle Loan']/parent::*</value>
      <webElementGuid>467e3686-a6c9-4707-8150-fd28249e1ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>6e5d35a4-e21c-4861-8714-cf38ede203a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>1ee4351c-5ca2-40e0-84a9-94b3a5c05262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'NewVehicleLoan-accordion' and @href = 'javascript:void(0)' and (text() = 'New Vehicle Loan' or . = 'New Vehicle Loan')]</value>
      <webElementGuid>4591e7e2-531d-49ab-9568-9e9c7ea03321</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
