<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>graph_2_description</name>
   <tag></tag>
   <elementGuidId>01e66d30-f297-4fdc-bf3e-a7a549658b50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;highcharts-upna329-0&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;highcharts-series-group&quot;]/g[@class=&quot;highcharts-series highcharts-series-0 highcharts-column-series highcharts-color-0 highcharts-tracker highcharts-series-hover&quot;]/path[@class=&quot;highcharts-point highcharts-color-0 highcharts-point-hover&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'lf_container2']&#xd;
 </value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>path.highcharts-point.highcharts-color-0.highcharts-point-hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>ab8f7a6e-ae96-400e-90f5-5c7ea3a78121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>rgb(65,149,183)</value>
      <webElementGuid>f4bbce55-55f3-4421-9656-5d64497d69e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M 35.5 65.5 L 247.5 65.5 A 3 3 0 0 1 250.5 68.5 L 250.5 287.5 A 0 0 0 0 1 250.5 287.5 L 32.5 287.5 A 0 0 0 0 1 32.5 287.5 L 32.5 68.5 A 3 3 0 0 1 35.5 65.5 Z</value>
      <webElementGuid>81ae13de-7ecc-4101-9d2a-2d31fe8e0305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#cccccc</value>
      <webElementGuid>069f2c5d-0710-4957-96b2-c3ea79ba0a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>09d57f92-ff51-418c-ac2a-ca290cd7ab31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>opacity</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b4687bd8-9f18-477f-afda-7eedb151d3c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>filter</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>d7cc3a1a-67aa-4624-afe6-7ab92915df04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>highcharts-point highcharts-color-0 highcharts-point-hover</value>
      <webElementGuid>7cbcb1cb-4b60-4e79-8b94-10c0acc69b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3cba357d-497d-4dab-8f33-b79e5ece1245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b1a1c7ea-2a06-4290-a280-df990d3f3da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Average Cost Per Year, New: $7,735</value>
      <webElementGuid>f8bef474-5711-479e-abe2-7d08edd9f55f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-upna329-0&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;highcharts-series-group&quot;]/g[@class=&quot;highcharts-series highcharts-series-0 highcharts-column-series highcharts-color-0 highcharts-tracker highcharts-series-hover&quot;]/path[@class=&quot;highcharts-point highcharts-color-0 highcharts-point-hover&quot;]</value>
      <webElementGuid>db60be84-9456-4514-af17-3cbc356a6b53</webElementGuid>
   </webElementProperties>
</WebElementEntity>
