<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_20,039</name>
   <tag></tag>
   <elementGuidId>bc6cf5d0-3436-431f-8b3e-67e4893e85ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_MonPmtAuto01_result_value > span.lf-nbsp-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='lf_MonPmtAuto01_result_value']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c09dc48e-59fa-4d66-b295-73156c8754ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-nbsp-number</value>
      <webElementGuid>ed23657e-9dc6-4501-9cbb-50fbc7385ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$20,039</value>
      <webElementGuid>27f2e7b1-5fbe-4ba3-bb50-1782a770935b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_MonPmtAuto01_result_value&quot;)/span[@class=&quot;lf-nbsp-number&quot;]</value>
      <webElementGuid>6489151e-4d84-4fc7-96ae-f260b20ca539</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='lf_MonPmtAuto01_result_value']/span</value>
      <webElementGuid>18f995ab-f035-40c4-93c4-41ee350a3c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly payment'])[1]/following::span[1]</value>
      <webElementGuid>f0495622-05de-4929-86ea-10532d7dc122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$4,210'])[1]/following::span[1]</value>
      <webElementGuid>e480e064-a298-4e60-8610-682cf7e127a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$976'])[1]/preceding::span[1]</value>
      <webElementGuid>1ac1e697-b4ee-4dfd-8913-76bfa6edc140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total interest paid'])[1]/preceding::span[2]</value>
      <webElementGuid>21c6fa01-3e9c-4891-83e2-ce03508064a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$20,039']/parent::*</value>
      <webElementGuid>0d6804f8-365a-4604-a5c5-832f5f55754d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/span</value>
      <webElementGuid>2ad0157d-c404-4612-afa7-3dc3e5733233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '$20,039' or . = '$20,039')]</value>
      <webElementGuid>968a07fd-525f-4aa8-b98d-ef9edd8a280c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
