<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Must be between 0 and 1,000,000_Globa_761fb6</name>
   <tag></tag>
   <elementGuidId>17e338b5-dae0-490b-bedc-0f43e635e48d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_Global_AutoPurchasePrice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lf_Global_AutoPurchasePrice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Purchase price, in dollars&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10ca456e-ab45-4ca2-a14e-58edd2ea98fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Global_AutoPurchasePrice</value>
      <webElementGuid>ea8fdd57-5237-4942-a800-9a8e2df511af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Global_AutoPurchasePrice</value>
      <webElementGuid>e9cc3f44-5f05-4f58-b0d0-bffba050f729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-input-comma</value>
      <webElementGuid>04339a2e-97a9-4224-a35b-b2d3633a3234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>22dcedec-fb35-44e7-84e5-bd602e94f631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>40000</value>
      <webElementGuid>2c03ad24-3424-4400-b5f6-cd9dd2adfe11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>0209be37-bf11-4279-9402-21d9b930a72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Purchase price, in dollars</value>
      <webElementGuid>0a78cb40-04aa-4038-a63d-e3b37688629c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>93e8b79c-65a7-4b37-be11-2834f557da94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Global_AutoPurchasePrice&quot;)</value>
      <webElementGuid>b8a5fba8-f287-476a-90ef-ed4de0c4cc78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lf_Global_AutoPurchasePrice']</value>
      <webElementGuid>207fcef7-8faf-4a9e-8bef-e720e0c529b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Global_AutoPurchasePrice-table']/div[3]/input</value>
      <webElementGuid>8935f52f-4927-4b64-99ed-55318ce617ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>5d3f2f14-4acb-4c24-918c-d2d459ecdd2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lf_Global_AutoPurchasePrice' and @name = 'Global_AutoPurchasePrice' and @type = 'text']</value>
      <webElementGuid>5dc2a052-9ff1-4d9c-a1ab-5e27d14a9e9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
