<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Monthly payment</name>
   <tag></tag>
   <elementGuidId>5d9dd5c6-a0ed-427e-82c4-c4d2b2c5c551</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#col-2 > span.lf-table-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='col-2']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=columnheader[name=&quot;Monthly payment&quot;i] >> span</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b6b800d9-300d-46c5-93f1-9931cd7ab053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-table-header</value>
      <webElementGuid>907cb6f5-cb9e-47c9-95e3-a5dedaf36b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Monthly payment</value>
      <webElementGuid>62fc8160-194b-4215-8f8d-0c4d226b1565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;col-2&quot;)/span[@class=&quot;lf-table-header&quot;]</value>
      <webElementGuid>99c65960-bb73-4e3a-bd28-5f6d5338c6ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='col-2']/span</value>
      <webElementGuid>5b0d84b1-4ccf-4ee3-8548-9bb83a2d53e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Month'])[1]/following::span[1]</value>
      <webElementGuid>fa8185b8-a146-4aeb-b8f6-0e8bfb970e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Schedule - Home Equity Loan'])[6]/following::span[2]</value>
      <webElementGuid>e6095e89-e5f5-4dad-8d1b-29afbe3ad921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Balance'])[1]/preceding::span[1]</value>
      <webElementGuid>2a8337ed-80a2-460a-8238-8f6dc5794770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Principal paid'])[1]/preceding::span[2]</value>
      <webElementGuid>3ed93da9-0af7-436b-90d3-f9cb021d9ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]/span</value>
      <webElementGuid>5f10ef31-8156-43f3-97b2-33ebf8addc23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Monthly payment' or . = 'Monthly payment')]</value>
      <webElementGuid>66e04a07-273e-4356-9ae9-f0e9bd397575</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
