<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Balance</name>
   <tag></tag>
   <elementGuidId>7d64d7fe-0f5f-4293-9347-fcfb0ffbdf00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#col-3 > span.lf-table-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='col-3']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Balance&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>459df5e6-9f13-4e34-b0b0-d81464410088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-table-header</value>
      <webElementGuid>ef7e6bd3-3888-4d11-ae81-707397cd1b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Balance</value>
      <webElementGuid>c5bf08ca-bb5a-4abb-b985-b4fe7de66b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;col-3&quot;)/span[@class=&quot;lf-table-header&quot;]</value>
      <webElementGuid>af6d8358-7a3f-4a9b-943f-ea2e3ca548f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='col-3']/span</value>
      <webElementGuid>0381642d-8c33-44ac-b822-b24d0636b135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly payment'])[2]/following::span[1]</value>
      <webElementGuid>01edff73-8d5f-4bf1-8b47-bdebf2d5b007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Month'])[1]/following::span[2]</value>
      <webElementGuid>f56b65e4-2a0f-419e-b300-2a91e166cf29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Principal paid'])[1]/preceding::span[1]</value>
      <webElementGuid>b1967316-3228-4a72-9ea4-90ea6dd6cd6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interest paid'])[1]/preceding::span[2]</value>
      <webElementGuid>fba0ce43-c330-4f83-9fad-016f9d0caf11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Balance']/parent::*</value>
      <webElementGuid>7f57fbbc-c4f4-4be4-b800-df5dcf4710ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/span</value>
      <webElementGuid>eebda782-1dd7-45d7-8e16-b7487d0809f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Balance' or . = 'Balance')]</value>
      <webElementGuid>ca7b5340-34f0-4af6-9be1-9a160dfb61d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
