<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_2,664</name>
   <tag></tag>
   <elementGuidId>a9426510-5bab-4f38-8a2e-c16d08070bef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_TotInt1CreditLn03_result_value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='lf_TotInt1CreditLn03_result_value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;$2,664&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c5540272-3a6a-424b-8c07-cdcc9dcb4ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_TotInt1CreditLn03_result_value</value>
      <webElementGuid>9e3e9dc5-8012-4b4b-a039-c97b135d47b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableCellADA </value>
      <webElementGuid>9855b2a2-7e53-4104-b579-20eacdfa7b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$2,664
                                        </value>
      <webElementGuid>b368b4d5-3827-46ba-957a-0c09d76e70b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_TotInt1CreditLn03_result_value&quot;)</value>
      <webElementGuid>c5654f84-73e1-4556-bfc8-2ef46d86bb96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='lf_TotInt1CreditLn03_result_value']</value>
      <webElementGuid>082a5b00-6f32-4da2-b03d-6605c73992ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='lf_TotInt2CreditLn03_results']/td[2]</value>
      <webElementGuid>4e7b9d03-d4a1-4172-92d2-93b8f9f3508b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$3,964'])[1]/following::td[1]</value>
      <webElementGuid>1a956c6f-d4d6-48c3-a748-b136e81179f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total interest paid'])[1]/following::td[2]</value>
      <webElementGuid>280e20d4-6a0f-487f-9222-9ad7ef1cc857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total tax savings'])[1]/preceding::td[1]</value>
      <webElementGuid>870fcdb2-99b6-4abb-91d2-ff146acc31f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]</value>
      <webElementGuid>d610f6e6-3e43-4954-b99c-0fc5997d9399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'lf_TotInt1CreditLn03_result_value' and (text() = '$2,664
                                        ' or . = '$2,664
                                        ')]</value>
      <webElementGuid>75eb4d8f-049c-4722-89b8-fcd89d82ed6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
