<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Total tax savings</name>
   <tag></tag>
   <elementGuidId>11f65fb5-81ea-449a-9f57-49c8af92e97e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_TaxSavings2CreditLn03_result_label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='lf_TaxSavings2CreditLn03_result_label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=rowheader[name=&quot;Total tax savings&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>84358da2-0d2b-46fd-b39b-3264a52f8481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_TaxSavings2CreditLn03_result_label</value>
      <webElementGuid>20953613-952b-4e25-9836-6229755723f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableCellADA</value>
      <webElementGuid>554888b9-4cf3-42d0-ac9d-d099d6ad0453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>29ad80bc-5a72-4336-8efe-884ac55ca9a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Total tax savings
                                        </value>
      <webElementGuid>22bb7369-735b-47a7-a606-03992b268ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_TaxSavings2CreditLn03_result_label&quot;)</value>
      <webElementGuid>0e6af319-8e1a-4b03-988a-4882cc8700ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//th[@id='lf_TaxSavings2CreditLn03_result_label']</value>
      <webElementGuid>33f2aae5-ad99-474c-9bce-d73a44f5d4f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='lf_TaxSavings2CreditLn03_results']/th</value>
      <webElementGuid>2c9bc728-3457-4cea-84e6-a9d219ebb042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$4,005'])[1]/following::th[1]</value>
      <webElementGuid>34a2c983-c360-479b-a322-24ba4f10268a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$3,552'])[1]/following::th[1]</value>
      <webElementGuid>032d9d2d-ffeb-4561-ae89-3bcd0c7b3acd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1,200'])[1]/preceding::th[1]</value>
      <webElementGuid>6deb4ac9-801a-4401-aa12-acff190b36a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N/A'])[1]/preceding::th[1]</value>
      <webElementGuid>e842575f-b91d-466c-87a1-f74aa261a960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Total tax savings']/parent::*</value>
      <webElementGuid>9bbd0d4a-dbdb-40da-981d-d23fb099d5f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/th</value>
      <webElementGuid>89393114-bdfd-4f7d-bc99-7790262457d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[@id = 'lf_TaxSavings2CreditLn03_result_label' and (text() = '
                                            Total tax savings
                                        ' or . = '
                                            Total tax savings
                                        ')]</value>
      <webElementGuid>233684f1-ee6c-4fd8-a2fe-ae3322508412</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
