<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Taxes  Depreciation</name>
   <tag></tag>
   <elementGuidId>cb5648e0-175c-480f-b588-85d326ded4a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TaxesDepreciation-accordion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='TaxesDepreciation-accordion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d31c8c6c-161e-4363-8ddc-49a97bbe1abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>425a6cf9-d62b-4398-8ff0-36a1f2a42161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>824adbc1-bf98-4ce3-9f45-934340781cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TaxesDepreciation-accordion</value>
      <webElementGuid>114d1831-203d-4924-940b-e7ce590a98e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>lf-panel-TaxesDepreciation</value>
      <webElementGuid>f7617041-ed50-47cf-b8d2-f783e6001ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-accordion-label</value>
      <webElementGuid>a109a5f3-522e-41b0-a6b3-ebd9d60345cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>07725148-7009-4bbf-aba1-0ce888230882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Taxes &amp; Depreciation category, Click to show details,</value>
      <webElementGuid>212284e2-e40f-4335-a1ce-d81fcff0e43c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Taxes &amp; Depreciation</value>
      <webElementGuid>030598ce-a484-414e-ac0d-1c4e10b3c8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TaxesDepreciation-accordion&quot;)</value>
      <webElementGuid>87221a26-d225-4db5-a34a-6d8e9c78c227</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='TaxesDepreciation-accordion']</value>
      <webElementGuid>c41e55ff-9b96-4509-af5f-de847e3a2982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='lf-tab-TaxesDepreciation']/div/h3/a</value>
      <webElementGuid>db8b474b-328b-40cf-b84b-e79f2bdf6131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Taxes &amp; Depreciation')]</value>
      <webElementGuid>99c2d8ef-d8a8-4486-a4bf-715a1df5e3d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registration costs'])[4]/following::a[1]</value>
      <webElementGuid>fb13ee67-5fe0-4940-a438-c3c1b485bc87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between $0 and $100,000'])[2]/following::a[1]</value>
      <webElementGuid>9627a855-7887-4a0b-9b48-cd6d2516a578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your state &amp; federal tax rate'])[1]/preceding::a[1]</value>
      <webElementGuid>513f6ec1-7209-437b-8875-69298274fd4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be between 0.00% and 90.00%'])[1]/preceding::a[2]</value>
      <webElementGuid>4072b931-a21f-4beb-8094-994141e68408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Taxes &amp; Depreciation']/parent::*</value>
      <webElementGuid>9af8263c-394f-40eb-9643-1773a76fbe30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[5]</value>
      <webElementGuid>4fb0b666-b7b3-47a9-83dc-e17f30e4240d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[5]/div/h3/a</value>
      <webElementGuid>2d4a5c0d-72c8-414e-bc67-c181688c1944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'TaxesDepreciation-accordion' and @href = 'javascript:void(0)' and (text() = 'Taxes &amp; Depreciation' or . = 'Taxes &amp; Depreciation')]</value>
      <webElementGuid>46d0cf09-ed46-4408-8761-d2107b72ac48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
