<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_lf-legend-item-2</name>
   <tag></tag>
   <elementGuidId>943f5cd0-38f0-446e-9436-9f64d2d50ff0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Total']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lf-legend-item-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Total&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a0dbf8e1-d8e5-4ffa-b313-d792780d975b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>0292acaa-e6a1-4124-8a6d-5c8577b112be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>d9a67b89-4b70-4ff3-bab7-50851126a6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text-anchor</name>
      <type>Main</type>
      <value>start</value>
      <webElementGuid>5d778f7e-b8c7-4da9-b84d-aa9275d52bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>933c43f9-5c87-4a0c-8abe-9d7211d1e722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf-legend-item-2</value>
      <webElementGuid>87a4dfcf-332b-4837-b9b1-7d26f5bc02c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Total</value>
      <webElementGuid>5fc85162-7cf7-482b-8089-f041658f2c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf-legend-item-2&quot;)</value>
      <webElementGuid>e4ac3089-c826-493f-a5b9-486dd9760c04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Total']/parent::*</value>
      <webElementGuid>d8510988-cc89-400b-b5b4-9cf86a42aca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//text[@id = 'lf-legend-item-2' and (text() = 'Total' or . = 'Total')]</value>
      <webElementGuid>e9dff64b-cea3-4304-b427-91ca030affac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
