<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Must be between 0 and 200,000_Auto_Ou_c3de58</name>
   <tag></tag>
   <elementGuidId>0f0ff002-14a7-4244-9579-8de728bd5dc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf_Auto_OutstandingLoanAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lf_Auto_OutstandingLoanAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Amount owed on trade-in, in dollars&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6560d9c-dc65-4a8e-8821-b3bc6f9d1fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf_Auto_OutstandingLoanAmount</value>
      <webElementGuid>aa0da509-43bd-4668-9ccd-6a261a02fa28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Auto_OutstandingLoanAmount</value>
      <webElementGuid>d5727fc1-ca0d-4153-9b0a-56717c57c6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lf-input-comma</value>
      <webElementGuid>f382c1cf-21b7-4f0b-b6ad-dcd74433a7ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>626bdfb9-75b3-40db-b96c-5544c72571bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7acee2a2-c24b-4f6d-8863-13d15e270709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>1e9d897d-9ca4-44ce-b5ff-be1ae7825c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Amount owed on trade-in, in dollars</value>
      <webElementGuid>23cf67b4-6199-4067-bbec-c410a2094e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-listener-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ecccadc9-f329-4a9e-a5fd-c3641973b7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf_Auto_OutstandingLoanAmount&quot;)</value>
      <webElementGuid>8c2da67b-0e36-4e18-b828-3f4ee70f0c7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lf_Auto_OutstandingLoanAmount']</value>
      <webElementGuid>9b530e60-4b0c-4fb9-a891-4105ffce9961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lf_Auto_OutstandingLoanAmount_container']/div[3]/input</value>
      <webElementGuid>2a3609ee-d636-4cb3-9e89-f349cb4cd423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/div/div[3]/div[3]/input</value>
      <webElementGuid>ea09ca8b-b121-4574-bc26-091678435553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lf_Auto_OutstandingLoanAmount' and @name = 'Auto_OutstandingLoanAmount' and @type = 'text']</value>
      <webElementGuid>1488f5d4-e5fa-492a-9d80-a1405d9932c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
